#!/bin/sh

# This TACACS server need bind to port 49, because SONiC load_minigraph only support port 49
TACPLUS_PORT=49
LOCKFILE=/var/run/tacacs_daily_daemon.lock

# Always kill running tac_plus process on port $TACPLUS_PORT to reload config
# It will be start later by tacacs_daily_daemon
TACPLUS_PID=$(ps -ef | grep "tac_plus .* -p $TACPLUS_PORT" | grep -v "grep" |  awk '{print $2}')
if [ $TACPLUS_PID ]; then
    echo "tac_plus already running on port $TACPLUS_PORT, stop it to reload config"
    kill -9 $TACPLUS_PID
fi

exec 9>"$LOCKFILE"
# Exit if tacacs_daily_daemon already running in background
if ! flock -n 9; then
    echo "tacacs_daily_daemon already running in background"
    exit 0
fi

echo "starting tac_plus for daily work"
while true;
do
    # start tac_plus will kill existed tac_plus instance bind to same port
    # Enable Authentication/Authorization/Accounting debug by: -d 88
    /usr/sbin/tac_plus -d 88 -l /var/log/tac_plus_daily.log -C /etc/tac_plus_daily.conf  -p $TACPLUS_PORT -G
    echo "tac_plus existed, restarting"
done
