# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nic_simulator_grpc_mgmt_service_pb2 as nic__simulator__grpc__mgmt__service__pb2


class DualTorMgmtServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryAdminForwardingPortState = channel.unary_unary(
                '/DualTorMgmtService/QueryAdminForwardingPortState',
                request_serializer=nic__simulator__grpc__mgmt__service__pb2.ListOfAdminRequest.SerializeToString,
                response_deserializer=nic__simulator__grpc__mgmt__service__pb2.ListOfAdminReply.FromString,
                )
        self.SetAdminForwardingPortState = channel.unary_unary(
                '/DualTorMgmtService/SetAdminForwardingPortState',
                request_serializer=nic__simulator__grpc__mgmt__service__pb2.ListOfAdminRequest.SerializeToString,
                response_deserializer=nic__simulator__grpc__mgmt__service__pb2.ListOfAdminReply.FromString,
                )
        self.QueryOperationPortState = channel.unary_unary(
                '/DualTorMgmtService/QueryOperationPortState',
                request_serializer=nic__simulator__grpc__mgmt__service__pb2.ListOfOperationRequest.SerializeToString,
                response_deserializer=nic__simulator__grpc__mgmt__service__pb2.ListOfOperationReply.FromString,
                )
        self.SetDrop = channel.unary_unary(
                '/DualTorMgmtService/SetDrop',
                request_serializer=nic__simulator__grpc__mgmt__service__pb2.ListOfDropRequest.SerializeToString,
                response_deserializer=nic__simulator__grpc__mgmt__service__pb2.ListOfDropReply.FromString,
                )


class DualTorMgmtServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryAdminForwardingPortState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAdminForwardingPortState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOperationPortState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDrop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DualTorMgmtServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryAdminForwardingPortState': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAdminForwardingPortState,
                    request_deserializer=nic__simulator__grpc__mgmt__service__pb2.ListOfAdminRequest.FromString,
                    response_serializer=nic__simulator__grpc__mgmt__service__pb2.ListOfAdminReply.SerializeToString,
            ),
            'SetAdminForwardingPortState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAdminForwardingPortState,
                    request_deserializer=nic__simulator__grpc__mgmt__service__pb2.ListOfAdminRequest.FromString,
                    response_serializer=nic__simulator__grpc__mgmt__service__pb2.ListOfAdminReply.SerializeToString,
            ),
            'QueryOperationPortState': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOperationPortState,
                    request_deserializer=nic__simulator__grpc__mgmt__service__pb2.ListOfOperationRequest.FromString,
                    response_serializer=nic__simulator__grpc__mgmt__service__pb2.ListOfOperationReply.SerializeToString,
            ),
            'SetDrop': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDrop,
                    request_deserializer=nic__simulator__grpc__mgmt__service__pb2.ListOfDropRequest.FromString,
                    response_serializer=nic__simulator__grpc__mgmt__service__pb2.ListOfDropReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DualTorMgmtService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DualTorMgmtService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryAdminForwardingPortState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DualTorMgmtService/QueryAdminForwardingPortState',
            nic__simulator__grpc__mgmt__service__pb2.ListOfAdminRequest.SerializeToString,
            nic__simulator__grpc__mgmt__service__pb2.ListOfAdminReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAdminForwardingPortState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DualTorMgmtService/SetAdminForwardingPortState',
            nic__simulator__grpc__mgmt__service__pb2.ListOfAdminRequest.SerializeToString,
            nic__simulator__grpc__mgmt__service__pb2.ListOfAdminReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryOperationPortState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DualTorMgmtService/QueryOperationPortState',
            nic__simulator__grpc__mgmt__service__pb2.ListOfOperationRequest.SerializeToString,
            nic__simulator__grpc__mgmt__service__pb2.ListOfOperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDrop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DualTorMgmtService/SetDrop',
            nic__simulator__grpc__mgmt__service__pb2.ListOfDropRequest.SerializeToString,
            nic__simulator__grpc__mgmt__service__pb2.ListOfDropReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
