# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nic_simulator_grpc_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nic_simulator_grpc_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n nic_simulator_grpc_service.proto\"-\n\x0c\x41\x64minRequest\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\r\n\x05state\x18\x02 \x03(\x08\"+\n\nAdminReply\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\r\n\x05state\x18\x02 \x03(\x08\"\"\n\x10OperationRequest\x12\x0e\n\x06portid\x18\x01 \x03(\x05\"/\n\x0eOperationReply\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\r\n\x05state\x18\x02 \x03(\x08\"\"\n\x10LinkStateRequest\x12\x0e\n\x06portid\x18\x01 \x03(\x05\"/\n\x0eLinkStateReply\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\r\n\x05state\x18\x02 \x03(\x08\"\'\n\x14ServerVersionRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\"%\n\x12ServerVersionReply\x12\x0f\n\x07version\x18\x01 \x01(\t\"A\n\x0b\x44ropRequest\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\x11\n\tdirection\x18\x02 \x03(\x05\x12\x0f\n\x07recover\x18\x03 \x01(\x08\",\n\tDropReply\x12\x0e\n\x06portid\x18\x01 \x03(\x05\x12\x0f\n\x07success\x18\x02 \x03(\x08\x32\xef\x02\n\rDualToRActive\x12=\n\x1dQueryAdminForwardingPortState\x12\r.AdminRequest\x1a\x0b.AdminReply\"\x00\x12;\n\x1bSetAdminForwardingPortState\x12\r.AdminRequest\x1a\x0b.AdminReply\"\x00\x12?\n\x17QueryOperationPortState\x12\x11.OperationRequest\x1a\x0f.OperationReply\"\x00\x12\x36\n\x0eQueryLinkState\x12\x11.LinkStateRequest\x1a\x0f.LinkStateReply\"\x00\x12\x42\n\x12QueryServerVersion\x12\x15.ServerVersionRequest\x1a\x13.ServerVersionReply\"\x00\x12%\n\x07SetDrop\x12\x0c.DropRequest\x1a\n.DropReply\"\x00\x62\x06proto3'
)




_ADMINREQUEST = _descriptor.Descriptor(
  name='AdminRequest',
  full_name='AdminRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portid', full_name='AdminRequest.portid', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='AdminRequest.state', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=81,
)


_ADMINREPLY = _descriptor.Descriptor(
  name='AdminReply',
  full_name='AdminReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portid', full_name='AdminReply.portid', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='AdminReply.state', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=126,
)


_OPERATIONREQUEST = _descriptor.Descriptor(
  name='OperationRequest',
  full_name='OperationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portid', full_name='OperationRequest.portid', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=162,
)


_OPERATIONREPLY = _descriptor.Descriptor(
  name='OperationReply',
  full_name='OperationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portid', full_name='OperationReply.portid', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='OperationReply.state', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=211,
)


_LINKSTATEREQUEST = _descriptor.Descriptor(
  name='LinkStateRequest',
  full_name='LinkStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portid', full_name='LinkStateRequest.portid', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=247,
)


_LINKSTATEREPLY = _descriptor.Descriptor(
  name='LinkStateReply',
  full_name='LinkStateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portid', full_name='LinkStateReply.portid', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='LinkStateReply.state', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=296,
)


_SERVERVERSIONREQUEST = _descriptor.Descriptor(
  name='ServerVersionRequest',
  full_name='ServerVersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ServerVersionRequest.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=337,
)


_SERVERVERSIONREPLY = _descriptor.Descriptor(
  name='ServerVersionReply',
  full_name='ServerVersionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ServerVersionReply.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=376,
)


_DROPREQUEST = _descriptor.Descriptor(
  name='DropRequest',
  full_name='DropRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portid', full_name='DropRequest.portid', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='DropRequest.direction', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recover', full_name='DropRequest.recover', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=443,
)


_DROPREPLY = _descriptor.Descriptor(
  name='DropReply',
  full_name='DropReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portid', full_name='DropReply.portid', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='DropReply.success', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=489,
)

DESCRIPTOR.message_types_by_name['AdminRequest'] = _ADMINREQUEST
DESCRIPTOR.message_types_by_name['AdminReply'] = _ADMINREPLY
DESCRIPTOR.message_types_by_name['OperationRequest'] = _OPERATIONREQUEST
DESCRIPTOR.message_types_by_name['OperationReply'] = _OPERATIONREPLY
DESCRIPTOR.message_types_by_name['LinkStateRequest'] = _LINKSTATEREQUEST
DESCRIPTOR.message_types_by_name['LinkStateReply'] = _LINKSTATEREPLY
DESCRIPTOR.message_types_by_name['ServerVersionRequest'] = _SERVERVERSIONREQUEST
DESCRIPTOR.message_types_by_name['ServerVersionReply'] = _SERVERVERSIONREPLY
DESCRIPTOR.message_types_by_name['DropRequest'] = _DROPREQUEST
DESCRIPTOR.message_types_by_name['DropReply'] = _DROPREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdminRequest = _reflection.GeneratedProtocolMessageType('AdminRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADMINREQUEST,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:AdminRequest)
  })
_sym_db.RegisterMessage(AdminRequest)

AdminReply = _reflection.GeneratedProtocolMessageType('AdminReply', (_message.Message,), {
  'DESCRIPTOR' : _ADMINREPLY,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:AdminReply)
  })
_sym_db.RegisterMessage(AdminReply)

OperationRequest = _reflection.GeneratedProtocolMessageType('OperationRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONREQUEST,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:OperationRequest)
  })
_sym_db.RegisterMessage(OperationRequest)

OperationReply = _reflection.GeneratedProtocolMessageType('OperationReply', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONREPLY,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:OperationReply)
  })
_sym_db.RegisterMessage(OperationReply)

LinkStateRequest = _reflection.GeneratedProtocolMessageType('LinkStateRequest', (_message.Message,), {
  'DESCRIPTOR' : _LINKSTATEREQUEST,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:LinkStateRequest)
  })
_sym_db.RegisterMessage(LinkStateRequest)

LinkStateReply = _reflection.GeneratedProtocolMessageType('LinkStateReply', (_message.Message,), {
  'DESCRIPTOR' : _LINKSTATEREPLY,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:LinkStateReply)
  })
_sym_db.RegisterMessage(LinkStateReply)

ServerVersionRequest = _reflection.GeneratedProtocolMessageType('ServerVersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVERVERSIONREQUEST,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:ServerVersionRequest)
  })
_sym_db.RegisterMessage(ServerVersionRequest)

ServerVersionReply = _reflection.GeneratedProtocolMessageType('ServerVersionReply', (_message.Message,), {
  'DESCRIPTOR' : _SERVERVERSIONREPLY,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:ServerVersionReply)
  })
_sym_db.RegisterMessage(ServerVersionReply)

DropRequest = _reflection.GeneratedProtocolMessageType('DropRequest', (_message.Message,), {
  'DESCRIPTOR' : _DROPREQUEST,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:DropRequest)
  })
_sym_db.RegisterMessage(DropRequest)

DropReply = _reflection.GeneratedProtocolMessageType('DropReply', (_message.Message,), {
  'DESCRIPTOR' : _DROPREPLY,
  '__module__' : 'nic_simulator_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:DropReply)
  })
_sym_db.RegisterMessage(DropReply)



_DUALTORACTIVE = _descriptor.ServiceDescriptor(
  name='DualToRActive',
  full_name='DualToRActive',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=492,
  serialized_end=859,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryAdminForwardingPortState',
    full_name='DualToRActive.QueryAdminForwardingPortState',
    index=0,
    containing_service=None,
    input_type=_ADMINREQUEST,
    output_type=_ADMINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetAdminForwardingPortState',
    full_name='DualToRActive.SetAdminForwardingPortState',
    index=1,
    containing_service=None,
    input_type=_ADMINREQUEST,
    output_type=_ADMINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryOperationPortState',
    full_name='DualToRActive.QueryOperationPortState',
    index=2,
    containing_service=None,
    input_type=_OPERATIONREQUEST,
    output_type=_OPERATIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryLinkState',
    full_name='DualToRActive.QueryLinkState',
    index=3,
    containing_service=None,
    input_type=_LINKSTATEREQUEST,
    output_type=_LINKSTATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryServerVersion',
    full_name='DualToRActive.QueryServerVersion',
    index=4,
    containing_service=None,
    input_type=_SERVERVERSIONREQUEST,
    output_type=_SERVERVERSIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetDrop',
    full_name='DualToRActive.SetDrop',
    index=5,
    containing_service=None,
    input_type=_DROPREQUEST,
    output_type=_DROPREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DUALTORACTIVE)

DESCRIPTOR.services_by_name['DualToRActive'] = _DUALTORACTIVE

# @@protoc_insertion_point(module_scope)
