# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nic_simulator_grpc_service_pb2 as nic__simulator__grpc__service__pb2


class DualTorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryAdminPortState = channel.unary_unary(
                '/DualTorService/QueryAdminPortState',
                request_serializer=nic__simulator__grpc__service__pb2.AdminRequest.SerializeToString,
                response_deserializer=nic__simulator__grpc__service__pb2.AdminReply.FromString,
                )
        self.SetAdminPortState = channel.unary_unary(
                '/DualTorService/SetAdminPortState',
                request_serializer=nic__simulator__grpc__service__pb2.AdminRequest.SerializeToString,
                response_deserializer=nic__simulator__grpc__service__pb2.AdminReply.FromString,
                )
        self.QueryOperationPortState = channel.unary_unary(
                '/DualTorService/QueryOperationPortState',
                request_serializer=nic__simulator__grpc__service__pb2.OperationRequest.SerializeToString,
                response_deserializer=nic__simulator__grpc__service__pb2.OperationReply.FromString,
                )


class DualTorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryAdminPortState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAdminPortState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOperationPortState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DualTorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryAdminPortState': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAdminPortState,
                    request_deserializer=nic__simulator__grpc__service__pb2.AdminRequest.FromString,
                    response_serializer=nic__simulator__grpc__service__pb2.AdminReply.SerializeToString,
            ),
            'SetAdminPortState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAdminPortState,
                    request_deserializer=nic__simulator__grpc__service__pb2.AdminRequest.FromString,
                    response_serializer=nic__simulator__grpc__service__pb2.AdminReply.SerializeToString,
            ),
            'QueryOperationPortState': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOperationPortState,
                    request_deserializer=nic__simulator__grpc__service__pb2.OperationRequest.FromString,
                    response_serializer=nic__simulator__grpc__service__pb2.OperationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DualTorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DualTorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryAdminPortState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DualTorService/QueryAdminPortState',
            nic__simulator__grpc__service__pb2.AdminRequest.SerializeToString,
            nic__simulator__grpc__service__pb2.AdminReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAdminPortState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DualTorService/SetAdminPortState',
            nic__simulator__grpc__service__pb2.AdminRequest.SerializeToString,
            nic__simulator__grpc__service__pb2.AdminReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryOperationPortState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DualTorService/QueryOperationPortState',
            nic__simulator__grpc__service__pb2.OperationRequest.SerializeToString,
            nic__simulator__grpc__service__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
