# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platforms/networking/sandcastle/public/proto/options.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='platforms/networking/sandcastle/public/proto/options.proto',
  package='google.sandcastle',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n:platforms/networking/sandcastle/public/proto/options.proto\x12\x11google.sandcastle\x1a google/protobuf/descriptor.proto:D\n\x0c\x65ntity_index\x12\x1f.google.protobuf.MessageOptions\x18\xb3\x86\x06 \x01(\tR\x0b\x65ntityIndex:1\n\x03key\x12\x1d.google.protobuf.FieldOptions\x18\xd8\xc3\x1d \x01(\tR\x03key:\\\n\x1amerge_allow_list_extension\x12\x1d.google.protobuf.FieldOptions\x18\xd9\xc3\x1d \x01(\x08R\x17mergeAllowListExtension')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


ENTITY_INDEX_FIELD_NUMBER = 99123
entity_index = _descriptor.FieldDescriptor(
  name='entity_index', full_name='google.sandcastle.entity_index', index=0,
  number=99123, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, json_name='entityIndex', file=DESCRIPTOR)
KEY_FIELD_NUMBER = 483800
key = _descriptor.FieldDescriptor(
  name='key', full_name='google.sandcastle.key', index=1,
  number=483800, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, json_name='key', file=DESCRIPTOR)
MERGE_ALLOW_LIST_EXTENSION_FIELD_NUMBER = 483801
merge_allow_list_extension = _descriptor.FieldDescriptor(
  name='merge_allow_list_extension', full_name='google.sandcastle.merge_allow_list_extension', index=2,
  number=483801, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, json_name='mergeAllowListExtension', file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['entity_index'] = entity_index
DESCRIPTOR.extensions_by_name['key'] = key
DESCRIPTOR.extensions_by_name['merge_allow_list_extension'] = merge_allow_list_extension
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(entity_index)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(key)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(merge_allow_list_extension)

# @@protoc_insertion_point(module_scope)
