maintainers:
  - StormLiangMS
  - wangxin
  - yxieca

releases:
  includes:
    - '^202\d{3}$'
  excludes:
    - "202305"
    - "202311"
    - "202211"
    - "202205"
    - "202012"

expiry:
  default_days: 90

report:
  warning_days: [30, 15, 7, 3, 1]
