mgmt_bridge: br0
mgmt_gw: 10.250.0.1
mgmt_prefixlen: 24
duts_fp_ports: 
  mgmt141: 
    "0": "use_own_NIC"
    "1": "use_own_NIC"
    "2": "use_own_NIC"
    "3": "use_own_NIC"
    "4": "use_own_NIC"
    "5": "use_own_NIC"
    "6": "use_own_NIC"
    "7": "use_own_NIC"
    "8": "use_own_NIC"
    "9": "use_own_NIC"
    "10": "use_own_NIC"
    "11": "use_own_NIC"
    "12": "use_own_NIC"
    "13": "use_own_NIC"
    "14": "use_own_NIC"
    "15": "use_own_NIC"
    "16": "use_own_NIC"
    "17": "use_own_NIC"
    "18": "use_own_NIC"
    "19": "use_own_NIC"
    "20": "use_own_NIC"
    "21": "use_own_NIC"
    "22": "use_own_NIC"
    "23": "use_own_NIC"
    "24": "use_own_NIC"
    "25": "use_own_NIC"
    "26": "use_own_NIC"
    "27": "use_own_NIC"
    "28": "use_own_NIC"
    "29": "use_own_NIC"
    "30": "use_own_NIC"
    "31": "use_own_NIC"
    "32": "use_own_NIC"
    "33": "use_own_NIC"
    "34": "use_own_NIC"
    "35": "use_own_NIC"
    "36": "use_own_NIC"
    "37": "use_own_NIC"
    "38": "use_own_NIC"
    "39": "use_own_NIC"
    "40": "use_own_NIC"
    "41": "use_own_NIC"
    "42": "use_own_NIC"
    "43": "use_own_NIC"
    "44": "use_own_NIC"
    "45": "use_own_NIC"
    "46": "use_own_NIC"
    "47": "use_own_NIC"
    "48": "use_own_NIC"
    "49": "use_own_NIC"
    "50": "use_own_NIC"
    "51": "use_own_NIC"
    "52": "use_own_NIC"
    "53": "use_own_NIC"
    "54": "use_own_NIC"
    "55": "use_own_NIC"
    "56": "use_own_NIC"
    "57": "use_own_NIC"
    "58": "use_own_NIC"
    "59": "use_own_NIC"
    "60": "use_own_NIC"
    "61": "use_own_NIC"
    "62": "use_own_NIC"
    "63": "use_own_NIC"
duts_midplane_ports: {}
duts_inband_ports: {}
duts_mgmt_port: []
duts_name: "mgmt141"
configuration: {}
