#! /bin/bash

image=$1
if test x$image == x
then
    if [[ $0 =~ "bash" ]]
    then
        echo "Usage: source <scriptname> <image-id> (or)"
        echo "./scriptname <image-id>"
    else
        echo "Usage: $0 <image-id>"
    fi
else
all_duts="xx37-lc0 xx37-lc1 xx37-lc7 xx37-rp"
tbname=" -n t2-xx37 -d "${all_duts// /,}
d_name=" /run_logs/$image/"`date +%F-%H-%M-%S`/
mkdir -p $d_name
mkdir -p /run_logs/allure_repo
chmod -R 777 $d_name

alloptions=" -O -u  -e --skip_sanity -r -m individual -t t2,any -l debug "
include_sanity=" -O -u -r -m individual -t t2,any -l debug -e --alluredir=/run_logs/allure_repo/$image"
e_options=" -e --capture=no -e --skip_sanity -e -rA"
d_options=" -e --disable_loganalyzer"
q_options=" -e --qos_swap_syncd=False"
echo=echo
echo=
# PROD
cmd_prefix="$echo ./run_tests.sh $tbname $include_sanity $e_options $q_options"

# NONPROD
#cmd_prefix="$echo ./run_tests.sh $tbname $alloptions $e_options $q_options"
# DUT Index for 400G Testbed.
# 0 = Vanguard/Long links
# 1 = Lancer/short links/100G
# 2 = Gauntlet/Short links
###B
###Bsudo apt install sshpass
###Bpass="cisco123"
###Bssh_pass="sshpass -p $pass "
###Bfor dut in $all_duts:
###B    $ssh_pass scp /home/sonic/IMAGES/$image/docker-syncd-cisco-rpc.gz cisco@$dut:
###B    $ssh_pass scp /home/sonic/SCRIPTS/rpc.sh cisco@$dut:
###B    $ssh_pass scp /home/sonic/SCRIPTS/rpc-revert.sh cisco@$dut:
###B    $ssh_pass ssh cisco@$dut source /home/cisco/rpc.sh  &
###B

#logdir=$d_name/pretest
#mkdir -p $logdir
##$echo ./run_tests.sh $tbname $alloptions -p $logdir $e_options -c 'test_pretest.py'
#$echo ./run_tests.sh $tbname $include_sanity -p $logdir $e_options -c 'bgp/test_bgp_fact.py'


# Col: K
# Prod run
logdir=$d_name/K-400g-LL-sasic-gb
mkdir -p $logdir
# 400G L - 400G L
$cmd_prefix -p $logdir -e '--primary_dut_index=0 --secondary_dut_index=0 --test_port_selection_criteria=single_asic' -c 'qos/test_qos_sai.py'

# Col: L
logdir=$d_name/L-400g-LL-masic-gb
mkdir -p  $logdir
# 100G S - L mDut
$cmd_prefix -p $logdir -e '--primary_dut_index=0 --secondary_dut_index=0 --test_port_selection_criteria=single_dut_multi_asic' -c 'qos/test_qos_sai.py'

# Col: M
logdir=$d_name/M-400L-100S-gb-mdut
mkdir -p $logdir
# 100G L - L sAsic
$cmd_prefix -p $logdir -e '--primary_dut_index=0 --secondary_dut_index=1 --test_port_selection_criteria=multi_dut' -c 'qos/test_qos_sai.py'

# Col N
logdir=$d_name/N-100g-S-400G-L-gb-mdut
mkdir -p  $logdir
# 100G S - S sAsic
$cmd_prefix -p $logdir -e '--primary_dut_index=1 --secondary_dut_index=0 --test_port_selection_criteria=multi_dut' -c 'qos/test_qos_sai.py'

# Col:O
logdir=$d_name/O-100g-SS-gb-sasic
mkdir -p  $logdir
# 100G S - S sAsic
$cmd_prefix -p $logdir -e '--primary_dut_index=1 --secondary_dut_index=1 --test_port_selection_criteria=single_asic' -c 'qos/test_qos_sai.py'

# Col: P
logdir=$d_name/P-100g-SS-gb-masic
mkdir -p  $logdir
# 100G S - S mDut
$cmd_prefix -p $logdir -e '--primary_dut_index=1 --secondary_dut_index=1 --test_port_selection_criteria=single_dut_multi_asic' -c 'qos/test_qos_sai.py'

# Col: AD
logdir=$d_name/AD-100g-SS-pac-sasic
mkdir -p  $logdir
# ss:1asic-pac
$cmd_prefix -p $logdir -e '--primary_dut_index=2 --secondary_dut_index=2 --test_port_selection_criteria=single_asic' -c 'qos/test_qos_sai.py'

# Col: AE
logdir=$d_name/AE-100g-SS-pac-masic
mkdir -p  $logdir
# ss: 1dut-masic-pac
$cmd_prefix -p $logdir -e '--primary_dut_index=2 --secondary_dut_index=2 --test_port_selection_criteria=single_dut_multi_asic' -c 'qos/test_qos_sai.py'

# Col: AG
logdir=$d_name/AG-400L-100S-mdut-gb-pac
mkdir -p  $logdir
#400G/l-100G/S, V->G
$cmd_prefix -p $logdir -e '--primary_dut_index=0 --secondary_dut_index=2 --test_port_selection_criteria=multi_dut' -c 'qos/test_qos_sai.py'

# Col: AH
logdir=$d_name/AH-100S-400L-mdut-pac-gb
mkdir -p  $logdir
# 100G/S-400G/L G->V
$cmd_prefix -p $logdir -e '--primary_dut_index=2 --secondary_dut_index=0 --test_port_selection_criteria=multi_dut' -c 'qos/test_qos_sai.py'

# Col: AI
logdir=$d_name/AI-100-SS-pac-gb
# AI-100g-SS-pac-gb
mkdir -p  $logdir
$cmd_prefix -p $logdir -e '--primary_dut_index=2 --secondary_dut_index=1 --test_port_selection_criteria=multi_dut' -c 'qos/test_qos_sai.py'

# Col: AJ
logdir=$d_name/AJ-100g-SS-gb-pac
mkdir -p  $logdir
# 100G S - S mDut
$cmd_prefix -p $logdir -e '--primary_dut_index=1 --secondary_dut_index=2 --test_port_selection_criteria=multi_dut' -c 'qos/test_qos_sai.py'


###cant run#### Col: U
###cant run###logdir=$d_name/U-100g-SL-gb
###cant run###mkdir -p  $logdir
###cant run#### 100G/S - 100G/L (M-Dut) Q200
###cant run###$cmd_prefix -p $logdir -e '--primary_dut_index=1 --secondary_dut_index=0 --test_port_selection_criteria=multi_dut' -c 'qos/test_qos_sai.py'

##################
###### Change lancer to long-links - If supported
##################
##### Col: AK
####logdir=$d_name/AK-100-SL-pac-gb-mdut
##### AK-100g-SL-pac-gb
####mkdir -p  $logdir
####$cmd_prefix -p $logdir -e '--primary_dut_index=2 --secondary_dut_index=1 --test_port_selection_criteria=multi_dut' -c 'qos/test_qos_sai.py'
####
##### Col: AL
####logdir=$d_name/AL-100g-LS-gb-pac-mdut
####mkdir -p  $logdir
##### 100G L - S mDut
####$cmd_prefix -p $logdir -e '--primary_dut_index=1 --secondary_dut_index=2 --test_port_selection_criteria=multi_dut' -c 'qos/test_qos_sai.py'
####

# echo "The log dir is : $d_name"

# #### Run in the UCS. cd to the log dir.
# #### cd to $d_name
# # sonic_mgmt_path=/home/sonic/qos-sai-workspace/sonic-mgmt-202205/
# # d_name=`pwd`
# # for f in `find $d_name -name "*.xml"`; do python3 $sonic_mgmt_path/test_reporting/junit_xml_parser_csv.py --csv ${f/xml/csv} $f ; done
# # for f in `find $d_name -name "*.csv"`; do echo $f > ${f}-s; done
# # for f in `find $d_name -name "*.csv"`; do cat $f | awk -F, '{print $3}' >> ${f}-s; done
# # find $d_name -name "*-s" | xargs paste > ${d_name}.csv

fi
