simulation:
  no_image_copy: true
  pyvxr_flags:
    port_file_timeout: 1200
  sim_dir: /nobackup/sim
  sim_host: localhost
  skip_auto_bringup: false

devices:
  trex1: &host
    data_ports:
      - eth1
      - eth2
    data_port_attributes:
      transport: e1000
    linux_username: vxr
    linux_password: cisco123
    linux_prompt: vxr@ubuntu22:~\$
    disks:
      - hda_ref:
          file: /nobackup/images/ubuntu22.qcow2
          type: reference
    memory: 3GB
    platform: linux
    vcpu: 2
    xr_port_redir:
      - 22

  trex2:
    <<: *host
  trex3:
    <<: *host
  trex4:
    <<: *host
  trex5:
    <<: *host
  trex6:
    <<: *host
  trex7:
    <<: *host
  trex8:
    <<: *host
  trex9:
    <<: *host
  trex10:
    <<: *host
  trex11:
    <<: *host
  trex12:
    <<: *host
  trex13:
    <<: *host
  trex14:
    <<: *host
  trex15:
    <<: *host
  trex16:
    <<: *host
  trex17:
    <<: *host
  trex18:
    <<: *host
  trex19:
    <<: *host
  trex20:
    <<: *host
  trex21:
    <<: *host

  nexus1:
    platform: nxos
    image: /auto/vxr/images/nxos/nxos64-cs.10.4.4.qcow2
    xr_hostname: IPN
    xr_username: cisco
    xr_password: cisco123
    xr_port_redir:
      - 22
    xr_config: |
      interface Ethernet1/1
       no switchport
       ip address 43.216.11.11 255.255.255.0
       no shutdown
      interface Ethernet1/2
       no switchport
       ip address 43.216.12.11 255.255.255.0
       no shutdown
      interface Ethernet1/3
       no switchport
       ip address 43.216.21.11 255.255.255.0
       no shutdown
      interface Ethernet1/4
       no switchport
       ip address 43.216.22.11 255.255.255.0
       no shutdown
      interface Ethernet1/5
       no switchport
       ip address 43.216.31.11 255.255.255.0
       no shutdown
      interface Ethernet1/6
       no switchport
       ip address 43.216.32.11 255.255.255.0
       no shutdown
      feature bgp
      router bgp 7000
       neighbor 43.216.11.10 remote-as 6001
       address-family ipv4 unicast
       neighbor 43.216.12.10 remote-as 6001
       address-family ipv4 unicast
       neighbor 43.216.21.10 remote-as 6002
       address-family ipv4 unicast
       neighbor 43.216.22.10 remote-as 6002
       address-family ipv4 unicast
       neighbor 43.216.31.10 remote-as 6003
       address-family ipv4 unicast
       neighbor 43.216.32.10 remote-as 6003
       address-family ipv4 unicast

  L0: &switch
    image: /auto/vxr/images/onie-sonic/onie-recovery-x86_64-cisco_8000-r0.iso
    linecard_types:
      - 8101-32FH
    port_breakout:
      lc0:
        0..31: 1x400
    vxr_sim_config:
      shelf:
        ConfigCardPidOverride: HF6100-32D
    linux_password: cisco123
    linux_username: cisco
    onie-install: /nobackup/images/sonic-cisco-8000.bin
    os_type: sonic
    memory: 12GB
    vcpu: 8
    platform: spitfire_f
    data_ports:
      - Ethernet1_1
      - Ethernet1_2
      - Ethernet1_3
      - Ethernet1_4
      - Ethernet1_5
      - Ethernet1_6
      - Ethernet1_7
      - Ethernet1_8
      - Ethernet1_9
      - Ethernet1_10
      - Ethernet1_11
      - Ethernet1_12
      - Ethernet1_13
      - Ethernet1_14
      - Ethernet1_15
      - Ethernet1_16
      - Ethernet1_17
      - Ethernet1_18
      - Ethernet1_19
      - Ethernet1_20
      - Ethernet1_21
    xr_port_redir:
      - 22
    pre_cli: |
      sleep 60
      curl --retry 10 --retry-delay 10 --retry-all-errors -O http://ttg-fs1.cisco.com/ttg-images/misc/pyvxr_gen_sw_sudi_cert.tar.gz
      curl -O http://ttg-fs1.cisco.com/ttg-images/tortuga-agents_0.1-1_amd64.deb
      tar -xzf pyvxr_gen_sw_sudi_cert.tar.gz
      sudo ./pyvxr_gen_sw_sudi_cert.sh
    cli_commands: |
      sudo config hostname tortuga-dc1-leaf0
      sudo config save -y
      sudo dpkg -i /home/cisco/tortuga-agents_0.1-1_amd64.deb
      sudo systemctl stop drake
      sudo curl http://ttg-fs1.cisco.com/ttg-images/drake-config-pradeep1.yml -o /opt/cisco/etc/tortuga/drake-config.yml
      sudo systemctl daemon-reload
      sudo systemctl restart drake
      sudo systemctl restart lira
      sudo systemctl restart azimuth

  L1:
    <<: *switch
    cli_commands: |
      sudo config hostname tortuga-dc1-leaf1
      sudo config save -y
      sudo dpkg -i /home/cisco/tortuga-agents_0.1-1_amd64.deb

  L2:
    <<: *switch
    cli_commands: |
      sudo config hostname tortuga-dc2-leaf0
      sudo config save -y
      sudo dpkg -i /home/cisco/tortuga-agents_0.1-1_amd64.deb
      sudo systemctl stop drake
      sudo curl http://ttg-fs1.cisco.com/ttg-images/drake-config-pradeep1.yml -o /opt/cisco/etc/tortuga/drake-config.yml
      sudo systemctl daemon-reload
      sudo systemctl restart drake
      sudo systemctl restart lira
      sudo systemctl restart azimuth

  L3:
    <<: *switch
    cli_commands: |
      sudo config hostname tortuga-dc2-leaf1
      sudo config save -y
      sudo dpkg -i /home/cisco/tortuga-agents_0.1-1_amd64.deb

  L4:
    <<: *switch
    cli_commands: |
      sudo config hostname tortuga-dc3-leaf0
      sudo config save -y
      sudo dpkg -i /home/cisco/tortuga-agents_0.1-1_amd64.deb
      sudo systemctl stop drake
      sudo curl http://ttg-fs1.cisco.com/ttg-images/drake-config-pradeep1.yml -o /opt/cisco/etc/tortuga/drake-config.yml
      sudo systemctl daemon-reload
      sudo systemctl restart drake
      sudo systemctl restart lira
      sudo systemctl restart azimuth

  L5:
    <<: *switch
    cli_commands: |
      sudo config hostname tortuga-dc3-leaf1
      sudo config save -y
      sudo dpkg -i /home/cisco/tortuga-agents_0.1-1_amd64.deb

  S0:
    <<: *switch
    cli_commands: |
      sudo config hostname tortuga-dc1-spine0
      sudo config save -y
      sudo dpkg -i /home/cisco/tortuga-agents_0.1-1_amd64.deb
      sudo systemctl stop drake
      sudo curl http://ttg-fs1.cisco.com/ttg-images/drake-config-pradeep3.yml -o /opt/cisco/etc/tortuga/drake-config.yml
      sudo systemctl daemon-reload
      sudo systemctl restart drake
      sudo systemctl restart lira
      sudo systemctl restart azimuth

  S1:
    <<: *switch
    cli_commands: |
      sudo config hostname tortuga-dc2-spine0
      sudo config save -y
      sudo dpkg -i /home/cisco/tortuga-agents_0.1-1_amd64.deb
      sudo systemctl stop drake
      sudo curl http://ttg-fs1.cisco.com/ttg-images/drake-config-pradeep3.yml -o /opt/cisco/etc/tortuga/drake-config.yml
      sudo systemctl daemon-reload
      sudo systemctl restart drake
      sudo systemctl restart lira
      sudo systemctl restart azimuth

  S2:
    <<: *switch
    cli_commands: |
      sudo config hostname tortuga-dc3-spine0
      sudo config save -y
      sudo dpkg -i /home/cisco/tortuga-agents_0.1-1_amd64.deb
      sudo systemctl stop drake
      sudo curl http://ttg-fs1.cisco.com/ttg-images/drake-config-pradeep3.yml -o /opt/cisco/etc/tortuga/drake-config.yml
      sudo systemctl daemon-reload
      sudo systemctl restart drake
      sudo systemctl restart lira
      sudo systemctl restart azimuth

connections:
  hubs:
    # Fabric: DC1
    L0_trex1_1:
      - L0.Ethernet1_9
      - trex1.eth1
    L0_trex5_2:
      - L0.Ethernet1_13
      - trex5.eth2
    L0_trex2_1:
      - L0.Ethernet1_10
      - trex2.eth1
    L0_trex2_2:
      - L0.Ethernet1_15
      - trex2.eth2
    L0_trex3_1:
      - L0.Ethernet1_11
      - trex3.eth1
    L0_trex4_1:
      - L0.Ethernet1_12
      - trex4.eth1
    L0_trex4_2:
      - L0.Ethernet1_14
      - trex4.eth2
    L0_LOOP:
      - L0.Ethernet1_16
      - L0.Ethernet1_17
    L1_trex5_1:
      - L1.Ethernet1_9
      - trex5.eth1
    L1_trex1_2:
      - L1.Ethernet1_13
      - trex1.eth2
    L1_trex6_1:
      - L1.Ethernet1_10
      - trex6.eth1
    L1_trex6_2:
      - L1.Ethernet1_15
      - trex6.eth2
    L1_trex7_1:
      - L1.Ethernet1_11
      - trex7.eth1
    L1_trex7_2:
      - L1.Ethernet1_14
      - trex7.eth2
    S0_L0_conn1:
      - S0.Ethernet1_1
      - L0.Ethernet1_1
    S0_L1_conn1:
      - S0.Ethernet1_2
      - L1.Ethernet1_1

    # Fabric: DC2
    L2_trex8_1:
      - L2.Ethernet1_9
      - trex8.eth1
    L2_trex12_2:
      - L2.Ethernet1_13
      - trex12.eth2
    L2_trex9_1:
      - L2.Ethernet1_10
      - trex9.eth1
    L2_trex9_2:
      - L2.Ethernet1_15
      - trex9.eth2
    L2_trex10_1:
      - L2.Ethernet1_11
      - trex10.eth1
    L2_trex11_1:
      - L2.Ethernet1_12
      - trex11.eth1
    L2_trex11_2:
      - L2.Ethernet1_14
      - trex11.eth2
    L2_LOOP:
      - L2.Ethernet1_16
      - L2.Ethernet1_17
    L3_trex12_1:
      - L3.Ethernet1_9
      - trex12.eth1
    L3_trex8_2:
      - L3.Ethernet1_13
      - trex8.eth2
    L3_trex13_1:
      - L3.Ethernet1_10
      - trex13.eth1
    L3_trex13_2:
      - L3.Ethernet1_15
      - trex13.eth2
    L3_trex14_1:
      - L3.Ethernet1_11
      - trex14.eth1
    L3_trex14_2:
      - L3.Ethernet1_14
      - trex14.eth2
    S1_L2_conn1:
      - S1.Ethernet1_1
      - L2.Ethernet1_1
    S1_L3_conn1:
      - S1.Ethernet1_2
      - L3.Ethernet1_1

    # Fabric: DC3
    L4_trex15_1:
      - L4.Ethernet1_9
      - trex15.eth1
    L4_trex19_2:
      - L4.Ethernet1_13
      - trex19.eth2
    L4_trex16_1:
      - L4.Ethernet1_10
      - trex16.eth1
    L4_trex16_2:
      - L4.Ethernet1_15
      - trex16.eth2
    L4_trex17_1:
      - L4.Ethernet1_11
      - trex17.eth1
    L4_trex18_1:
      - L4.Ethernet1_12
      - trex18.eth1
    L4_trex18_2:
      - L4.Ethernet1_14
      - trex18.eth2
    L4_LOOP:
      - L4.Ethernet1_16
      - L4.Ethernet1_17
    L5_trex19_1:
      - L5.Ethernet1_9
      - trex19.eth1
    L5_trex15_2:
      - L5.Ethernet1_13
      - trex15.eth2
    L5_trex20_1:
      - L5.Ethernet1_10
      - trex20.eth1
    L5_trex20_2:
      - L5.Ethernet1_15
      - trex20.eth2
    L5_trex21_1:
      - L5.Ethernet1_11
      - trex21.eth1
    L5_trex21_2:
      - L5.Ethernet1_14
      - trex21.eth2
    S2_L4_conn1:
      - S2.Ethernet1_1
      - L4.Ethernet1_1
    S2_L5_conn1:
      - S2.Ethernet1_2
      - L5.Ethernet1_1

    # DCI connections.
    S0_nexus1_conn1:
      - S0.Ethernet1_9
      - nexus1.Ethernet1/1
    S0_nexus1_conn2:
      - S0.Ethernet1_10
      - nexus1.Ethernet1/2
    S1_nexus1_conn1:
      - S1.Ethernet1_9
      - nexus1.Ethernet1/3
    S1_nexus1_conn2:
      - S1.Ethernet1_10
      - nexus1.Ethernet1/4
    S2_nexus1_conn1:
      - S2.Ethernet1_9
      - nexus1.Ethernet1/5
    S2_nexus1_conn2:
      - S2.Ethernet1_10
      - nexus1.Ethernet1/6
