# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diagnostic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='diagnostic.proto',
  package='google.sandcastle.stack.diagnostics',
  syntax='proto2',
  serialized_options=_b('\200\001\000\220\001\001'),
  serialized_pb=_b('\n\x10\x64iagnostic.proto\x12#google.sandcastle.stack.diagnostics\"+\n\nBurninTest\"\x1d\n\x0e\x42urninTestType\x12\x0b\n\x07UNKNOWN\x10\x00\"\x0f\n\rBurninRequest\"\xce\x03\n\x0c\x42urninResult\x12[\n\ttest_type\x18\x01 \x01(\x0e\x32>.google.sandcastle.stack.diagnostics.BurninTest.BurninTestTypeR\x08testType\x12\x1b\n\ttest_name\x18\x02 \x01(\tR\x08testName\x12]\n\x0btest_status\x18\x03 \x01(\x0e\x32<.google.sandcastle.stack.diagnostics.BurninResult.TestStatusR\ntestStatus\x12q\n\x12\x63omponent_failures\x18\x04 \x03(\x0b\x32\x42.google.sandcastle.stack.diagnostics.BurninResult.ComponentFailureR\x11\x63omponentFailures\x1a=\n\x10\x43omponentFailure\x12)\n\x10\x66\x61ilure_location\x18\x01 \x01(\tR\x0f\x66\x61ilureLocation\"3\n\nTestStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\"\x82\x01\n\x0e\x42urninResponse\x12K\n\x07results\x18\x01 \x03(\x0b\x32\x31.google.sandcastle.stack.diagnostics.BurninResultR\x07results\x12#\n\rsystem_uptime\x18\x02 \x01(\x04R\x0csystemUptimeB\x06\x80\x01\x00\x90\x01\x01')
)



_BURNINTEST_BURNINTESTTYPE = _descriptor.EnumDescriptor(
  name='BurninTestType',
  full_name='google.sandcastle.stack.diagnostics.BurninTest.BurninTestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=71,
  serialized_end=100,
)
_sym_db.RegisterEnumDescriptor(_BURNINTEST_BURNINTESTTYPE)

_BURNINRESULT_TESTSTATUS = _descriptor.EnumDescriptor(
  name='TestStatus',
  full_name='google.sandcastle.stack.diagnostics.BurninResult.TestStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=531,
  serialized_end=582,
)
_sym_db.RegisterEnumDescriptor(_BURNINRESULT_TESTSTATUS)


_BURNINTEST = _descriptor.Descriptor(
  name='BurninTest',
  full_name='google.sandcastle.stack.diagnostics.BurninTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BURNINTEST_BURNINTESTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=100,
)


_BURNINREQUEST = _descriptor.Descriptor(
  name='BurninRequest',
  full_name='google.sandcastle.stack.diagnostics.BurninRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=117,
)


_BURNINRESULT_COMPONENTFAILURE = _descriptor.Descriptor(
  name='ComponentFailure',
  full_name='google.sandcastle.stack.diagnostics.BurninResult.ComponentFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failure_location', full_name='google.sandcastle.stack.diagnostics.BurninResult.ComponentFailure.failure_location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='failureLocation', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=529,
)

_BURNINRESULT = _descriptor.Descriptor(
  name='BurninResult',
  full_name='google.sandcastle.stack.diagnostics.BurninResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_type', full_name='google.sandcastle.stack.diagnostics.BurninResult.test_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='testType', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_name', full_name='google.sandcastle.stack.diagnostics.BurninResult.test_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='testName', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_status', full_name='google.sandcastle.stack.diagnostics.BurninResult.test_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='testStatus', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='component_failures', full_name='google.sandcastle.stack.diagnostics.BurninResult.component_failures', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='componentFailures', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BURNINRESULT_COMPONENTFAILURE, ],
  enum_types=[
    _BURNINRESULT_TESTSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=582,
)


_BURNINRESPONSE = _descriptor.Descriptor(
  name='BurninResponse',
  full_name='google.sandcastle.stack.diagnostics.BurninResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='google.sandcastle.stack.diagnostics.BurninResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='results', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='system_uptime', full_name='google.sandcastle.stack.diagnostics.BurninResponse.system_uptime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='systemUptime', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=715,
)

_BURNINTEST_BURNINTESTTYPE.containing_type = _BURNINTEST
_BURNINRESULT_COMPONENTFAILURE.containing_type = _BURNINRESULT
_BURNINRESULT.fields_by_name['test_type'].enum_type = _BURNINTEST_BURNINTESTTYPE
_BURNINRESULT.fields_by_name['test_status'].enum_type = _BURNINRESULT_TESTSTATUS
_BURNINRESULT.fields_by_name['component_failures'].message_type = _BURNINRESULT_COMPONENTFAILURE
_BURNINRESULT_TESTSTATUS.containing_type = _BURNINRESULT
_BURNINRESPONSE.fields_by_name['results'].message_type = _BURNINRESULT
DESCRIPTOR.message_types_by_name['BurninTest'] = _BURNINTEST
DESCRIPTOR.message_types_by_name['BurninRequest'] = _BURNINREQUEST
DESCRIPTOR.message_types_by_name['BurninResult'] = _BURNINRESULT
DESCRIPTOR.message_types_by_name['BurninResponse'] = _BURNINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BurninTest = _reflection.GeneratedProtocolMessageType('BurninTest', (_message.Message,), dict(
  DESCRIPTOR = _BURNINTEST,
  __module__ = 'diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:google.sandcastle.stack.diagnostics.BurninTest)
  ))
_sym_db.RegisterMessage(BurninTest)

BurninRequest = _reflection.GeneratedProtocolMessageType('BurninRequest', (_message.Message,), dict(
  DESCRIPTOR = _BURNINREQUEST,
  __module__ = 'diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:google.sandcastle.stack.diagnostics.BurninRequest)
  ))
_sym_db.RegisterMessage(BurninRequest)

BurninResult = _reflection.GeneratedProtocolMessageType('BurninResult', (_message.Message,), dict(

  ComponentFailure = _reflection.GeneratedProtocolMessageType('ComponentFailure', (_message.Message,), dict(
    DESCRIPTOR = _BURNINRESULT_COMPONENTFAILURE,
    __module__ = 'diagnostic_pb2'
    # @@protoc_insertion_point(class_scope:google.sandcastle.stack.diagnostics.BurninResult.ComponentFailure)
    ))
  ,
  DESCRIPTOR = _BURNINRESULT,
  __module__ = 'diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:google.sandcastle.stack.diagnostics.BurninResult)
  ))
_sym_db.RegisterMessage(BurninResult)
_sym_db.RegisterMessage(BurninResult.ComponentFailure)

BurninResponse = _reflection.GeneratedProtocolMessageType('BurninResponse', (_message.Message,), dict(
  DESCRIPTOR = _BURNINRESPONSE,
  __module__ = 'diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:google.sandcastle.stack.diagnostics.BurninResponse)
  ))
_sym_db.RegisterMessage(BurninResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
