# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loas2_sandcastle_crl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loas2_sandcastle_crl.proto',
  package='google.sandcastle',
  syntax='proto2',
  serialized_options=_b('\200\001\000\220\001\001'),
  serialized_pb=_b('\n\x1aloas2_sandcastle_crl.proto\x12\x11google.sandcastle\"t\n\x12Loas2SandcastleCrl\x12\x18\n\x07version\x18\x01 \x01(\tR\x07version\x12\x17\n\x07\x63rl_ids\x18\x02 \x03(\x04R\x06\x63rlIds\x12+\n\x11release_timestamp\x18\x03 \x01(\x03R\x10releaseTimestampB\x06\x80\x01\x00\x90\x01\x01')
)




_LOAS2SANDCASTLECRL = _descriptor.Descriptor(
  name='Loas2SandcastleCrl',
  full_name='google.sandcastle.Loas2SandcastleCrl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='google.sandcastle.Loas2SandcastleCrl.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='version', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crl_ids', full_name='google.sandcastle.Loas2SandcastleCrl.crl_ids', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='crlIds', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='release_timestamp', full_name='google.sandcastle.Loas2SandcastleCrl.release_timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='releaseTimestamp', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['Loas2SandcastleCrl'] = _LOAS2SANDCASTLECRL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Loas2SandcastleCrl = _reflection.GeneratedProtocolMessageType('Loas2SandcastleCrl', (_message.Message,), dict(
  DESCRIPTOR = _LOAS2SANDCASTLECRL,
  __module__ = 'loas2_sandcastle_crl_pb2'
  # @@protoc_insertion_point(class_scope:google.sandcastle.Loas2SandcastleCrl)
  ))
_sym_db.RegisterMessage(Loas2SandcastleCrl)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
