# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gnmitest/gnmitest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.openconfig.gnmitest.proto.suite import suite_pb2 as github_dot_com_dot_openconfig_dot_gnmitest_dot_proto_dot_suite_dot_suite__pb2
from github.com.openconfig.gnmitest.proto.report import report_pb2 as github_dot_com_dot_openconfig_dot_gnmitest_dot_proto_dot_report_dot_report__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gnmitest/gnmitest.proto',
  package='gnmitest',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1dproto/gnmitest/gnmitest.proto\x12\x08gnmitest\x1a\x36github.com/openconfig/gnmitest/proto/suite/suite.proto\x1a\x38github.com/openconfig/gnmitest/proto/report/report.proto2/\n\x08GNMITest\x12#\n\x03Run\x12\x0c.suite.Suite\x1a\x0e.report.Reportb\x06proto3'
  ,
  dependencies=[github_dot_com_dot_openconfig_dot_gnmitest_dot_proto_dot_suite_dot_suite__pb2.DESCRIPTOR,github_dot_com_dot_openconfig_dot_gnmitest_dot_proto_dot_report_dot_report__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_GNMITEST = _descriptor.ServiceDescriptor(
  name='GNMITest',
  full_name='gnmitest.GNMITest',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=157,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='gnmitest.GNMITest.Run',
    index=0,
    containing_service=None,
    input_type=github_dot_com_dot_openconfig_dot_gnmitest_dot_proto_dot_suite_dot_suite__pb2._SUITE,
    output_type=github_dot_com_dot_openconfig_dot_gnmitest_dot_proto_dot_report_dot_report__pb2._REPORT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GNMITEST)

DESCRIPTOR.services_by_name['GNMITest'] = _GNMITEST

# @@protoc_insertion_point(module_scope)
