device_groups:
  fanout:
    host:
    - nexus-5
  lab:
    children:
    - sonic
    - fanout
    vars:
      mgmt_subnet_mask_length: '24'
  ptf:
    host:
    - docker-ptf
  sonic:
    children:
    - sonic_cisco
  sonic_cisco:
    host:
    - mathilda-01
    vars:
      hwsku: Cisco-8102-C64
      iface_speed: '100000'
devices:
  mathilda-01:
    alias: null
    ansible:
      ansible_host: 192.168.122.47
      ansible_ssh_pass: cisco123
      ansible_ssh_user: cisco
    credentials:
      enable_password: cisco123
      password: cisco123
      username: cisco
    device_type: DevSonic
    hwsku: Cisco-8102-C64
    os: sonic
  nexus-5:
    alias: null
    ansible:
      ansible_host: 10.251.0.13/23
      ansible_ssh_pass: password
      ansible_ssh_user: user
      fanout_sonic_password: password
      fanout_sonic_user: admin
    credentials:
      password: null
      username: null
    device_type: FanoutLeaf
    hwsku: Arista-7260QX-64
  str-acs-serv-01:
    alias: null
    ansible:
      ansible_become_pass: cisco123
      ansible_host: 172.17.0.1/23
      ansible_ssh_pass: cisco123
      ansible_ssh_user: vxr
      sonicadmin_initial_password: cisco123
      sonicadmin_password: cisco123
      sonicadmin_user: admin
    credentials:
      password: cisco123
      username: vxr
    device_type: server
    hwsku: TestServ
    mgmt_subnet_mask_length: '24'
  docker-ptf:
    device_type: blank
    hwsku:
    ansible:
        ansible_ssh_user: root
        ansible_host: 1.74.23.21/16
        ansible_hostv6: fc0b::1/64
        ansible_ssh_pass: root
    credentials:
        password: root
        username: root
docker_registry:
  docker_registry_host: sonicdev-microsoft.azurecr.io:443
  docker_registry_password: sonic
  docker_registry_username: 1dafc8d7-d19c-4f58-8653-e8d904f30dab
host_vars:
  str-acs-serv-01:
    external_port: eth0
    mgmt_bridge: br1
    mgmt_gw: 172.17.0.1
    mgmt_prefixlen: 24
testbed:
  docker-ptf:
    comment: Test ptf mathilda
    dut: mathilda-01
    group-name: sonic_cisco
    ptf_image_name: docker-ptf-mathilda
    ptf_ip: 192.168.122.66/24
    ptf_ipv6: fc0b::1/64
    ptf: docker-ptf
    server: server_1
    topo: t0-64
    vm_base: VM0100
    ansible:
      ansible_ssh_user: root
      ansible_host: 192.168.122.66/24
      ansible_hostv6: fc0b::1/64
      ansible_ssh_pass: root
    credentials:
      password: root
      username: root

testbed_config:
  alias: mathildatopologyTestbed
  name: testbed-mathilda-t0
  type: Physical
topology:
  mathilda-01:
    interfaces:
      Ethernet0:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/0
        VlanID: 2000
        VlanMode: Access
      Ethernet4:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/1
        VlanID: 2001
        VlanMode: Access
      Ethernet8:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/2
        VlanID: 2002
        VlanMode: Access
      Ethernet12:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/3
        VlanID: 2003
        VlanMode: Access
      Ethernet16:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/4
        VlanID: 2004
        VlanMode: Access
      Ethernet20:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/5
        VlanID: 2005
        VlanMode: Access
      Ethernet24:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/6
        VlanID: 2006
        VlanMode: Access
      Ethernet28:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/7
        VlanID: 2007
        VlanMode: Access
      Ethernet32:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/8
        VlanID: 2008
        VlanMode: Access
      Ethernet36:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/9
        VlanID: 2009
        VlanMode: Access
      Ethernet40:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/10
        VlanID: 2010
        VlanMode: Access
      Ethernet44:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/11
        VlanID: 2011
        VlanMode: Access
      Ethernet48:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/12
        VlanID: 2012
        VlanMode: Access
      Ethernet52:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/13
        VlanID: 2013
        VlanMode: Access
      Ethernet56:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/14
        VlanID: 2014
        VlanMode: Access
      Ethernet60:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/15
        VlanID: 2015
        VlanMode: Access
      Ethernet64:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/16
        VlanID: 2016
        VlanMode: Access
      Ethernet68:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/17
        VlanID: 2017
        VlanMode: Access
      Ethernet72:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/18
        VlanID: 2018
        VlanMode: Access
      Ethernet76:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/19
        VlanID: 2019
        VlanMode: Access
      Ethernet80:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/20
        VlanID: 2020
        VlanMode: Access
      Ethernet84:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/21
        VlanID: 2021
        VlanMode: Access
      Ethernet88:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/22
        VlanID: 2022
        VlanMode: Access
      Ethernet92:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/23
        VlanID: 2023
        VlanMode: Access
      Ethernet96:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/24
        VlanID: 2024
        VlanMode: Access
      Ethernet100:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/25
        VlanID: 2025
        VlanMode: Access
      Ethernet104:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/26
        VlanID: 2026
        VlanMode: Access
      Ethernet108:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/27
        VlanID: 2027
        VlanMode: Access
      Ethernet112:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/28
        VlanID: 2028
        VlanMode: Access
      Ethernet116:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/29
        VlanID: 2029
        VlanMode: Access
      Ethernet120:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/30
        VlanID: 2030
        VlanMode: Access
      Ethernet124:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/31
        VlanID: 2031
        VlanMode: Access
      Ethernet128:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/32
        VlanID: 2032
        VlanMode: Access
      Ethernet132:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/33
        VlanID: 2033
        VlanMode: Access
      Ethernet136:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/34
        VlanID: 2034
        VlanMode: Access
      Ethernet140:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/35
        VlanID: 2035
        VlanMode: Access
      Ethernet144:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/36
        VlanID: 2036
        VlanMode: Access
      Ethernet148:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/37
        VlanID: 2037
        VlanMode: Access
      Ethernet152:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/38
        VlanID: 2038
        VlanMode: Access
      Ethernet156:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/39
        VlanID: 2039
        VlanMode: Access
      Ethernet160:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/40
        VlanID: 2040
        VlanMode: Access
      Ethernet164:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/41
        VlanID: 2041
        VlanMode: Access
      Ethernet168:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/42
        VlanID: 2042
        VlanMode: Access
      Ethernet172:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/43
        VlanID: 2043
        VlanMode: Access
      Ethernet176:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/44
        VlanID: 2044
        VlanMode: Access
      Ethernet180:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/45
        VlanID: 2045
        VlanMode: Access
      Ethernet184:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/46
        VlanID: 2046
        VlanMode: Access
      Ethernet188:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/47
        VlanID: 2047
        VlanMode: Access
      Ethernet192:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/48
        VlanID: 2048
        VlanMode: Access
      Ethernet196:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/49
        VlanID: 2049
        VlanMode: Access
      Ethernet200:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/50
        VlanID: 2050
        VlanMode: Access
      Ethernet204:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/51
        VlanID: 2051
        VlanMode: Access
      Ethernet208:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/52
        VlanID: 2052
        VlanMode: Access
      Ethernet212:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/53
        VlanID: 2053
        VlanMode: Access
      Ethernet216:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/54
        VlanID: 2054
        VlanMode: Access
      Ethernet220:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/55
        VlanID: 2055
        VlanMode: Access
      Ethernet224:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/56
        VlanID: 2056
        VlanMode: Access
      Ethernet228:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/57
        VlanID: 2057
        VlanMode: Access
      Ethernet232:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/58
        VlanID: 2058
        VlanMode: Access
      Ethernet236:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/59
        VlanID: 2059
        VlanMode: Access
      Ethernet240:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/60
        VlanID: 2060
        VlanMode: Access
      Ethernet244:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/61
        VlanID: 2061
        VlanMode: Access
      Ethernet248:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/62
        VlanID: 2062
        VlanMode: Access
      Ethernet252:
        Bandwidth: 100000
        EndDevice: nexus-5
        EndPort: Ethernet1/63
        VlanID: 2063
        VlanMode: Access
veos:
  cd_image_filename: Aboot-veos-serial-8.0.0.iso
  credentials:
    password: 123456
    username: admin
  eos_ansible:
    ansible_password: 123456
    ansible_user: admin
  hdd_image_filename: vEOS-lab-4.20.15M.vmdk
  max_fp_num: 4
  memory: 2097152
  proxy_env:
    http_proxy: http://173.36.224.108:80
    https_proxy: http://173.36.224.108:80
  root_path: /home/azure/veos-vm
  skip_image_downloading: false
  vm_console_base: 7000
  vm_host_ansible:
    ansible_password: cisco123
    ansible_sudo_pass: cisco123
    ansible_user: vxr
  vm_images_url: https://acsbe.blob.core.windows.net/vmimages
  vm_host_1:
    STR-ACS-SERV-01:
      ansible_host: 192.168.122.150
  vms_1:
    VM0100:
      ansible_host: 192.168.122.94
    VM0101:
      ansible_host: 192.168.122.228
    VM0102:
      ansible_host: 192.168.122.40
    VM0103:
      ansible_host: 192.168.122.188
veos_groups:
  eos:
    children:
    - vms_1
  server_1:
    children:
    - vm_host_1
    - vms_1
    vars:
      host_var_file: host_vars/STR-ACS-SERV-01.yml
  servers:
    children:
    - server_1
    vars:
      topologies:
      - t1
      - t1-lag
      - t1-64-lag
      - t1-64-lag-clet
      - t0
      - t0-56
      - t0-52
      - ptf32
      - ptf64
      - t0-64
      - t0-64-32
      - t0-116
  vm_host:
    children:
    - vm_host_1
  vm_host_1:
    host:
    - STR-ACS-SERV-01
  vms_1:
    host:
    - VM0100
    - VM0101
    - VM0102
    - VM0103
