- name: Set ansible login user name and password
  set_fact: ansible_user="root" ansible_password={{ eos_root_password }}

- name: Set EOS backplane port name
  set_fact: bp_ifname="Ethernet9"

- name: copy rc.eos
  copy: src=rc.eos
        dest=/mnt/flash/rc.eos
  when: hostname in configuration
  notify:
    - Update VM state

- name: copy boot-config
  copy: src=boot-config
        dest=/mnt/flash/boot-config
  when: hostname in configuration
  notify:
    - Update VM state

- name: update startup-config
  template: src="{{ topo }}-{{ props.swrole }}.j2"
            dest=/mnt/flash/startup-config
  when: hostname in configuration
  notify:
    - Update VM state
