import ipaddress
import logging
import os
import pytest
import re
import tempfile
from tests.common import config_reload
from tests.common.platform.processes_utils import wait_critical_processes
from tests.common.utilities import wait_until
from tests.common.helpers.assertions import pytest_assert

pytestmark = [
    pytest.mark.topology('t0', 't1'),
    pytest.mark.disable_loganalyzer,
]

logger = logging.getLogger(__name__)

# Global skip list for FRR commands that may not appear in 'show running-config' output
# These commands are hidden when their values match FRR defaults
SKIP_CONFIG_COMMANDS = [
    'zebra nexthop kernel enable'
]

# FRR config files generated by docker_init.sh — only these should be verified
# against vtysh running-config. Excludes stale non-config files (e.g.
# support_bundle_commands.conf) that may persist on upgraded switches.
#
# Source: dockers/docker-fpm-frr/docker_init.sh in sonic-buildimage.
# Update this set if new FRR daemon configs are added there.
SONIC_FRR_CONFIG_FILES = {
    'bgpd.conf', 'zebra.conf', 'staticd.conf', 'vtysh.conf',
    'bfdd.conf', 'ospfd.conf',
    'frr.conf',
}


def parse_frr_config_file(duthost, config_file):
    """
    Parse FRR configuration file and extract meaningful configuration lines
    """
    config_lines = []
    try:
        # Read the configuration file
        cmd = "sudo cat /etc/sonic/frr/{}".format(config_file)
        result = duthost.shell(cmd)

        for line in result['stdout_lines']:
            line = line.strip()
            # Skip empty lines and comments
            if (line and not line.startswith('!')):
                config_lines.append(line)

    except Exception as e:
        logger.warning("Failed to read config file {}: {}".format(config_file, str(e)))

    return config_lines


def parse_vtysh_running_config(duthost):
    """
    Get running configuration from vtysh and parse it
    """
    try:
        result = duthost.shell('vtysh -c "show running-config"')
        running_config = result['stdout']
        return running_config
    except Exception as e:
        logger.error("Failed to get running configuration: {}".format(str(e)))
        return ""


def normalize_config_line(line):
    """
    Normalize configuration line for comparison
    Remove extra spaces and standardize format
    """
    # Remove extra whitespace
    line = re.sub(r'\s+', ' ', line.strip())
    return line


def is_config_in_running(config_line, running_config):
    """
    Check if a configuration line exists in running configuration
    """
    normalized_config = normalize_config_line(config_line)
    normalized_running = normalize_config_line(running_config)

    # Direct match
    if normalized_config in normalized_running:
        return True

    # Check for partial matches for complex configurations
    # Split the config line into words for more flexible matching
    config_words = normalized_config.split()
    if len(config_words) > 1:
        # Check if all words in config line appear in the same context in running config
        lines = normalized_running.split('\n')
        for line in lines:
            if all(word in line for word in config_words):
                return True

    return False


def verify_frr_config_in_running(duthost, config_file, running_config):
    """
    Verify that configurations in config file are present in running configuration
    """
    logger.info("Verifying FRR config file: {}".format(config_file))

    # Get configuration lines from file
    config_lines = parse_frr_config_file(duthost, config_file)
    logger.info("Parsed {} lines from config file {}".format(len(config_lines), config_file))
    logger.debug("Configuration lines: {}".format(config_lines))

    if not running_config:
        pytest.fail("Failed to get running configuration from vtysh")

    missing_configs = []

    # Check each configuration line
    for config_line in config_lines:
        # Skip certain lines that are not expected in running config (regex patterns)
        skip_patterns = [
            r'password\s+',           # password lines are security-related and not shown
            r'^interface\s+',
            r'^link-detect$',
            r'^network\s+',
            r'^maximum-paths\s+',
        ]

        should_skip = False

        # Check against regex patterns
        for pattern in skip_patterns:
            # re.IGNORECASE makes the pattern matching case-insensitive
            # This means 'HOSTNAME', 'hostname', 'Hostname' will all match r'hostname\s+'
            if re.match(pattern, config_line, re.IGNORECASE):
                should_skip = True
                logger.debug("Skipping config line '{}' (matched pattern: {})".format(config_line, pattern))
                break

        # Check against global skip command list (commands that may be hidden when matching defaults)
        if not should_skip:
            for skip_cmd in SKIP_CONFIG_COMMANDS:
                if config_line.lower().startswith(skip_cmd.lower()):
                    should_skip = True
                    logger.debug("Skipping config line '{}' (matched skip command: {})".format(
                        config_line, skip_cmd))
                    break

        if should_skip:
            continue

        if not is_config_in_running(config_line, running_config):
            missing_configs.append(config_line)
            logger.warning("Configuration '{}' from {} not found in running config".format(
                config_line, config_file))

    return missing_configs


def get_frr_config_files(duthost):
    """
    Get list of FRR config files from /etc/sonic/frr directory
    """
    config_files = []
    try:
        result = duthost.shell("ls /etc/sonic/frr")
        for file in result['stdout_lines']:
            file = file.strip()
            if file in SONIC_FRR_CONFIG_FILES:
                config_files.append(file)
        logger.info("Found FRR config files: {}".format(config_files))
        return config_files
    except Exception as e:
        logger.error("Failed to get FRR config files: {}".format(str(e)))
        return config_files


# Add iteration level mapping similar to bgp_stress_link_flap
ITERATION_LEVEL_MAP = {
    'debug': 1,
    'basic': 3,
    'confident': 10,
    'thorough': 50
}

# Number of config_reload iterations for stress test (tunable via completeness level)
STRESS_ITERATION_LEVEL_MAP = {
    'debug': 1,
    'basic': 2,
    'confident': 5,
    'thorough': 10,
}

# Stress test marker prefix — all injected config uses this for easy identification
STRESS_MARKER = 'STRESS_TEST_'

# Template path inside BGP containers — includes chain for both modes:
#   separated: gen_bgpd.conf.j2 -> bgpd.conf.j2 -> bgpd.main.conf.j2
#   unified:   gen_frr.conf.j2  -> frr.conf.j2   -> bgpd.main.conf.j2
_TEMPLATE_PATH = '/usr/share/sonic/templates/bgpd/bgpd.main.conf.j2'

# Uniform stress injection counts (independent of device role/scale)
_STRESS_PREFIX_LIST_COUNT = 200
_STRESS_COMMUNITY_LIST_COUNT = 100
_STRESS_ROUTE_MAP_COUNT = 300


def _generate_stress_policy_content():
    """Generate plain FRR policy config (prefix-lists, community-lists, route-maps).

    This content is inserted into bgpd.main.conf.j2 before the 'router bgp' line.
    All objects use the STRESS_TEST_ prefix for identification and cleanup.
    Content is plain text — no Jinja2 variables — safe for sonic-cfggen passthrough.
    """
    lines = ['!', '! === FRR STRESS TEST POLICY BEGIN ===', '!']

    for i in range(_STRESS_PREFIX_LIST_COUNT):
        o2, o3 = (i // 256) % 256, i % 256
        lines.append('ip prefix-list {}PL_{} seq 5 permit 10.{}.{}.0/24'.format(STRESS_MARKER, i, o2, o3))

    lines.append('!')

    for i in range(_STRESS_COMMUNITY_LIST_COUNT):
        comm = (i % 65534) + 1
        lines.append('bgp community-list standard {}CL_{} permit {}:{}'.format(STRESS_MARKER, i, comm, comm))

    lines.append('!')

    for i in range(_STRESS_ROUTE_MAP_COUNT):
        comm = (i % 65534) + 1
        lines.append('route-map {}RM_{} permit 10'.format(STRESS_MARKER, i))
        lines.append(' match ip address prefix-list {}PL_{}'.format(STRESS_MARKER, i % _STRESS_PREFIX_LIST_COUNT))
        lines.append(' set community {}:{}'.format(comm, comm))
        lines.append('!')

    lines.extend(['!', '! === FRR STRESS TEST POLICY END ===', '!'])
    return '\n'.join(lines)


def _inject_policy_into_template(duthost, bgp_name, policy_content):
    """Insert policy content into bgpd.main.conf.j2 before the 'router bgp' line."""
    result = duthost.shell("docker exec {} cat {}".format(bgp_name, _TEMPLATE_PATH))
    original = result['stdout']

    output_lines = []
    inserted = False
    for line in original.splitlines():
        if not inserted and line.strip().startswith('router bgp'):
            output_lines.append(policy_content)
            inserted = True
        output_lines.append(line)

    if not inserted:
        logger.warning("No 'router bgp' found in %s:%s, appending at end", bgp_name, _TEMPLATE_PATH)
        output_lines.append(policy_content)

    modified = '\n'.join(output_lines)
    # Write modified template to local temp file, then transfer to DUT.
    # Cannot use duthost.shell() with heredoc or duthost.copy(content=) because Ansible
    # templates all strings through Jinja2, which corrupts the {% %}/{{ }} template directives.
    with tempfile.NamedTemporaryFile(mode='w', suffix='.j2', delete=False) as f:
        f.write(modified)
        local_tmp = f.name
    duthost.copy(src=local_tmp, dest='/tmp/frr_stress_template.txt')
    os.unlink(local_tmp)
    duthost.shell("docker cp /tmp/frr_stress_template.txt {}:{}".format(bgp_name, _TEMPLATE_PATH))


def _normalize_network_line(line):
    """Normalize 'network <prefix>' lines to canonical form.

    FRR normalizes prefixes via %pFX format (e.g., 'network fc00:1::32/64'
    becomes 'network fc00:1::/64'). Apply the same normalization so rendered
    template lines match running-config output.
    """
    m = re.match(r'^(network\s+)(\S+)(.*)', line)
    if m:
        try:
            net = ipaddress.ip_network(m.group(2), strict=False)
            return '{}{}{}'.format(m.group(1), str(net), m.group(3))
        except ValueError:
            pass
    return line


def _verify_config_file_forward(config_content, running_config):
    """Forward check: ALL meaningful config lines must appear in running-config.

    Validates both baseline config (e.g., router-id, neighbor statements) AND
    stress-injected objects. This catches the production bug where critical config
    like 'bgp router-id' was missing after reload.

    For STRESS_MARKER lines: uses name-based matching to tolerate FRR normalization
    (e.g., auto-inserted 'seq N' in community-lists).
    For baseline lines: uses normalized substring matching.
    Known FRR normalization gaps are skipped via skip_patterns.
    """
    # Lines that FRR may not reproduce verbatim in 'show running-config'
    skip_patterns = [
        r'^password\s+',           # security-related, hidden in running-config
        r'^interface\s+',          # interface context lines rendered differently
        r'^link-detect$',          # implicit, not shown
        r'^zebra nexthop kernel',  # platform-specific, may not appear
    ]

    # Dynamic maximum-paths detection: FRR's bgp_config_write_maxpaths()
    # suppresses 'maximum-paths N' when N equals the compile-time MULTIPATH_NUM.
    # The value of MULTIPATH_NUM varies by build (514 on master, 64 on 202405).
    # Detect suppressed values by finding maximum-paths lines in the rendered
    # config that are absent from running-config, and skip only those.
    for cfg_line in config_content.splitlines():
        mp_match = re.match(r'^\s*maximum-paths(?:\s+ibgp)?\s+(\d+)\s*$', cfg_line.strip())
        if mp_match:
            mp_val = mp_match.group(1)
            if 'maximum-paths {}'.format(mp_val) not in running_config \
                    and 'maximum-paths ibgp {}'.format(mp_val) not in running_config:
                skip_patterns.append(r'^maximum-paths\s+{}\s*$'.format(re.escape(mp_val)))
                skip_patterns.append(r'^maximum-paths\s+ibgp\s+{}\s*$'.format(re.escape(mp_val)))

    missing = []
    normalized_running = normalize_config_line(running_config)

    for line in config_content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('!') or stripped.startswith('#'):
            continue

        # Check skip patterns (known FRR normalization gaps)
        if any(re.match(p, stripped, re.IGNORECASE) for p in skip_patterns):
            continue

        # For STRESS_MARKER lines: use name-based matching (handles seq N insertion)
        if STRESS_MARKER in stripped:
            match = re.search(r'({}(?:PL|CL|RM|PEER)_\d+)'.format(re.escape(STRESS_MARKER)), stripped)
            if match and match.group(1) not in running_config:
                missing.append(stripped)
        else:
            # Normalize network lines before comparison (FRR canonicalizes prefixes)
            check_line = stripped
            if re.match(r'^network\s+', stripped):
                check_line = _normalize_network_line(stripped)

            # Baseline config: use normalized substring match
            normalized_line = normalize_config_line(check_line)
            if normalized_line not in normalized_running:
                # Also try word-based matching (handles minor spacing differences)
                if not is_config_in_running(check_line, running_config):
                    missing.append(stripped)

    return missing


def test_frr_config_check(duthosts, enum_rand_one_per_hwsku_frontend_hostname, get_function_completeness_level):
    """
    Test FRR configuration consistency
    1. Get current FRR running configuration using 'vtysh -c "show running"'
    2. Read config files and get configurations
    3. Compare config file contents with FRR running configuration
    4. Perform config reload
    5. Repeat the comparison after config reload
    """
    duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
    logger.info("Starting FRR configuration check test on {}".format(duthost.hostname))

    # Get completeness level and set number of iterations
    normalized_level = get_function_completeness_level
    if normalized_level is None:
        normalized_level = 'debug'
    num_iterations = ITERATION_LEVEL_MAP[normalized_level]
    logger.info('Completeness level: {}, setting iterations to: {}'.format(normalized_level, num_iterations))

    # FRR config files to check - ['bgpd.conf', 'staticd.conf', 'zebra.conf', 'vtysh.conf']
    frr_config_files = get_frr_config_files(duthost)
    logger.info("FRR config files to check: {}".format(frr_config_files))

    # Get current FRR running configuration (once)
    logger.info("Getting FRR running configuration")
    running_config = parse_vtysh_running_config(duthost)
    # logger.debug("Running configuration: {}".format(running_config))

    # Initial configuration verification
    logger.info("Verifying initial FRR configuration consistency")
    initial_missing_configs = {}

    for config_file in frr_config_files:
        missing_configs = verify_frr_config_in_running(duthost, config_file, running_config)
        logger.info("Missing configurations in {}: {}".format(config_file, missing_configs))
        if missing_configs:
            initial_missing_configs[config_file] = missing_configs

    # Log initial results
    if initial_missing_configs:
        logger.warning("Initial check - Found missing configurations:")
        for config_file, missing in initial_missing_configs.items():
            logger.warning("File {}: {}".format(config_file, missing))
    else:
        logger.info("Initial check - All configurations are present in running config")

    # Loop for repeated config reload and verification
    logger.info("Starting {} iterations of config reload and verification".format(num_iterations))

    for iteration in range(1, num_iterations + 1):
        logger.info("ITERATION {}/{}".format(iteration, num_iterations))

        # Perform config reload
        logger.info("Iteration {}: Performing config reload".format(iteration))
        try:
            config_reload(duthost, safe_reload=True, check_intf_up_ports=True)
            wait_critical_processes(duthost)
            logger.info("Iteration {}: Config reload completed successfully".format(iteration))
        except Exception as e:
            pytest.fail("Iteration {}: Config reload failed: {}".format(iteration, str(e)))

        # Get running configuration again after reload
        logger.info("Iteration {}: Getting FRR running configuration after reload".format(iteration))
        post_reload_running_config = parse_vtysh_running_config(duthost)

        # Verify configuration after reload
        logger.info("Iteration {}: Verifying FRR configuration after config reload".format(iteration))
        post_reload_missing_configs = {}

        for config_file in frr_config_files:
            missing_configs = verify_frr_config_in_running(duthost, config_file, post_reload_running_config)
            if missing_configs:
                post_reload_missing_configs[config_file] = missing_configs
                logger.warning("Iteration {}: Missing configs in {}: {}".format(
                    iteration, config_file, missing_configs))

        # Compare with initial results
        logger.info("Iteration {}: Comparing with initial configuration check".format(iteration))
        if initial_missing_configs == post_reload_missing_configs:
            logger.info("Iteration {}: Configuration consistency maintained".format(iteration))
        else:
            logger.warning("Iteration {}: Configuration consistency changed".format(iteration))
            logger.warning("Initial missing: {}".format(initial_missing_configs))
            logger.warning("Current missing: {}".format(post_reload_missing_configs))

        # Final verification for this iteration
        if post_reload_missing_configs:
            logger.error("Iteration {}: Found missing configurations:".format(iteration))
            for config_file, missing in post_reload_missing_configs.items():
                logger.error("Iteration {}: File {}: {}".format(iteration, config_file, missing))

            # Fail immediately when configuration inconsistency is detected
            pytest.fail("Iteration {}: FRR configuration inconsistency detected after config reload".format(iteration))
        else:
            logger.info("Iteration {}: All configurations are present in running config".format(iteration))

    logger.info("Completed {} iterations of config reload and verification".format(num_iterations))


@pytest.mark.topology('t0', 't1', 't2', 'lrh', 'urh')
def test_frr_large_config_load_stress(duthosts, enum_rand_one_per_hwsku_frontend_hostname,
                                      get_function_completeness_level):
    """Stress test FRR config file loading with large configuration.

    Injects stress config via policy objects (prefix-lists, community-lists,
    route-maps) appended to bgpd.main.conf.j2. After sonic-cfggen renders the
    modified template, FRR loads the (now large) config file from scratch.

    Performs N config_reload cycles (tunable via --completeness_level).
    Each reload triggers sonic-cfggen to re-render the modified template,
    and FRR to load the large config file. Verifies config consistency after
    each reload via forward check (every meaningful line in the rendered
    config must appear in running-config).

    Supports 'separated' and 'unified' docker_routing_config_mode.
    Skips for 'split', 'split-unified', and FRR management framework.
    """
    duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
    logger.info("Starting FRR large config load stress test on %s", duthost.hostname)

    # --- Tunable iteration count ---
    normalized_level = get_function_completeness_level
    if normalized_level is None:
        normalized_level = 'basic'
    num_iterations = STRESS_ITERATION_LEVEL_MAP[normalized_level]
    logger.info("Completeness level: %s, stress iterations: %d", normalized_level, num_iterations)

    # --- Skip conditions ---
    mode = duthost.shell(
        "sonic-db-cli CONFIG_DB hget 'DEVICE_METADATA|localhost' docker_routing_config_mode",
        module_ignore_errors=True)['stdout'].strip()
    if mode not in ('separated', 'unified', ''):
        pytest.skip("docker_routing_config_mode '{}' not supported — test requires separated or unified".format(mode))
    logger.info("Config mode: %s", mode or 'separated (default)')

    if duthost.get_frr_mgmt_framework_config():
        pytest.skip("FRR management framework enabled — test requires classic bgpcfgd path")

    bgp_docker_names = duthost.get_bgp_docker_names()
    logger.info("BGP containers: %s", bgp_docker_names)

    # Determine rendered config file path per mode
    rendered_path = '/etc/frr/frr.conf' if mode == 'unified' else '/etc/frr/bgpd.conf'

    # --- Generate policy content (template stress) ---
    policy_content = _generate_stress_policy_content()
    policy_line_count = len([ln for ln in policy_content.splitlines() if ln.strip() and not ln.strip().startswith('!')])
    logger.info("Generated stress policy: %d lines (%d prefix-lists, %d community-lists, %d route-maps)",
                policy_line_count, _STRESS_PREFIX_LIST_COUNT, _STRESS_COMMUNITY_LIST_COUNT, _STRESS_ROUTE_MAP_COUNT)

    # --- Inject + reload ---
    backed_up = []
    try:
        # Backup + inject policy into template in each BGP container
        for bgp_name in bgp_docker_names:
            logger.info("Backing up %s in %s", _TEMPLATE_PATH, bgp_name)
            rc = duthost.shell("docker cp {}:{} /tmp/frr_template_bak_{}".format(
                bgp_name, _TEMPLATE_PATH, bgp_name), module_ignore_errors=True)
            if rc['rc'] != 0:
                pytest.fail("Failed to backup template in {}: {}".format(bgp_name, rc['stderr']))
            backed_up.append(bgp_name)
            _inject_policy_into_template(duthost, bgp_name, policy_content)
            logger.info("Injected policy into %s:%s", bgp_name, _TEMPLATE_PATH)

        # --- Reload + verify iterations ---
        for iteration in range(1, num_iterations + 1):
            logger.info("=== STRESS ITERATION %d/%d ===", iteration, num_iterations)

            try:
                config_reload(duthost, safe_reload=True, check_intf_up_ports=True)
            except Exception as e:
                pytest.fail("Iteration {}: config_reload failed: {}".format(iteration, str(e)))

            # Per-ASIC verification
            for asic_id in duthost.get_asic_ids():
                asic = duthost.asic_instance(asic_id)
                bgp_name = bgp_docker_names[0] if len(bgp_docker_names) == 1 else 'bgp{}'.format(asic_id)

                # Wait for stress content in running-config (bgpcfgd is async)
                def _stress_content_present():
                    rc = asic.run_vtysh("-c 'show running-config'")['stdout']
                    return rc.count(STRESS_MARKER) > 0

                pytest_assert(wait_until(180, 15, 10, _stress_content_present),
                              "Iter {}, ASIC {}: Stress content not in running-config within 180s".format(
                                  iteration, asic_id))

                # Defensive check: verify injected template is in the render chain.
                # On first iteration only — if it works once, the chain is valid.
                if iteration == 1:
                    rendered_check = duthost.shell(
                        "docker exec {} cat {}".format(bgp_name, rendered_path),
                        module_ignore_errors=True)
                    if rendered_check['rc'] == 0 and STRESS_MARKER not in rendered_check['stdout']:
                        pytest.skip(
                            "Injected template not in render chain for mode '{}' — "
                            "{} does not contain stress content".format(mode, rendered_path))

                # Forward check: every meaningful line in rendered config file must appear in running-config
                running = asic.run_vtysh("-c 'show running-config'")['stdout']
                config_result = duthost.shell("docker exec {} cat {}".format(bgp_name, rendered_path),
                                              module_ignore_errors=True)
                pytest_assert(config_result['rc'] == 0, "Iter {}, ASIC {}: Failed to read {}".format(
                    iteration, asic_id, rendered_path))

                missing = _verify_config_file_forward(config_result['stdout'], running)

                if missing:
                    for line in missing[:20]:
                        logger.error("  MISSING: %s", line)
                    pytest.fail("Iter {}, ASIC {}: {} config lines missing from running-config (first: '{}')".format(
                        iteration, asic_id, len(missing), missing[0]))

                logger.info("Iter %d, ASIC %s: forward check OK", iteration, asic_id)

                logger.info("Iteration %d, ASIC %s: Verification passed", iteration, asic_id)

            logger.info("=== STRESS ITERATION %d/%d PASSED ===", iteration, num_iterations)

    finally:
        logger.info("Cleaning up stress test artifacts")

        # Restore template backups (only for containers that were successfully backed up)
        for bgp_name in backed_up:
            duthost.shell("docker cp /tmp/frr_template_bak_{b} {b}:{p}".format(b=bgp_name, p=_TEMPLATE_PATH),
                          module_ignore_errors=True)
        duthost.shell("rm -f /tmp/frr_template_bak_* /tmp/frr_stress_template.txt /tmp/frr_stress_content.txt",
                      module_ignore_errors=True)

        # Final config_reload to restore clean state
        try:
            config_reload(duthost, safe_reload=True, check_intf_up_ports=True)
            logger.info("Cleanup config_reload completed")
        except Exception as e:
            logger.error("Cleanup config_reload failed: %s", str(e))

    logger.info("FRR large config load stress test completed: %d iterations, %d BGP containers",
                num_iterations, len(bgp_docker_names))
