ansible_connection: multi_passwd_ssh

ansible_user: "{{ lookup('env', 'SONIC_MGMT_PTF_USER') | default('root', true) }}"
ansible_password: "{{ lookup('env', 'SONIC_MGMT_PTF_PASSWORD') | default('root', true) }}"
ansible_ssh_pass: "{{ lookup('env', 'SONIC_MGMT_PTF_PASSWORD') | default('root', true) }}"
# ansible_altpasswords:
#   - fakepassword1
#   - fakepassword2
