topology:
  VMs:
    ARISTA01RWA:
      vlans:
        - 6
      vm_offset: 0
    ARISTA02RWA:
      vlans:
        - 12
      vm_offset: 1
    ARISTA01LRH:
      vlans:
        - 13
      vm_offset: 2
    ARISTA02LRH:
      vlans:
        - 24
      vm_offset: 3
    ARISTA03LRH:
      vlans:
        - 25
      vm_offset: 4
    ARISTA04LRH:
      vlans:
        - 34
      vm_offset: 5

  DUT:
    loopback:
      ipv4:
        - 10.1.0.1/32
      ipv6:
        - fc00:10::1/128

configuration_properties:
  common:
    podset_number: 400
    tor_number: 16
    tor_subnet_number: 8
    max_tor_subnet_number: 32
    tor_subnet_size: 128
    dut_asn: 64983
    dut_confed_asn: 64915
    dut_confed_peers: "64981"
    dut_type: UpperRegionalHub
    nhipv4: 10.10.246.254
    nhipv6: fc0a::ff
  core:
    swrole: core
  leaf:
    swrole: leaf

configuration:
  ARISTA01RWA:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        64915:
          - 10.0.0.0
          - fc00::1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.1/32
        ipv6: 2064:100::1/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.1/31
        ipv6: fc00::2/126
    bp_interface:
      ipv4: 10.10.246.1/24
      ipv6: fc0a::2/64
  ARISTA02RWA:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        64915:
          - 10.0.0.2
          - fc00::5
    interfaces:
      Loopback0:
        ipv4: 100.1.0.2/32
        ipv6: 2064:100::2/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.3/31
        ipv6: fc00::6/126
    bp_interface:
      ipv4: 10.10.246.2/24
      ipv6: fc0a::4/64
  ARISTA01LRH:
    properties:
      - common
      - leaf
    bgp:
      asn: 64981
      confed_asn: 64915
      confed_peers: "64983"
      peers:
        64983:
          - 10.0.0.100
          - fc00::d
    interfaces:
      Loopback0:
        ipv4: 100.1.0.51/32
        ipv6: 2064:100::33/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.101/31
        ipv6: fc00::e/126
    bp_interface:
      ipv4: 10.10.246.101/24
      ipv6: fc0a::66/64
  ARISTA02LRH:
    properties:
      - common
      - leaf
    bgp:
      asn: 64981
      confed_asn: 64915
      confed_peers: "64983"
      peers:
        64983:
          - 10.0.0.102
          - fc00::11
    interfaces:
      Loopback0:
        ipv4: 100.1.0.52/32
        ipv6: 2064:100::34/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.103/31
        ipv6: fc00::12/126
    bp_interface:
      ipv4: 10.10.246.102/24
      ipv6: fc0a::68/64
  ARISTA03LRH:
    properties:
      - common
      - leaf
    bgp:
      asn: 64981
      confed_asn: 64915
      confed_peers: "64983"
      peers:
        64983:
          - 10.0.0.104
          - fc00::15
    interfaces:
      Loopback0:
        ipv4: 100.1.0.53/32
        ipv6: 2064:100::35/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.105/31
        ipv6: fc00::16/126
    bp_interface:
      ipv4: 10.10.246.103/24
      ipv6: fc0a::6a/64
  ARISTA04LRH:
    properties:
      - common
      - leaf
    bgp:
      asn: 64981
      confed_asn: 64915
      confed_peers: "64983"
      peers:
        64983:
          - 10.0.0.106
          - fc00::19
    interfaces:
      Loopback0:
        ipv4: 100.1.0.54/32
        ipv6: 2064:100::36/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.107/31
        ipv6: fc00::1a/126
    bp_interface:
      ipv4: 10.10.246.104/24
      ipv6: fc0a::6c/64
