topology:
  VMs:
    ARISTA01T1:
      vlans:
        - 0
      vm_offset: 0
    ARISTA02T1:
      vlans:
        - 1
      vm_offset: 1
    ARISTA03T1:
      vlans:
        - 2
      vm_offset: 2
    ARISTA04T1:
      vlans:
        - 3
      vm_offset: 3
    ARISTA05T1:
      vlans:
        - 4
      vm_offset: 4
    ARISTA06T1:
      vlans:
        - 5
      vm_offset: 5
    ARISTA01UT2:
      vlans:
        - 6
      vm_offset: 6
    ARISTA02UT2:
      vlans:
        - 7
      vm_offset: 7

configuration_properties:
  common:
    dut_asn: 4200100000
    dut_type: LowerSpineRouter
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF
    podset_number: 200
    tor_number: 16
    tor_subnet_number: 2
    max_tor_subnet_number: 16
    tor_subnet_size: 128
  spine:
    swrole: spine
  leaf:
    swrole: leaf

configuration:
  ARISTA01T1:
    properties:
    - common
    - leaf
    tornum: 1
    bgp:
      asn: 4200000000
      peers:
        4200100000:
          - 10.0.0.0
          - fc00::1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.1/32
        ipv6: 2064:100:0:1::/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.1/31
        ipv6: fc00::2/126
    bp_interface:
      ipv4: 10.10.246.2/24
      ipv6: fc0a::2/64
  ARISTA02T1:
    properties:
    - common
    - leaf
    tornum: 2
    bgp:
      asn: 4200000000
      peers:
        4200100000:
          - 10.0.0.2
          - fc00::5
    interfaces:
      Loopback0:
        ipv4: 100.1.0.2/32
        ipv6: 2064:100:0:2::/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.3/31
        ipv6: fc00::6/126
    bp_interface:
      ipv4: 10.10.246.3/24
      ipv6: fc0a::3/64
  ARISTA03T1:
    properties:
    - common
    - leaf
    tornum: 3
    bgp:
      asn: 4200000000
      peers:
        4200100000:
          - 10.0.0.4
          - fc00::9
    interfaces:
      Loopback0:
        ipv4: 100.1.0.3/32
        ipv6: 2064:100:0:3::/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.5/31
        ipv6: fc00::a/126
    bp_interface:
      ipv4: 10.10.246.4/24
      ipv6: fc0a::4/64
  ARISTA04T1:
    properties:
    - common
    - leaf
    tornum: 4
    bgp:
      asn: 4200000000
      peers:
        4200100000:
          - 10.0.0.6
          - fc00::d
    interfaces:
      Loopback0:
        ipv4: 100.1.0.4/32
        ipv6: 2064:100:0:4::/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.7/31
        ipv6: fc00::e/126
    bp_interface:
      ipv4: 10.10.246.5/24
      ipv6: fc0a::5/64
  ARISTA05T1:
    properties:
    - common
    - leaf
    tornum: 5
    bgp:
      asn: 4200000000
      peers:
        4200100000:
          - 10.0.0.8
          - fc00::11
    interfaces:
      Loopback0:
        ipv4: 100.1.0.5/32
        ipv6: 2064:100:0:5::/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.9/31
        ipv6: fc00::12/126
    bp_interface:
      ipv4: 10.10.246.6/24
      ipv6: fc0a::6/64
  ARISTA06T1:
    properties:
    - common
    - leaf
    tornum: 6
    bgp:
      asn: 4200000000
      peers:
        4200100000:
          - 10.0.0.10
          - fc00::15
    interfaces:
      Loopback0:
        ipv4: 100.1.0.6/32
        ipv6: 2064:100:0:6::/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.11/31
        ipv6: fc00::16/126
    bp_interface:
      ipv4: 10.10.246.7/24
      ipv6: fc0a::7/64
  ARISTA01UT2:
    properties:
    - common
    - spine
    bgp:
      asn: 4200200000
      peers:
        4200100000:
          - 10.0.0.180
          - fc00::169
    interfaces:
      Loopback0:
        ipv4: 100.1.0.91/32
        ipv6: 2064:100:0:5b::/128
      Ethernet1:
        ipv4: 10.0.0.181/31
        ipv6: fc00::16a/126
    bp_interface:
      ipv4: 10.10.246.92/24
      ipv6: fc0a::5c/64
  ARISTA02UT2:
    properties:
    - common
    - spine
    bgp:
      asn: 4200200000
      peers:
        4200100000:
          - 10.0.0.182
          - fc00::16d
    interfaces:
      Loopback0:
        ipv4: 100.1.0.92/32
        ipv6: 2064:100:0:5c::/128
      Ethernet1:
        ipv4: 10.0.0.183/31
        ipv6: fc00::16e/126
    bp_interface:
      ipv4: 10.10.246.93/24
      ipv6: fc0a::5d/64
