allure:
  debian-url: http://172.29.93.10/sonic-images/sonicci/allure_2.32.0-1_all.deb
  local-report-dir: /tmp/allure_results
  report-url-file-path: allure_report_url.log
  remote-report-dir: /auto/sonic/allure/reports
  server-base-url: https://allure.cisco.com