"""Compatibility imports for the common port-attribute parser."""

from tests.common.port_attributes.attribute_keys import (
    BASE_ATTRIBUTES_KEY,
    CDB_FIRMWARE_UPGRADE_ATTRIBUTES_KEY,
    DOM_ATTRIBUTES_KEY,
    EEPROM_ATTRIBUTES_KEY,
    FEC_ATTRIBUTES_KEY,
    PHYSICAL_OIR_ATTRIBUTES_KEY,
    PM_ATTRIBUTES_KEY,
    PORT_CONFIG_ATTRIBUTES_KEY,
    REMOTE_RESEAT_ATTRIBUTES_KEY,
    SYSTEM_ATTRIBUTES_KEY,
    VDM_ATTRIBUTES_KEY,
)

__all__ = [
    "BASE_ATTRIBUTES_KEY",
    "CDB_FIRMWARE_UPGRADE_ATTRIBUTES_KEY",
    "DOM_ATTRIBUTES_KEY",
    "EEPROM_ATTRIBUTES_KEY",
    "FEC_ATTRIBUTES_KEY",
    "PHYSICAL_OIR_ATTRIBUTES_KEY",
    "PM_ATTRIBUTES_KEY",
    "PORT_CONFIG_ATTRIBUTES_KEY",
    "REMOTE_RESEAT_ATTRIBUTES_KEY",
    "SYSTEM_ATTRIBUTES_KEY",
    "VDM_ATTRIBUTES_KEY",
]
