device_groups:
  fanout:
    host:
    - nexus-5
  lab:
    children:
    - sonic
    - fanout
    vars:
      mgmt_subnet_mask_length: '24'
  ptf:
    host:
    - docker-ptf
  sonic:
    children:
    - sonic_cisco
  sonic_cisco:
    host:
    - sfd-lc0
    - sfd-lc1
    - sfd-01
    vars:
      hwsku: msft_multi_asic_vs # TODO is this the correct SKU??
      iface_speed: '100000'
devices:
  sfd-lc0:
    alias: null
    ansible:
      ansible_host: 192.168.122.48
      ansible_ssh_pass: cisco123
      ansible_ssh_user: cisco
    credentials:
      enable_password: cisco123
      password: cisco123
      username: cisco
    device_type: DevSonic
    hwsku: 8800-LC-48H-O
    card_type: Linecard
    num_asics: '2'
    switch_type: 'chassis-packet'
    slot_num: '1'
    os: sonic
  sfd-lc1:
    alias: null
    ansible:
      ansible_host: 192.168.122.49
      ansible_ssh_pass: cisco123
      ansible_ssh_user: cisco
    credentials:
      enable_password: cisco123
      password: cisco123
      username: cisco
    device_type: DevSonic
    hwsku: 8800-LC-48H-O
    card_type: Linecard
    num_asics: '2'
    switch_type: 'chassis-packet'
    slot_num: '2'
    os: sonic
  sfd-01:
    alias: null
    ansible:
      ansible_host: 192.168.122.47
      ansible_ssh_pass: cisco123
      ansible_ssh_user: cisco
    credentials:
      enable_password: cisco123
      password: cisco123
      username: cisco
    device_type: DevSonic
    hwsku: 8800-RP-O
    os: sonic
    card_type: supervisor
    num_asics: '16'
    asics_present: [0,1]
    switch_type: 'chassis-packet'
  nexus-5:
    alias: null
    ansible:
      ansible_host: 10.251.0.13/23
      ansible_ssh_pass: password
      ansible_ssh_user: user
      fanout_sonic_password: password
      fanout_sonic_user: admin
    credentials:
      password: null
      username: null
    device_type: FanoutLeaf
    hwsku: Arista-7260QX-64
  docker-ptf:
    device_type: blank
    hwsku:
    ansible:
        ansible_ssh_user: root
        ansible_host: 1.74.23.21/16
        ansible_hostv6: fc0b::1/64
        ansible_ssh_pass: root
    credentials:
        password: root
        username: root
  str-acs-serv-01:
    alias: null
    ansible:
      ansible_become_pass: cisco123
      ansible_host: 172.17.0.1/23
      ansible_ssh_pass: cisco123
      ansible_ssh_user: vxr
      sonicadmin_initial_password: cisco123
      sonicadmin_password: cisco123
      sonicadmin_user: admin
    credentials:
      password: cisco123
      username: vxr
    device_type: server
    hwsku: TestServ
    mgmt_subnet_mask_length: '24'
docker_registry:
  docker_registry_host: sonicdev-microsoft.azurecr.io:443
  docker_registry_password: sonic
  docker_registry_username: 1dafc8d7-d19c-4f58-8653-e8d904f30dab
host_vars:
  str-acs-serv-01:
    external_port: eth0
    mgmt_bridge: br1
    mgmt_gw: 172.17.0.1
    mgmt_prefixlen: 24
testbed:
  docker-ptf:
    comment: Test ptf mathilda
    dut: sfd-lc0; sfd-lc1; sfd-01
    group-name: sonic_cisco
    ptf_image_name: docker-ptf-sfd
    ptf_ip: 192.168.122.66/24
    ptf_ipv6: fc0b::1/64
    ptf: docker-ptf
    server: server_1
    topo: t2_2lc_min_ports-masic
    vm_base: VM0100
    ansible:
      ansible_ssh_user: root
      ansible_host: 192.168.122.66/24
      ansible_hostv6: fc0b::1/64
      ansible_ssh_pass: root
    credentials:
      password: root
      username: root

testbed_config:
  alias: t22lcminvirtualswitchtopologyTestbed # does this value matter?
  name: testbed-t2-2lc-min-ports # does this value matter?
  type: Physical
topology:
  sfd-lc0:
    interfaces:
      Ethernet4:
        Bandwidth: 100000
        EndDevice: VM0100 # Are the vEOS switches automatically named in this format? If so, how?
        EndPort: Ethernet1
        VlanID: 0
        VlanMode: Access
      Ethernet5:
        Bandwidth: 100000
        EndDevice: VM0100
        EndPort: Ethernet2
        VlanID: 1
        VlanMode: Access
      Ethernet8:
        Bandwidth: 100000
        EndDevice: VM0101
        EndPort: Ethernet1
        VlanID: 2
        VlanMode: Access
      Ethernet25:
        Bandwidth: 100000
        EndDevice: VM0102
        EndPort: Ethernet1
        VlanID: 3
        VlanMode: Access
      Ethernet28:
        Bandwidth: 100000
        EndDevice: VM0102
        EndPort: Ethernet2
        VlanID: 4
        VlanMode: Access
      Ethernet23:
        Bandwidth: 100000
        EndDevice: VM0103
        EndPort: Ethernet1
        VlanID: 5
        VlanMode: Access
  sfd-lc1:
    interfaces:
      Ethernet2:
        Bandwidth: 100000
        EndDevice: VM0104 # Are the vEOS switches automatically named in this format? If so, how?
        EndPort: Ethernet1
        VlanID: 6
        VlanMode: Access
      Ethernet3:
        Bandwidth: 100000
        EndDevice: VM0104 # Are the vEOS switches automatically named in this format? If so, how?
        EndPort: Ethernet2
        VlanID: 7
        VlanMode: Access
      Ethernet6:
        Bandwidth: 100000
        EndDevice: VM0105
        EndPort: Ethernet1
        VlanID: 8
        VlanMode: Access
      Ethernet23:
        Bandwidth: 100000
        EndDevice: VM0106 # Are the vEOS switches automatically named in this format? If so, how?
        EndPort: Ethernet1
        VlanID: 9
        VlanMode: Access
      Ethernet25:
        Bandwidth: 100000
        EndDevice: VM0106 # Are the vEOS switches automatically named in this format? If so, how?
        EndPort: Ethernet2
        VlanID: 10
        VlanMode: Access
      Ethernet28:
        Bandwidth: 100000
        EndDevice: VM0107
        EndPort: Ethernet1
        VlanID: 11
        VlanMode: Access
veos:
  cd_image_filename: Aboot-veos-serial-8.0.0.iso
  credentials:
    password: 123456
    username: admin
  eos_ansible:
    ansible_password: 123456
    ansible_user: admin
  hdd_image_filename: vEOS-lab-4.20.15M.vmdk
  max_fp_num: 4
  memory: 2097152
  proxy_env:
    http_proxy: http://173.36.224.108:80
    https_proxy: http://173.36.224.108:80
  root_path: /home/azure/veos-vm
  skip_image_downloading: false
  vm_console_base: 7000
  vm_host_ansible:
    ansible_password: cisco123
    ansible_sudo_pass: cisco123
    ansible_user: vxr
  vm_images_url: https://acsbe.blob.core.windows.net/vmimages
  vm_host_1:
    STR-ACS-SERV-01:
      ansible_host: 192.168.122.150
  vms_1:
    VM0100:
      ansible_host: 192.168.122.100
    VM0101:
      ansible_host: 192.168.122.101
    VM0102:
      ansible_host: 192.168.122.102
    VM0103:
      ansible_host: 192.168.122.103
    VM0104:
      ansible_host: 192.168.122.104
    VM0105:
      ansible_host: 192.168.122.105
    VM0106:
      ansible_host: 192.168.122.106
    VM0107:
      ansible_host: 192.168.122.107
veos_groups:
  eos:
    children:
    - vms_1
  server_1:
    children:
    - vm_host_1
    - vms_1
    vars:
      host_var_file: host_vars/STR-ACS-SERV-01.yml
  servers:
    children:
    - server_1
    vars:
      topologies:
      - t1
      - t1-lag
      - t1-64-lag
      - t1-64-lag-clet
      - t0
      - t0-56
      - t0-52
      - ptf32
      - ptf64
      - t0-64
      - t0-64-32
      - t0-116
      - dualtor-56
      - t2-vs
      - t2_2lc_min_ports-masic
  vm_host:
    children:
    - vm_host_1
  vm_host_1:
    host:
    - STR-ACS-SERV-01
  vms_1:
    host:
    - VM0100
    - VM0101
    - VM0102
    - VM0103
    - VM0104
    - VM0105
    - VM0106
    - VM0107
