
slot1:
  ASIC0:
    topology:
      NEIGH_ASIC:
        ASIC0:
          asic_intfs:
          - Eth290-ASIC0
          - Eth292-ASIC0
          - Eth294-ASIC0
        ASIC1:
          asic_intfs:
          - Eth192-ASIC0
          - Eth286-ASIC0
          - Eth288-ASIC0
          - Eth302-ASIC0
        ASIC2:
          asic_intfs:
          - Eth268-ASIC0
          - Eth272-ASIC0
          - Eth274-ASIC0
        ASIC3:
          asic_intfs:
          - Eth270-ASIC0
          - Eth296-ASIC0
          - Eth298-ASIC0
          - Eth300-ASIC0
    configuration_properties:
      common:
        dut_asn: 65100
        asic_type: FrontEnd
    configuration:
      ASIC0:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.1.1/24
            - 2603:10e2:400:1::1/64
      ASIC1:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.2.1/24
            - 2603:10e2:400:2::1/64
      ASIC2:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.3.1/24
            - 2603:10e2:400:3::1/64
      ASIC3:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.4.1/24
            - 2603:10e2:400:4::1/64
  ASIC1:
    topology:
      NEIGH_ASIC:
        ASIC0:
          asic_intfs:
          - Eth288-ASIC1
          - Eth292-ASIC1
          - Eth294-ASIC1
        ASIC1:
          asic_intfs:
          - Eth192-ASIC1
          - Eth286-ASIC1
          - Eth290-ASIC1
          - Eth302-ASIC1
        ASIC2:
          asic_intfs:
          - Eth268-ASIC1
          - Eth272-ASIC1
          - Eth274-ASIC1
        ASIC3:
          asic_intfs:
          - Eth270-ASIC1
          - Eth296-ASIC1
          - Eth298-ASIC1
          - Eth300-ASIC1
    configuration_properties:
      common:
        dut_asn: 65100
        asic_type: FrontEnd
    configuration:
      ASIC0:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.1.2/24
            - 2603:10e2:400:1::2/64
      ASIC1:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.2.2/24
            - 2603:10e2:400:2::2/64
      ASIC2:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.3.2/24
            - 2603:10e2:400:3::2/64
      ASIC3:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.4.2/24
            - 2603:10e2:400:4::2/64
slot2:
  ASIC0:
    topology:
      NEIGH_ASIC:
        ASIC0:
          asic_intfs:
          - Eth290-ASIC0
          - Eth292-ASIC0
          - Eth294-ASIC0
        ASIC1:
          asic_intfs:
          - Eth192-ASIC0
          - Eth286-ASIC0
          - Eth288-ASIC0
          - Eth302-ASIC0
        ASIC2:
          asic_intfs:
          - Eth268-ASIC0
          - Eth272-ASIC0
          - Eth274-ASIC0
        ASIC3:
          asic_intfs:
          - Eth270-ASIC0
          - Eth296-ASIC0
          - Eth298-ASIC0
          - Eth300-ASIC0
    configuration_properties:
      common:
        dut_asn: 65100
        asic_type: FrontEnd
    configuration:
      ASIC0:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.1.3/24
            - 2603:10e2:400:1::3/64
      ASIC1:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.2.3/24
            - 2603:10e2:400:2::3/64
      ASIC2:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.3.3/24
            - 2603:10e2:400:3::3/64
      ASIC3:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.4.3/24
            - 2603:10e2:400:4::3/64
  ASIC1:
    topology:
      NEIGH_ASIC:
        ASIC0:
          asic_intfs:
          - Eth288-ASIC1
          - Eth292-ASIC1
          - Eth294-ASIC1
        ASIC1:
          asic_intfs:
          - Eth192-ASIC1
          - Eth286-ASIC1
          - Eth290-ASIC1
          - Eth302-ASIC1
        ASIC2:
          asic_intfs:
          - Eth268-ASIC1
          - Eth272-ASIC1
          - Eth274-ASIC1
        ASIC3:
          asic_intfs:
          - Eth270-ASIC1
          - Eth296-ASIC1
          - Eth298-ASIC1
          - Eth300-ASIC1
    configuration_properties:
      common:
        dut_asn: 65100
        asic_type: FrontEnd
    configuration:
      ASIC0:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.1.4/24
            - 2603:10e2:400:1::4/64
      ASIC1:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.2.4/24
            - 2603:10e2:400:2::4/64
      ASIC2:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.3.4/24
            - 2603:10e2:400:3::4/64
      ASIC3:
        bgp:
          asn: 65100
          peers:
            65100:
            - 20.0.4.4/24
            - 2603:10e2:400:4::4/64