################################################################################
#                         CICD test list - Ring3                               #
################################################################################
#
# This structure organizes a list of tests in two layers:
#     TEST_CATEGORY: Defines a subset of sonic-mgmt tests.
#     TOPOLOGY: Defines the type of topology in which the test is run.
#     PLATFORM: Defines the type of platform in which the test is run
#
# In other words, the hierarchy is:
#     TEST_CATEGORY -> TOPOLOGY -> PLATFORM -> [list of tests]
#
# TOPOLOGY section will always include a 'all_topo' key, which serves as a base. 
# PLATFORM section will always include a 'all_pids'
#
# Example:
# 
# example-ring3.yaml
#
# baseline:
#   all_topo:
#     all_pids:
#       - baseline/test/case_1.py
#       - baseline/test/case_2.py
#       - baseline/test/case_3.py
#       - baseline/test/case_4.py
#       - baseline/test/case_5.py
# FWD:
#   all_topo:
#     all_pids:
#     - fwd/test/case_1.py
#     - fwd/test/case_2.py
#     - fwd/test/case_3.py
#     - fwd/test/case_4.py
#     - fwd/test/case_5.py
#   t0-64:
#     all_pids:
#     - telemetry/test_telemetry.py::test_config_db_parameters
#     - example/t0/specific/fwd/test.py
# PLT:
#   all_topo:
#     all_pids:
#     - plt/test/case_1.py
#     - plt/test/case_2.py
#     - plt/test/case_3.py
#     - plt/test/case_4.py
#     - plt/test/case_5.py
#   t0-64:
#     all_pids:
#     - example/t0/specific/plt/test.py
#     - example/t0/specific/plt/test2.py
#   t1-64-lag:
#     all_pids:
#     - example/t1/specific/plt/test.py
#     - example/t1/specific/plt/test2.py
#
# How the test list is created
# - a list of TEST_CATEGORY is given(must have at least one)
# - For each TEST_CATEGORY:
#     - tests in TEST_CATEGORY/all_topo/all_pids are included
#     - if TOPOLOGY is specified, and TEST_CATEGORY/TOPOLOGY exists, tests in TEST_CATEGORY/TOPOLOGY/all_pids are included
#     - if TOPOLOGY and PLATFORM are specified, and TEST_CATEGORY/TOPOLOGY/PLATFORM exists, tests in TEST_CATEGORY/TOPOLOGY/PLATFORM are included
# - Any duplicate test entries are removed.
# - You now have your final test list!

baseline:
  all_topo:
    all_pids:
      - test_pretest.py
      - test_announce_routes.py
      - test_features.py
      - test_interfaces.py
      - bgp/test_bgp_fact.py
      - bgp/test_bgp_gr_helper.py
      - bgp/test_bgp_update_timer.py
      - bgp/test_bgpmon.py
      - arp/test_neighbor_mac_noptf.py
      - cacl/test_cacl_application.py
      - cacl/test_cacl_function.py
      - cacl/test_ebtables_application.py
      - route/test_route_perf.py
      - route/test_route_consistency.py
      - route/test_route_flap.py
      - test_procdockerstatsd.py
      - test_nbr_health.py
      - test_pre-test.py  
      - test_posttest.py  
  t0: &t0
    all_pids:
      - bgp/test_bgp_dual_asn.py
      - bgp/test_bgp_speaker.py
      - portstat/test_portstat.py
      - lldp/test_lldp.py
      - generic_config_updater/test_bgpl.py
      - generic_config_updater/test_incremental_qos.py
      - generic_config_updater/test_lo_interface.py
      - generic_config_updater/test_pfcwd_interval.py
      - generic_config_updater/test_portchannel_interface.py
      - generic_config_updater/test_syslog.py
      - generic_config_updater/test_vlan_interface.py
      - arp/test_arp_extended.py
      - arp/test_tagged_arp.py
      - fdb/test_fdb.py
      - fdb/test_fdb_flush.py
      - fdb/test_fdb_mac_expire.py
      - fdb/test_fdb_mac_move.py
      - log_fidelity/test_bgp_shutdown.py
      - memory_checker/test_memory_checker.py
      - ssh/test_ssh_ciphers.py
      - ssh/test_ssh_limit.py
      - override_config_table/test_override_config_table.py
      - snmp/test_snmp_cpu.py
      - snmp/test_snmp_default_route.py
      - snmp/test_snmp_memory.py
      - snmp/test_snmp_queue.py
      - snmp/test_snmp_v2mib.py
      #- snmp/test_snmp_fdb.py
      - route/test_static_route.py
      - route/test_duplicate_route.py
      - syslog/test_syslog.py
      - system_health/test_system_status.py
      - vxlan/test_vxlan_decap.py
      - pc/test_po_cleanup.py
      - pc/test_po_update.py
      - vlan/test_autostate_disabled.py
      - vlan/test_host_vlan.py
      #- vlan/test_vlan_ping.py
      - vlan/test_vlan.py
      - tests/test_posttest.py
      #- acl/custom_acl_table/test_custom_acl_table.py
  t0-64: *t0  
  t1: &t1
    all_pids:
      - bgp/test_bgp_allow_list.py
      - bgp/test_bgp_bbr.py
      - bgp/test_bgp_bounce.py
      - bgp/test_bgp_multipath_relax.py
      - bgp/test_bgp_session_flap.py
      - arp/test_arpall.py
      - route/test_duplicate_route.py
      - decap/test_decap.py
  t1-64-lag: *t1
  t2-min: *t0 #no specific test list for t2, need to come up with one

FWD:
  all_topo:
    all_pids:
      - route/test_default_route.py::test_default_ipv6_route_next_hop_global_address
      - route/test_default_route.py::test_ipv6_default_route_table_enabled_for_mgmt_interface
      - route/test_default_route.py::test_default_route_set_src
      - route/test_route_flap.py
  t0-64:
    all_pids:
      - route/test_default_route.py::test_default_route_with_bgp_flap
      - crm/test_crm.py::test_crm_neighbor
      - everflow/test_everflow_testbed.py::TestEverflowV4IngressAclIngressMirror::test_everflow_remove_unused_ecmp_next_hop
  
  t1-64-lag:
    all_pids:
      - route/test_default_route.py::test_default_route_with_bgp_flap
      - crm/test_crm.py::test_crm_neighbor
      - everflow/test_everflow_testbed.py::TestEverflowV4IngressAclIngressMirror::test_everflow_remove_unused_ecmp_next_hop

PLT:
  all_topo:
    all_pids:
      - platform_tests/api/test_chassis.py
      - platform_tests/api/test_component.py
      - platform_tests/test_cpu_memory_usage.py
      - platform_tests/test_port_toggle.py
      - platform_tests/test_power_budget_info.py
      - platform_tests/test_thermal_state_db.py
      - platform_tests/sfp/test_sfpshow.py
      - platform_tests/sfp/test_sfputil.py
      - platform_tests/test_thermal_state_db.py
      - platform_tests/api/test_module.py
      - platform_tests/api/test_sfp.py
      - platform_tests/api/test_thermal.py
      - platform_tests/cli/test_show_platform.py
      - platform_tests/daemon/test_ledd.py
      - platform_tests/daemon/test_pcied.py
      - platform_tests/daemon/test_psud.py
      - platform_tests/daemon/test_syseepromd.py
      - platform_tests/test_platform_info.py
      - platform_tests/test_reboot.py
      - platform_tests/test_reload_config.py

INFRA:
  all_topo:
    all_pids:
      - iface_namingmode/test_iface_namingmode.py
      - dhcp_relay/test_dhcp_relay.py
      - monit/test_monit_status.py
      - show_techsupport/test_auto_techsupport.py
      - system_health/test_system_health.py
      - cisco/platform_tests/test_serviceability_packet_capture.py
      - container_checker/test_container_checker.py
      - container_hardening/test_container_hardening.py
      - database/test_db_scripts.py
      - dhcp_relay/test_dhcp_pkt_fwd.py
      - generic_config_updater/test_monitor_config.py
      - process_monitoring/test_critical_process_monitoring.py
      - syslog/test_syslog_rate_limit.py

MGMT:
  all_topo:
    all_pids:
      #- generic_config_updater/test_aaa.py
      #- generic_config_updater/test_dhcp_relay.py
      - snmp/test_snmp_interfaces.py
      #- snmp/test_snmp_loopback.py
      #- snmp/test_snmp_lldp.py
      #- telemetry/test_telemetry.py
      - dns/static_dns/test_static_dns.py
      - generic_config_updater/test_ntp.py
      #- gnmi/test_gnmi.py
      #- gnmi/test_gnmi_configdb.py
      #- snmp/test_snmp_link_local.py
      #- tacacs/test_authorization.py
      #- tacacs/test_ro_disk.py
