---
- name: Create management bridge
  vnut_network:
    action: create_bridge
    bridge_name: "{{ vnut_mgmt_bridge }}"
    bridge_ip: "{{ vnut_mgmt_gateway }}/{{ vnut_mgmt_subnet | ipaddr('prefix') }}"
  register: bridge_result

- name: Display bridge creation result
  debug:
    var: bridge_result.msg
