# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from platforms.networking.sandcastle.public.proto import cmal_oper_cmds_pb2 as platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2
from platforms.networking.sandcastle.public.proto import mal_oper_pb2 as platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_mal__oper__pb2
from platforms.networking.sandcastle.public.proto import system_daemons_config_pb2 as platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2


class CmalOperCmdsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/Get',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_mal__oper__pb2.DataRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_mal__oper__pb2.DataResponse.FromString,
        )
    self.StartBERT = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/StartBERT',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartBERTRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartBERTResponse.FromString,
        )
    self.StopBERT = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/StopBERT',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StopBERTRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StopBERTResponse.FromString,
        )
    self.GetBERTStatus = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetBERTStatus',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetBERTStatusRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetBERTStatusResponse.FromString,
        )
    self.PrepareQualification = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/PrepareQualification',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.PrepareQualificationRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.PrepareQualificationResponse.FromString,
        )
    self.StartQualification = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/StartQualification',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartQualificationRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartQualificationResponse.FromString,
        )
    self.RetrieveQualificationResults = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/RetrieveQualificationResults',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.RetrieveQualificationResultsRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.RetrieveQualificationResultsResponse.FromString,
        )
    self.ExpireQualification = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/ExpireQualification',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ExpireQualificationRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ExpireQualificationResponse.FromString,
        )
    self.ListQualifications = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/ListQualifications',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ListQualificationsRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ListQualificationsResponse.FromString,
        )
    self.PSUCommand = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/PSUCommand',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.PSUCommandRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.PSUCommandResponse.FromString,
        )
    self.NSFOperation = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/NSFOperation',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.NSFOperationRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.NSFOperationResponse.FromString,
        )
    self.AutoReboot = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/AutoReboot',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.AutoRebootRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.AutoRebootResponse.FromString,
        )
    self.StateVerification = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/StateVerification',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StateVerificationRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StateVerificationResponse.FromString,
        )
    self.SFlowCommand = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/SFlowCommand',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.SFlowCommandRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.SFlowCommandResponse.FromString,
        )
    self.HardwareRulesGet = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/HardwareRulesGet',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.HardwareRulesGetRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.HardwareRulesGetResponse.FromString,
        )
    self.GetOpenflowFlowStats = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetOpenflowFlowStats',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetOpenflowFlowStatsRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetOpenflowFlowStatsResponse.FromString,
        )
    self.GetOpenflowGroupStats = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetOpenflowGroupStats',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetOpenflowGroupStatsRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetOpenflowGroupStatsResponse.FromString,
        )
    self.SetLoopback = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/SetLoopback',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.SetLoopbackRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.SetLoopbackResponse.FromString,
        )
    self.GetLoopback = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetLoopback',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetLoopbackRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetLoopbackResponse.FromString,
        )
    self.GenerateCsr = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GenerateCsr',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GenerateCsrRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GenerateCsrResponse.FromString,
        )
    self.SetMachineCreds = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/SetMachineCreds',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMachineCredsRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMachineCredsResponse.FromString,
        )
    self.SetPrincipalsList = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/SetPrincipalsList',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetPrincipalsListRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetPrincipalsListResponse.FromString,
        )
    self.SetCa = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/SetCa',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetCaRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetCaResponse.FromString,
        )
    self.SetMachineKeys = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/SetMachineKeys',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMachineKeysRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMachineKeysResponse.FromString,
        )
    self.SetMembership = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/SetMembership',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMembershipRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMembershipResponse.FromString,
        )
    self.GetMachineCreds = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetMachineCreds',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetMachineCredsRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetMachineCredsResponse.FromString,
        )
    self.GetPrincipalsList = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetPrincipalsList',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetPrincipalsListRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetPrincipalsListResponse.FromString,
        )
    self.GetCa = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetCa',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetCaRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetCaResponse.FromString,
        )
    self.GetMembership = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetMembership',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetMembershipRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetMembershipResponse.FromString,
        )
    self.GenerateKeypair = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GenerateKeypair',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GenerateKeypairRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GenerateKeypairResponse.FromString,
        )
    self.RotateMachineCert = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/RotateMachineCert',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateMachineCertRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateMachineCertResponse.FromString,
        )
    self.CheckCertInstall = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/CheckCertInstall',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.CheckCertInstallRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.CheckCertInstallResponse.FromString,
        )
    self.RotateThinMintKeys = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/RotateThinMintKeys',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateThinMintKeysRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateThinMintKeysResponse.FromString,
        )
    self.RotatePolicy = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/RotatePolicy',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotatePolicyRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotatePolicyResponse.FromString,
        )
    self.RotateCrl = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/RotateCrl',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateCrlRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateCrlResponse.FromString,
        )
    self.DisruptiveConfigCommit = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/DisruptiveConfigCommit',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.DisruptiveConfigCommitRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.DisruptiveConfigCommitResponse.FromString,
        )
    self.ConfigureBufferStatsCollection = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/ConfigureBufferStatsCollection',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ConfigureBufferStatsCollectionRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ConfigureBufferStatsCollectionResponse.FromString,
        )
    self.StartBufferStatsCollection = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/StartBufferStatsCollection',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartBufferStatsCollectionRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartBufferStatsCollectionResponse.FromString,
        )
    self.StopBufferStatsCollection = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/StopBufferStatsCollection',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StopBufferStatsCollectionRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StopBufferStatsCollectionResponse.FromString,
        )
    self.GetCollectedBufferStats = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetCollectedBufferStats',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetCollectedBufferStatsRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetCollectedBufferStatsResponse.FromString,
        )
    self.GetErrorStats = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetErrorStats',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ErrorStatsRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ErrorStatsResponse.FromString,
        )
    self.RevokeOverriddenLinkSpeed = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/RevokeOverriddenLinkSpeed',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.RevokeOverriddenLinkSpeedRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.RevokeOverriddenLinkSpeedResponse.FromString,
        )
    self.OpenflowRuleModRequestCollection = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/OpenflowRuleModRequestCollection',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.OpenflowRuleModRequestCollectionRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.OpenflowRuleModRequestCollectionResponse.FromString,
        )
    self.GetNodeAclProfiles = channel.unary_unary(
        '/google.sandcastle.stack.CmalOperCmdsService/GetNodeAclProfiles',
        request_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetNodeAclProfilesRequest.SerializeToString,
        response_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetNodeAclProfilesResponse.FromString,
        )


class CmalOperCmdsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartBERT(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopBERT(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBERTStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PrepareQualification(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartQualification(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RetrieveQualificationResults(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExpireQualification(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListQualifications(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PSUCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NSFOperation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AutoReboot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StateVerification(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SFlowCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HardwareRulesGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOpenflowFlowStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOpenflowGroupStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLoopback(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLoopback(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateCsr(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMachineCreds(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPrincipalsList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetCa(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMachineKeys(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMembership(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMachineCreds(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPrincipalsList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCa(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMembership(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateKeypair(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RotateMachineCert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckCertInstall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RotateThinMintKeys(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RotatePolicy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RotateCrl(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisruptiveConfigCommit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConfigureBufferStatsCollection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartBufferStatsCollection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopBufferStatsCollection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCollectedBufferStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetErrorStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RevokeOverriddenLinkSpeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenflowRuleModRequestCollection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNodeAclProfiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CmalOperCmdsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_mal__oper__pb2.DataRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_mal__oper__pb2.DataResponse.SerializeToString,
      ),
      'StartBERT': grpc.unary_unary_rpc_method_handler(
          servicer.StartBERT,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartBERTRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartBERTResponse.SerializeToString,
      ),
      'StopBERT': grpc.unary_unary_rpc_method_handler(
          servicer.StopBERT,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StopBERTRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StopBERTResponse.SerializeToString,
      ),
      'GetBERTStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetBERTStatus,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetBERTStatusRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetBERTStatusResponse.SerializeToString,
      ),
      'PrepareQualification': grpc.unary_unary_rpc_method_handler(
          servicer.PrepareQualification,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.PrepareQualificationRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.PrepareQualificationResponse.SerializeToString,
      ),
      'StartQualification': grpc.unary_unary_rpc_method_handler(
          servicer.StartQualification,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartQualificationRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartQualificationResponse.SerializeToString,
      ),
      'RetrieveQualificationResults': grpc.unary_unary_rpc_method_handler(
          servicer.RetrieveQualificationResults,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.RetrieveQualificationResultsRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.RetrieveQualificationResultsResponse.SerializeToString,
      ),
      'ExpireQualification': grpc.unary_unary_rpc_method_handler(
          servicer.ExpireQualification,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ExpireQualificationRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ExpireQualificationResponse.SerializeToString,
      ),
      'ListQualifications': grpc.unary_unary_rpc_method_handler(
          servicer.ListQualifications,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ListQualificationsRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ListQualificationsResponse.SerializeToString,
      ),
      'PSUCommand': grpc.unary_unary_rpc_method_handler(
          servicer.PSUCommand,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.PSUCommandRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.PSUCommandResponse.SerializeToString,
      ),
      'NSFOperation': grpc.unary_unary_rpc_method_handler(
          servicer.NSFOperation,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.NSFOperationRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.NSFOperationResponse.SerializeToString,
      ),
      'AutoReboot': grpc.unary_unary_rpc_method_handler(
          servicer.AutoReboot,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.AutoRebootRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.AutoRebootResponse.SerializeToString,
      ),
      'StateVerification': grpc.unary_unary_rpc_method_handler(
          servicer.StateVerification,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StateVerificationRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StateVerificationResponse.SerializeToString,
      ),
      'SFlowCommand': grpc.unary_unary_rpc_method_handler(
          servicer.SFlowCommand,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.SFlowCommandRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.SFlowCommandResponse.SerializeToString,
      ),
      'HardwareRulesGet': grpc.unary_unary_rpc_method_handler(
          servicer.HardwareRulesGet,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.HardwareRulesGetRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.HardwareRulesGetResponse.SerializeToString,
      ),
      'GetOpenflowFlowStats': grpc.unary_unary_rpc_method_handler(
          servicer.GetOpenflowFlowStats,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetOpenflowFlowStatsRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetOpenflowFlowStatsResponse.SerializeToString,
      ),
      'GetOpenflowGroupStats': grpc.unary_unary_rpc_method_handler(
          servicer.GetOpenflowGroupStats,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetOpenflowGroupStatsRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetOpenflowGroupStatsResponse.SerializeToString,
      ),
      'SetLoopback': grpc.unary_unary_rpc_method_handler(
          servicer.SetLoopback,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.SetLoopbackRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.SetLoopbackResponse.SerializeToString,
      ),
      'GetLoopback': grpc.unary_unary_rpc_method_handler(
          servicer.GetLoopback,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetLoopbackRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetLoopbackResponse.SerializeToString,
      ),
      'GenerateCsr': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateCsr,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GenerateCsrRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GenerateCsrResponse.SerializeToString,
      ),
      'SetMachineCreds': grpc.unary_unary_rpc_method_handler(
          servicer.SetMachineCreds,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMachineCredsRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMachineCredsResponse.SerializeToString,
      ),
      'SetPrincipalsList': grpc.unary_unary_rpc_method_handler(
          servicer.SetPrincipalsList,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetPrincipalsListRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetPrincipalsListResponse.SerializeToString,
      ),
      'SetCa': grpc.unary_unary_rpc_method_handler(
          servicer.SetCa,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetCaRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetCaResponse.SerializeToString,
      ),
      'SetMachineKeys': grpc.unary_unary_rpc_method_handler(
          servicer.SetMachineKeys,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMachineKeysRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMachineKeysResponse.SerializeToString,
      ),
      'SetMembership': grpc.unary_unary_rpc_method_handler(
          servicer.SetMembership,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMembershipRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.SetMembershipResponse.SerializeToString,
      ),
      'GetMachineCreds': grpc.unary_unary_rpc_method_handler(
          servicer.GetMachineCreds,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetMachineCredsRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetMachineCredsResponse.SerializeToString,
      ),
      'GetPrincipalsList': grpc.unary_unary_rpc_method_handler(
          servicer.GetPrincipalsList,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetPrincipalsListRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetPrincipalsListResponse.SerializeToString,
      ),
      'GetCa': grpc.unary_unary_rpc_method_handler(
          servicer.GetCa,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetCaRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetCaResponse.SerializeToString,
      ),
      'GetMembership': grpc.unary_unary_rpc_method_handler(
          servicer.GetMembership,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetMembershipRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GetMembershipResponse.SerializeToString,
      ),
      'GenerateKeypair': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateKeypair,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GenerateKeypairRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.GenerateKeypairResponse.SerializeToString,
      ),
      'RotateMachineCert': grpc.unary_unary_rpc_method_handler(
          servicer.RotateMachineCert,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateMachineCertRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateMachineCertResponse.SerializeToString,
      ),
      'CheckCertInstall': grpc.unary_unary_rpc_method_handler(
          servicer.CheckCertInstall,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.CheckCertInstallRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.CheckCertInstallResponse.SerializeToString,
      ),
      'RotateThinMintKeys': grpc.unary_unary_rpc_method_handler(
          servicer.RotateThinMintKeys,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateThinMintKeysRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateThinMintKeysResponse.SerializeToString,
      ),
      'RotatePolicy': grpc.unary_unary_rpc_method_handler(
          servicer.RotatePolicy,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotatePolicyRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotatePolicyResponse.SerializeToString,
      ),
      'RotateCrl': grpc.unary_unary_rpc_method_handler(
          servicer.RotateCrl,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateCrlRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_system__daemons__config__pb2.RotateCrlResponse.SerializeToString,
      ),
      'DisruptiveConfigCommit': grpc.unary_unary_rpc_method_handler(
          servicer.DisruptiveConfigCommit,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.DisruptiveConfigCommitRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.DisruptiveConfigCommitResponse.SerializeToString,
      ),
      'ConfigureBufferStatsCollection': grpc.unary_unary_rpc_method_handler(
          servicer.ConfigureBufferStatsCollection,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ConfigureBufferStatsCollectionRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ConfigureBufferStatsCollectionResponse.SerializeToString,
      ),
      'StartBufferStatsCollection': grpc.unary_unary_rpc_method_handler(
          servicer.StartBufferStatsCollection,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartBufferStatsCollectionRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StartBufferStatsCollectionResponse.SerializeToString,
      ),
      'StopBufferStatsCollection': grpc.unary_unary_rpc_method_handler(
          servicer.StopBufferStatsCollection,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StopBufferStatsCollectionRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.StopBufferStatsCollectionResponse.SerializeToString,
      ),
      'GetCollectedBufferStats': grpc.unary_unary_rpc_method_handler(
          servicer.GetCollectedBufferStats,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetCollectedBufferStatsRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetCollectedBufferStatsResponse.SerializeToString,
      ),
      'GetErrorStats': grpc.unary_unary_rpc_method_handler(
          servicer.GetErrorStats,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ErrorStatsRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.ErrorStatsResponse.SerializeToString,
      ),
      'RevokeOverriddenLinkSpeed': grpc.unary_unary_rpc_method_handler(
          servicer.RevokeOverriddenLinkSpeed,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.RevokeOverriddenLinkSpeedRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.RevokeOverriddenLinkSpeedResponse.SerializeToString,
      ),
      'OpenflowRuleModRequestCollection': grpc.unary_unary_rpc_method_handler(
          servicer.OpenflowRuleModRequestCollection,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.OpenflowRuleModRequestCollectionRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.OpenflowRuleModRequestCollectionResponse.SerializeToString,
      ),
      'GetNodeAclProfiles': grpc.unary_unary_rpc_method_handler(
          servicer.GetNodeAclProfiles,
          request_deserializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetNodeAclProfilesRequest.FromString,
          response_serializer=platforms_dot_networking_dot_sandcastle_dot_public_dot_proto_dot_cmal__oper__cmds__pb2.GetNodeAclProfilesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.sandcastle.stack.CmalOperCmdsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
