// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/report/report.proto

package report

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	gnmi "github.com/openconfig/gnmi/proto/gnmi"
	perf "github.com/openconfig/gnmitest/proto/perf"
	tests "github.com/openconfig/gnmitest/proto/tests"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CompletionStatus indicates the reason why the test ended.
type CompletionStatus int32

const (
	// Test finished with an unknown reason.
	CompletionStatus_UNKNOWN CompletionStatus = 0
	// Test successfully runs to completion.
	CompletionStatus_FINISHED CompletionStatus = 1
	// Test successfully runs to completion, but the completion is triggered by
	// test.
	CompletionStatus_EARLY_FINISHED CompletionStatus = 2
	// RPC request fails during test execution.
	CompletionStatus_RPC_ERROR CompletionStatus = 3
	// Test execution finished because of RPC request timeout.
	CompletionStatus_TIMEOUT CompletionStatus = 4
)

var CompletionStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "FINISHED",
	2: "EARLY_FINISHED",
	3: "RPC_ERROR",
	4: "TIMEOUT",
}

var CompletionStatus_value = map[string]int32{
	"UNKNOWN":        0,
	"FINISHED":       1,
	"EARLY_FINISHED": 2,
	"RPC_ERROR":      3,
	"TIMEOUT":        4,
}

func (x CompletionStatus) String() string {
	return proto.EnumName(CompletionStatus_name, int32(x))
}

func (CompletionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{0}
}

// Result of running an individual test.
type Status int32

const (
	// Indicates that test result is not set.
	Status_UNSET Status = 0
	// Indicates that test passes.
	Status_SUCCESS Status = 1
	// Indicates that test fails.
	Status_FAIL Status = 2
)

var Status_name = map[int32]string{
	0: "UNSET",
	1: "SUCCESS",
	2: "FAIL",
}

var Status_value = map[string]int32{
	"UNSET":   0,
	"SUCCESS": 1,
	"FAIL":    2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{1}
}

// MatchResult enumerates the outcome of a match comparison.
type MatchResult int32

const (
	MatchResult_MR_UNSET   MatchResult = 0
	MatchResult_MR_EQUAL   MatchResult = 1
	MatchResult_MR_UNEQUAL MatchResult = 2
)

var MatchResult_name = map[int32]string{
	0: "MR_UNSET",
	1: "MR_EQUAL",
	2: "MR_UNEQUAL",
}

var MatchResult_value = map[string]int32{
	"MR_UNSET":   0,
	"MR_EQUAL":   1,
	"MR_UNEQUAL": 2,
}

func (x MatchResult) String() string {
	return proto.EnumName(MatchResult_name, int32(x))
}

func (MatchResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{2}
}

// SubscribeResponseResult proto is used to pair a gnmi SubscribeResponse and
// the error returned from Process function of the test.
type SubscribeResponseResult struct {
	// gnmi SubscribeResponse received by the test.
	Response *gnmi.SubscribeResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// error returned by Process function of the test.
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponseResult) Reset()         { *m = SubscribeResponseResult{} }
func (m *SubscribeResponseResult) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponseResult) ProtoMessage()    {}
func (*SubscribeResponseResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{0}
}

func (m *SubscribeResponseResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponseResult.Unmarshal(m, b)
}
func (m *SubscribeResponseResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponseResult.Marshal(b, m, deterministic)
}
func (m *SubscribeResponseResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponseResult.Merge(m, src)
}
func (m *SubscribeResponseResult) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponseResult.Size(m)
}
func (m *SubscribeResponseResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponseResult.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponseResult proto.InternalMessageInfo

func (m *SubscribeResponseResult) GetResponse() *gnmi.SubscribeResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SubscribeResponseResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// TestError corresponds to a single error case reported during execution of a
// test. Test can emit multiple errors as a result of processing single
// SubscribeResponse message.
type TestError struct {
	// Message has human readable error that is set by the test.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// gnmi path corresponding to the message set. path is set by test as well.
	Path *gnmi.Path `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Additional details test can provide in the error.
	Details              *any.Any `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestError) Reset()         { *m = TestError{} }
func (m *TestError) String() string { return proto.CompactTextString(m) }
func (*TestError) ProtoMessage()    {}
func (*TestError) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{1}
}

func (m *TestError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestError.Unmarshal(m, b)
}
func (m *TestError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestError.Marshal(b, m, deterministic)
}
func (m *TestError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestError.Merge(m, src)
}
func (m *TestError) XXX_Size() int {
	return xxx_messageInfo_TestError.Size(m)
}
func (m *TestError) XXX_DiscardUnknown() {
	xxx_messageInfo_TestError.DiscardUnknown(m)
}

var xxx_messageInfo_TestError proto.InternalMessageInfo

func (m *TestError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TestError) GetPath() *gnmi.Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *TestError) GetDetails() *any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

// SubscribeTestResult is result of running an individual
// suite.SubscribeTest.
type SubscribeTestResult struct {
	// SubscribeResponse messages received as a result of subscription.
	Responses []*SubscribeResponseResult `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	// If test is stateful, error is set as a result of calling Check function of
	// the test. If test is stateless, error set here can be ignored.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Deprecated: Do not use.
	// CompletionStatus indicates why the test ended.
	Status CompletionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=report.CompletionStatus" json:"status,omitempty"`
	// List of errors received while running the test.
	Errors               []*TestError `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SubscribeTestResult) Reset()         { *m = SubscribeTestResult{} }
func (m *SubscribeTestResult) String() string { return proto.CompactTextString(m) }
func (*SubscribeTestResult) ProtoMessage()    {}
func (*SubscribeTestResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{2}
}

func (m *SubscribeTestResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeTestResult.Unmarshal(m, b)
}
func (m *SubscribeTestResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeTestResult.Marshal(b, m, deterministic)
}
func (m *SubscribeTestResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeTestResult.Merge(m, src)
}
func (m *SubscribeTestResult) XXX_Size() int {
	return xxx_messageInfo_SubscribeTestResult.Size(m)
}
func (m *SubscribeTestResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeTestResult.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeTestResult proto.InternalMessageInfo

func (m *SubscribeTestResult) GetResponses() []*SubscribeResponseResult {
	if m != nil {
		return m.Responses
	}
	return nil
}

// Deprecated: Do not use.
func (m *SubscribeTestResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SubscribeTestResult) GetStatus() CompletionStatus {
	if m != nil {
		return m.Status
	}
	return CompletionStatus_UNKNOWN
}

func (m *SubscribeTestResult) GetErrors() []*TestError {
	if m != nil {
		return m.Errors
	}
	return nil
}

// GetSetTestResult is the result of a GetSet test towards a target.
type GetSetTestResult struct {
	Test *tests.Test `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	// Result of running the test.
	Result Status `protobuf:"varint,2,opt,name=result,proto3,enum=report.Status" json:"result,omitempty"`
	// Result of the initialisation operation specified in the input test.
	InitialiseOper *GetSetOperResult `protobuf:"bytes,3,opt,name=initialise_oper,json=initialiseOper,proto3" json:"initialise_oper,omitempty"`
	// Result of the test operation specified in the input test.
	TestOper             *GetSetOperResult `protobuf:"bytes,4,opt,name=test_oper,json=testOper,proto3" json:"test_oper,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetSetTestResult) Reset()         { *m = GetSetTestResult{} }
func (m *GetSetTestResult) String() string { return proto.CompactTextString(m) }
func (*GetSetTestResult) ProtoMessage()    {}
func (*GetSetTestResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{3}
}

func (m *GetSetTestResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSetTestResult.Unmarshal(m, b)
}
func (m *GetSetTestResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSetTestResult.Marshal(b, m, deterministic)
}
func (m *GetSetTestResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSetTestResult.Merge(m, src)
}
func (m *GetSetTestResult) XXX_Size() int {
	return xxx_messageInfo_GetSetTestResult.Size(m)
}
func (m *GetSetTestResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSetTestResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetSetTestResult proto.InternalMessageInfo

func (m *GetSetTestResult) GetTest() *tests.Test {
	if m != nil {
		return m.Test
	}
	return nil
}

func (m *GetSetTestResult) GetResult() Status {
	if m != nil {
		return m.Result
	}
	return Status_UNSET
}

func (m *GetSetTestResult) GetInitialiseOper() *GetSetOperResult {
	if m != nil {
		return m.InitialiseOper
	}
	return nil
}

func (m *GetSetTestResult) GetTestOper() *GetSetOperResult {
	if m != nil {
		return m.TestOper
	}
	return nil
}

// GetSetOperResult is the result of an individual operation within the
// GetSetTest.
type GetSetOperResult struct {
	// Result of the operation.
	Result Status `protobuf:"varint,1,opt,name=result,proto3,enum=report.Status" json:"result,omitempty"`
	// set_responses is the SetResponse message received from the target.
	SetResponse *gnmi.SetResponse `protobuf:"bytes,2,opt,name=set_response,json=setResponse,proto3" json:"set_response,omitempty"`
	// set_status is the status.proto message received from the target in
	// response to the Set RPC within the operation.
	SetStatus *status.Status `protobuf:"bytes,3,opt,name=set_status,json=setStatus,proto3" json:"set_status,omitempty"`
	// get_response is the GetResponse received from the target.
	GetResponse *gnmi.GetResponse `protobuf:"bytes,4,opt,name=get_response,json=getResponse,proto3" json:"get_response,omitempty"`
	// get_status is the status.proto message received from the target in
	// response to the Get RPC within the operation.
	GetStatus *status.Status `protobuf:"bytes,5,opt,name=get_status,json=getStatus,proto3" json:"get_status,omitempty"`
	// get_response_matched indicates whether the GetResponse received from
	// the target matched that specified in the test.
	GetResponseMatched   MatchResult `protobuf:"varint,6,opt,name=get_response_matched,json=getResponseMatched,proto3,enum=report.MatchResult" json:"get_response_matched,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetSetOperResult) Reset()         { *m = GetSetOperResult{} }
func (m *GetSetOperResult) String() string { return proto.CompactTextString(m) }
func (*GetSetOperResult) ProtoMessage()    {}
func (*GetSetOperResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{4}
}

func (m *GetSetOperResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSetOperResult.Unmarshal(m, b)
}
func (m *GetSetOperResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSetOperResult.Marshal(b, m, deterministic)
}
func (m *GetSetOperResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSetOperResult.Merge(m, src)
}
func (m *GetSetOperResult) XXX_Size() int {
	return xxx_messageInfo_GetSetOperResult.Size(m)
}
func (m *GetSetOperResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSetOperResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetSetOperResult proto.InternalMessageInfo

func (m *GetSetOperResult) GetResult() Status {
	if m != nil {
		return m.Result
	}
	return Status_UNSET
}

func (m *GetSetOperResult) GetSetResponse() *gnmi.SetResponse {
	if m != nil {
		return m.SetResponse
	}
	return nil
}

func (m *GetSetOperResult) GetSetStatus() *status.Status {
	if m != nil {
		return m.SetStatus
	}
	return nil
}

func (m *GetSetOperResult) GetGetResponse() *gnmi.GetResponse {
	if m != nil {
		return m.GetResponse
	}
	return nil
}

func (m *GetSetOperResult) GetGetStatus() *status.Status {
	if m != nil {
		return m.GetStatus
	}
	return nil
}

func (m *GetSetOperResult) GetGetResponseMatched() MatchResult {
	if m != nil {
		return m.GetResponseMatched
	}
	return MatchResult_MR_UNSET
}

// Test is used to pair a tests.Test and its result.
type TestResult struct {
	Test *tests.Test `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	// Result of running the test.
	Result Status `protobuf:"varint,2,opt,name=result,proto3,enum=report.Status" json:"result,omitempty"`
	// Oneof field can be expanded to include results of other gnmi RPCs.
	//
	// Types that are valid to be assigned to Type:
	//	*TestResult_Subscribe
	//	*TestResult_Getset
	Type isTestResult_Type `protobuf_oneof:"type"`
	// Time taken by the operation mentioned in the input test
	OperTime             int64    `protobuf:"varint,12,opt,name=oper_time,json=operTime,proto3" json:"oper_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResult) Reset()         { *m = TestResult{} }
func (m *TestResult) String() string { return proto.CompactTextString(m) }
func (*TestResult) ProtoMessage()    {}
func (*TestResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{5}
}

func (m *TestResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResult.Unmarshal(m, b)
}
func (m *TestResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResult.Marshal(b, m, deterministic)
}
func (m *TestResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResult.Merge(m, src)
}
func (m *TestResult) XXX_Size() int {
	return xxx_messageInfo_TestResult.Size(m)
}
func (m *TestResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResult.DiscardUnknown(m)
}

var xxx_messageInfo_TestResult proto.InternalMessageInfo

func (m *TestResult) GetTest() *tests.Test {
	if m != nil {
		return m.Test
	}
	return nil
}

func (m *TestResult) GetResult() Status {
	if m != nil {
		return m.Result
	}
	return Status_UNSET
}

type isTestResult_Type interface {
	isTestResult_Type()
}

type TestResult_Subscribe struct {
	Subscribe *SubscribeTestResult `protobuf:"bytes,10,opt,name=subscribe,proto3,oneof"`
}

type TestResult_Getset struct {
	Getset *GetSetTestResult `protobuf:"bytes,11,opt,name=getset,proto3,oneof"`
}

func (*TestResult_Subscribe) isTestResult_Type() {}

func (*TestResult_Getset) isTestResult_Type() {}

func (m *TestResult) GetType() isTestResult_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *TestResult) GetSubscribe() *SubscribeTestResult {
	if x, ok := m.GetType().(*TestResult_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (m *TestResult) GetGetset() *GetSetTestResult {
	if x, ok := m.GetType().(*TestResult_Getset); ok {
		return x.Getset
	}
	return nil
}

func (m *TestResult) GetOperTime() int64 {
	if m != nil {
		return m.OperTime
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TestResult) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestResult_Subscribe)(nil),
		(*TestResult_Getset)(nil),
	}
}

// Instance stores test results of main test and its extensions.
type Instance struct {
	Description          string        `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Test                 *TestResult   `protobuf:"bytes,2,opt,name=test,proto3" json:"test,omitempty"`
	Extensions           []*TestResult `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{6}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Instance) GetTest() *TestResult {
	if m != nil {
		return m.Test
	}
	return nil
}

func (m *Instance) GetExtensions() []*TestResult {
	if m != nil {
		return m.Extensions
	}
	return nil
}

// InstanceGroup stores a set of Instances.
type InstanceGroup struct {
	Description string      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Instance    []*Instance `protobuf:"bytes,2,rep,name=instance,proto3" json:"instance,omitempty"`
	// Skipped indicates whether the instance group was skipped during
	// test execution based on a prior group being fatal.
	Skipped              bool     `protobuf:"varint,3,opt,name=skipped,proto3" json:"skipped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceGroup) Reset()         { *m = InstanceGroup{} }
func (m *InstanceGroup) String() string { return proto.CompactTextString(m) }
func (*InstanceGroup) ProtoMessage()    {}
func (*InstanceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{7}
}

func (m *InstanceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGroup.Unmarshal(m, b)
}
func (m *InstanceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGroup.Marshal(b, m, deterministic)
}
func (m *InstanceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGroup.Merge(m, src)
}
func (m *InstanceGroup) XXX_Size() int {
	return xxx_messageInfo_InstanceGroup.Size(m)
}
func (m *InstanceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGroup proto.InternalMessageInfo

func (m *InstanceGroup) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InstanceGroup) GetInstance() []*Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *InstanceGroup) GetSkipped() bool {
	if m != nil {
		return m.Skipped
	}
	return false
}

// Report is result of running suite.Suite
type Report struct {
	Results              []*InstanceGroup `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	PerfResults          *perf.Perf       `protobuf:"bytes,2,opt,name=perf_results,json=perfResults,proto3" json:"perf_results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_db08199be84e208e, []int{8}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetResults() []*InstanceGroup {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *Report) GetPerfResults() *perf.Perf {
	if m != nil {
		return m.PerfResults
	}
	return nil
}

func init() {
	proto.RegisterEnum("report.CompletionStatus", CompletionStatus_name, CompletionStatus_value)
	proto.RegisterEnum("report.Status", Status_name, Status_value)
	proto.RegisterEnum("report.MatchResult", MatchResult_name, MatchResult_value)
	proto.RegisterType((*SubscribeResponseResult)(nil), "report.SubscribeResponseResult")
	proto.RegisterType((*TestError)(nil), "report.TestError")
	proto.RegisterType((*SubscribeTestResult)(nil), "report.SubscribeTestResult")
	proto.RegisterType((*GetSetTestResult)(nil), "report.GetSetTestResult")
	proto.RegisterType((*GetSetOperResult)(nil), "report.GetSetOperResult")
	proto.RegisterType((*TestResult)(nil), "report.TestResult")
	proto.RegisterType((*Instance)(nil), "report.Instance")
	proto.RegisterType((*InstanceGroup)(nil), "report.InstanceGroup")
	proto.RegisterType((*Report)(nil), "report.Report")
}

func init() { proto.RegisterFile("proto/report/report.proto", fileDescriptor_db08199be84e208e) }

var fileDescriptor_db08199be84e208e = []byte{
	// 889 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x93, 0xd4, 0x8d, 0x8f, 0xbb, 0xc1, 0x3b, 0x5b, 0x54, 0xef, 0xae, 0xc4, 0x46, 0xbe,
	0x58, 0x95, 0x0a, 0x9c, 0x25, 0xbb, 0x20, 0x21, 0xc4, 0x45, 0xb6, 0x78, 0xbb, 0x11, 0x6d, 0x5a,
	0x26, 0x89, 0x10, 0x17, 0x28, 0x72, 0x92, 0x53, 0xc7, 0x22, 0xb1, 0x2d, 0xcf, 0x44, 0xa2, 0x6f,
	0xc0, 0xbb, 0x71, 0x89, 0x78, 0x0a, 0x5e, 0x02, 0xcd, 0x9f, 0xe3, 0xee, 0x52, 0xd8, 0x1b, 0x6e,
	0x6c, 0x9f, 0x39, 0xdf, 0x37, 0xdf, 0xf9, 0x9b, 0x31, 0x3c, 0x2e, 0xca, 0x9c, 0xe7, 0xbd, 0x12,
	0x8b, 0xbc, 0xe4, 0xfa, 0x15, 0xca, 0x35, 0x62, 0x2b, 0xeb, 0xc9, 0x8b, 0x24, 0xe5, 0xab, 0xed,
	0x3c, 0x5c, 0xe4, 0x9b, 0x5e, 0x5e, 0x60, 0xb6, 0xc8, 0xb3, 0x9b, 0x34, 0xe9, 0x25, 0xd9, 0x26,
	0xed, 0x29, 0xb6, 0xfc, 0x14, 0x0f, 0xc5, 0x7c, 0xf2, 0xd5, 0xfd, 0x0c, 0x8e, 0x8c, 0x6b, 0x96,
	0xf8, 0x64, 0xea, 0xa9, 0x79, 0xc7, 0x49, 0x9e, 0x27, 0x6b, 0xec, 0x95, 0xc5, 0xa2, 0xc7, 0x78,
	0xcc, 0xb7, 0xc6, 0xf1, 0x58, 0x3b, 0xa4, 0x35, 0xdf, 0xde, 0xf4, 0xe2, 0xec, 0x56, 0xbb, 0x5e,
	0x7d, 0x90, 0x56, 0x81, 0xe5, 0x8d, 0x7c, 0x28, 0x56, 0xb0, 0x84, 0xe3, 0xf1, 0x76, 0xce, 0x16,
	0x65, 0x3a, 0x47, 0x8a, 0xac, 0xc8, 0x33, 0x26, 0xde, 0xdb, 0x35, 0x27, 0x2f, 0xa1, 0x5d, 0xea,
	0x15, 0xdf, 0xea, 0x5a, 0x27, 0x6e, 0xff, 0x38, 0x94, 0xb9, 0xbd, 0x4f, 0xa8, 0x80, 0xe4, 0x08,
	0xf6, 0xb1, 0x2c, 0xf3, 0xd2, 0x6f, 0x74, 0xad, 0x13, 0x87, 0x2a, 0x23, 0xd8, 0x82, 0x33, 0x41,
	0xc6, 0x23, 0x61, 0x10, 0x1f, 0x0e, 0x36, 0xc8, 0x58, 0x9c, 0xa8, 0x6d, 0x1d, 0x6a, 0x4c, 0xf2,
	0x09, 0xb4, 0x8a, 0x98, 0xaf, 0x24, 0xd7, 0xed, 0x83, 0x52, 0xbb, 0x8e, 0xf9, 0x8a, 0xca, 0x75,
	0x12, 0xc2, 0xc1, 0x12, 0x79, 0x9c, 0xae, 0x99, 0xdf, 0x94, 0x90, 0xa3, 0x50, 0xd5, 0x23, 0x34,
	0xf5, 0x08, 0x07, 0xd9, 0x2d, 0x35, 0xa0, 0xe0, 0x77, 0x0b, 0x1e, 0x55, 0xc1, 0x8a, 0x00, 0x74,
	0x66, 0xdf, 0x82, 0x63, 0x02, 0x66, 0xbe, 0xd5, 0x6d, 0x9e, 0xb8, 0xfd, 0x67, 0xa1, 0x6e, 0xf9,
	0x3d, 0xd5, 0xa0, 0x3b, 0x06, 0xf1, 0xef, 0xe4, 0xf8, 0xba, 0xe1, 0x5b, 0x3a, 0x4f, 0xf2, 0x02,
	0x6c, 0xd5, 0x2e, 0x19, 0x5f, 0xa7, 0xef, 0x9b, 0x5d, 0xcf, 0xf2, 0x4d, 0xb1, 0x46, 0x9e, 0xe6,
	0xd9, 0x58, 0xfa, 0xa9, 0xc6, 0x91, 0x4f, 0xc1, 0x96, 0x54, 0xe6, 0xb7, 0x64, 0x1c, 0x0f, 0x0d,
	0xa3, 0xaa, 0x17, 0xd5, 0x80, 0xe0, 0x4f, 0x0b, 0xbc, 0x73, 0xe4, 0x63, 0xe4, 0xb5, 0x54, 0x9e,
	0x41, 0x4b, 0x74, 0x57, 0x37, 0xc8, 0x0d, 0xd5, 0x14, 0x49, 0x80, 0x74, 0x90, 0xe7, 0x60, 0x97,
	0x12, 0x2a, 0xa3, 0xed, 0xf4, 0x3b, 0x55, 0xa2, 0x3a, 0x10, 0xe5, 0x25, 0x03, 0xf8, 0x28, 0xcd,
	0x52, 0x9e, 0xc6, 0xeb, 0x94, 0xe1, 0x2c, 0x2f, 0xb0, 0xd4, 0x35, 0xae, 0x72, 0x50, 0xda, 0x57,
	0x05, 0x96, 0xba, 0x24, 0x9d, 0x1d, 0x41, 0xac, 0x92, 0x2f, 0xc1, 0x11, 0x92, 0x8a, 0xdc, 0xfa,
	0x0f, 0x72, 0x5b, 0x40, 0x85, 0x1d, 0xfc, 0xd1, 0x30, 0x79, 0xed, 0xdc, 0xb5, 0xb0, 0xad, 0x7f,
	0x0d, 0xfb, 0x15, 0x1c, 0x32, 0xe4, 0xb3, 0x6a, 0x50, 0xd5, 0xe8, 0x3c, 0xd4, 0x83, 0x8a, 0xbc,
	0xea, 0xa2, 0xcb, 0x76, 0x06, 0xf9, 0x02, 0x40, 0xb0, 0x6a, 0xbd, 0x72, 0xfb, 0xc4, 0xcc, 0x52,
	0x59, 0x2c, 0x8c, 0x8a, 0xc3, 0x90, 0xab, 0x4f, 0x21, 0x94, 0xd4, 0x85, 0x5a, 0x75, 0xa1, 0xf3,
	0xba, 0x50, 0x72, 0x57, 0x28, 0xd9, 0x09, 0xed, 0xdf, 0x2f, 0x94, 0x54, 0x42, 0x11, 0x1c, 0xd5,
	0x85, 0x66, 0x9b, 0x98, 0x2f, 0x56, 0xb8, 0xf4, 0x6d, 0x59, 0x87, 0x47, 0xa6, 0x0e, 0x97, 0x62,
	0x59, 0xd7, 0x92, 0xd4, 0x24, 0x2f, 0x15, 0x3c, 0xf8, 0xcb, 0x02, 0xf8, 0x3f, 0xe6, 0xe4, 0x1b,
	0x70, 0x98, 0x39, 0x22, 0x3e, 0xc8, 0xdd, 0x9e, 0xbe, 0x77, 0x76, 0x76, 0xc2, 0x6f, 0xf7, 0xe8,
	0x0e, 0x4f, 0xfa, 0x60, 0x27, 0xc8, 0x19, 0x72, 0xdf, 0xfd, 0xa7, 0xf1, 0xb8, 0x43, 0xd3, 0x48,
	0xf2, 0x14, 0x1c, 0x31, 0x50, 0x33, 0x9e, 0x6e, 0xd0, 0x3f, 0xec, 0x5a, 0x27, 0x4d, 0xda, 0x16,
	0x0b, 0x93, 0x74, 0x83, 0xaf, 0x6d, 0x68, 0xf1, 0xdb, 0x02, 0x83, 0xdf, 0x2c, 0x68, 0x0f, 0x33,
	0xc6, 0xe3, 0x6c, 0x81, 0xa4, 0x0b, 0xee, 0x12, 0x85, 0x62, 0x21, 0x0e, 0x9c, 0xbe, 0x64, 0xea,
	0x4b, 0xe4, 0xb9, 0xae, 0x46, 0x43, 0x37, 0xa4, 0x76, 0xe6, 0x74, 0x49, 0x55, 0x51, 0xfa, 0x00,
	0xf8, 0x2b, 0xc7, 0x8c, 0xa5, 0x79, 0x26, 0xe6, 0xa4, 0x79, 0x0f, 0xba, 0x86, 0x0a, 0x6e, 0xe1,
	0x81, 0x89, 0xe4, 0xbc, 0xcc, 0xb7, 0xc5, 0x07, 0x84, 0xf3, 0x19, 0xb4, 0x53, 0x4d, 0xf1, 0x1b,
	0x52, 0xc4, 0x33, 0x22, 0x66, 0x2b, 0x5a, 0x21, 0xc4, 0xfd, 0xc9, 0x7e, 0x49, 0x8b, 0x02, 0x97,
	0x72, 0x72, 0xdb, 0xd4, 0x98, 0xc1, 0x0a, 0x6c, 0x2a, 0x69, 0xa4, 0x07, 0x07, 0xaa, 0x5f, 0xe6,
	0x7e, 0xfb, 0xf8, 0xdd, 0x0d, 0x65, 0x6c, 0xd4, 0xa0, 0xc8, 0xe7, 0x70, 0x28, 0xfe, 0x0a, 0x33,
	0xc3, 0x32, 0x57, 0xb0, 0xfc, 0x55, 0x5c, 0x63, 0x79, 0x43, 0x5d, 0xf1, 0xa9, 0xf2, 0x65, 0xa7,
	0x3f, 0x83, 0xf7, 0xee, 0x95, 0x46, 0x5c, 0x38, 0x98, 0x8e, 0xbe, 0x1f, 0x5d, 0xfd, 0x38, 0xf2,
	0xf6, 0xc8, 0x21, 0xb4, 0xdf, 0x0c, 0x47, 0xc3, 0xf1, 0xdb, 0xe8, 0x3b, 0xcf, 0x22, 0x04, 0x3a,
	0xd1, 0x80, 0x5e, 0xfc, 0x34, 0xab, 0xd6, 0x1a, 0xe4, 0x01, 0x38, 0xf4, 0xfa, 0x6c, 0x16, 0x51,
	0x7a, 0x45, 0xbd, 0xa6, 0x60, 0x4f, 0x86, 0x97, 0xd1, 0xd5, 0x74, 0xe2, 0xb5, 0x4e, 0x4f, 0xc1,
	0xd6, 0x9b, 0x3a, 0xb0, 0x3f, 0x1d, 0x8d, 0xa3, 0x89, 0xb7, 0x27, 0x10, 0xe3, 0xe9, 0xd9, 0x59,
	0x34, 0x1e, 0x7b, 0x16, 0x69, 0x43, 0xeb, 0xcd, 0x60, 0x78, 0xe1, 0x35, 0x4e, 0xbf, 0x06, 0xb7,
	0x76, 0x16, 0x84, 0xf0, 0x25, 0x9d, 0x19, 0x8e, 0xb2, 0xa2, 0x1f, 0xa6, 0x83, 0x0b, 0xcf, 0x22,
	0x1d, 0x00, 0xe9, 0x53, 0x76, 0x63, 0x6e, 0xcb, 0xdf, 0xc6, 0xcb, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x82, 0x08, 0xe7, 0x5b, 0xfc, 0x07, 0x00, 0x00,
}
