// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/perf/perf.proto

package perf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/openconfig/gnmi/proto/gnmi"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Instances.
type Instance struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	ExecTime             int64    `protobuf:"varint,2,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3add00b2a762e50, []int{0}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Instance) GetExecTime() int64 {
	if m != nil {
		return m.ExecTime
	}
	return 0
}

// InstanceGroup stores a set of Instances.
type InstanceGroup struct {
	Iteration            int64       `protobuf:"varint,1,opt,name=iteration,proto3" json:"iteration,omitempty"`
	Description          string      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Instance             []*Instance `protobuf:"bytes,3,rep,name=instance,proto3" json:"instance,omitempty"`
	ExecTime             int64       `protobuf:"varint,4,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InstanceGroup) Reset()         { *m = InstanceGroup{} }
func (m *InstanceGroup) String() string { return proto.CompactTextString(m) }
func (*InstanceGroup) ProtoMessage()    {}
func (*InstanceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3add00b2a762e50, []int{1}
}

func (m *InstanceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceGroup.Unmarshal(m, b)
}
func (m *InstanceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceGroup.Marshal(b, m, deterministic)
}
func (m *InstanceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceGroup.Merge(m, src)
}
func (m *InstanceGroup) XXX_Size() int {
	return xxx_messageInfo_InstanceGroup.Size(m)
}
func (m *InstanceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceGroup proto.InternalMessageInfo

func (m *InstanceGroup) GetIteration() int64 {
	if m != nil {
		return m.Iteration
	}
	return 0
}

func (m *InstanceGroup) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InstanceGroup) GetInstance() []*Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *InstanceGroup) GetExecTime() int64 {
	if m != nil {
		return m.ExecTime
	}
	return 0
}

// Report is result of running suite.Suite
type Perf struct {
	Results              []*InstanceGroup `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ExecTime             int64            `protobuf:"varint,2,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	AvgTime              int64            `protobuf:"varint,3,opt,name=avg_time,json=avgTime,proto3" json:"avg_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Perf) Reset()         { *m = Perf{} }
func (m *Perf) String() string { return proto.CompactTextString(m) }
func (*Perf) ProtoMessage()    {}
func (*Perf) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3add00b2a762e50, []int{2}
}

func (m *Perf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Perf.Unmarshal(m, b)
}
func (m *Perf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Perf.Marshal(b, m, deterministic)
}
func (m *Perf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Perf.Merge(m, src)
}
func (m *Perf) XXX_Size() int {
	return xxx_messageInfo_Perf.Size(m)
}
func (m *Perf) XXX_DiscardUnknown() {
	xxx_messageInfo_Perf.DiscardUnknown(m)
}

var xxx_messageInfo_Perf proto.InternalMessageInfo

func (m *Perf) GetResults() []*InstanceGroup {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *Perf) GetExecTime() int64 {
	if m != nil {
		return m.ExecTime
	}
	return 0
}

func (m *Perf) GetAvgTime() int64 {
	if m != nil {
		return m.AvgTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Instance)(nil), "perf.Instance")
	proto.RegisterType((*InstanceGroup)(nil), "perf.InstanceGroup")
	proto.RegisterType((*Perf)(nil), "perf.Perf")
}

func init() { proto.RegisterFile("proto/perf/perf.proto", fileDescriptor_a3add00b2a762e50) }

var fileDescriptor_a3add00b2a762e50 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x25, 0x9b, 0xe2, 0xb6, 0xb3, 0xe8, 0x21, 0x22, 0xd4, 0x8f, 0x43, 0xd9, 0x53, 0x11, 0x6c,
	0x45, 0x7f, 0x84, 0xec, 0x4d, 0x82, 0x77, 0xe9, 0xc6, 0x69, 0x0c, 0x98, 0x0f, 0xd2, 0x74, 0xf1,
	0xa7, 0xf8, 0x73, 0xa5, 0xa9, 0x5d, 0xdd, 0x0a, 0x7b, 0x19, 0x26, 0xef, 0x65, 0xde, 0x7b, 0x33,
	0x70, 0xe1, 0xbc, 0x0d, 0xb6, 0x76, 0xe8, 0xdb, 0x58, 0xaa, 0xf8, 0x66, 0xc9, 0xd0, 0x5f, 0xdd,
	0x4b, 0x15, 0xde, 0xfb, 0x6d, 0x25, 0xac, 0xae, 0xad, 0x43, 0x23, 0xac, 0x69, 0x95, 0xac, 0xa5,
	0xd1, 0xaa, 0x1e, 0xe7, 0x62, 0x3b, 0x94, 0x71, 0x6e, 0xbd, 0x81, 0x74, 0x63, 0xba, 0xd0, 0x18,
	0x81, 0xac, 0x80, 0xd5, 0x1b, 0x76, 0xc2, 0x2b, 0x17, 0x94, 0x35, 0x39, 0x29, 0x48, 0x99, 0xf1,
	0xbf, 0x10, 0xbb, 0x86, 0x0c, 0x3f, 0x51, 0xbc, 0x06, 0xa5, 0x31, 0x5f, 0x14, 0xa4, 0xa4, 0x3c,
	0x1d, 0x80, 0x17, 0xa5, 0x71, 0xfd, 0x45, 0xe0, 0x74, 0xd2, 0x7a, 0xf2, 0xb6, 0x77, 0xec, 0x06,
	0x32, 0x15, 0xd0, 0x37, 0x7b, 0x39, 0xca, 0x7f, 0x81, 0xb9, 0xdd, 0xe2, 0xbf, 0xdd, 0x2d, 0xa4,
	0xea, 0x47, 0x30, 0xa7, 0x05, 0x2d, 0x57, 0x0f, 0x67, 0x55, 0xdc, 0x79, 0xb2, 0xe1, 0x7b, 0xfe,
	0x30, 0x5a, 0x32, 0x8b, 0xa6, 0x21, 0x79, 0x46, 0xdf, 0xb2, 0x3b, 0x58, 0x7a, 0xec, 0xfa, 0x8f,
	0xd0, 0xe5, 0x24, 0xea, 0x9d, 0x1f, 0xea, 0xc5, 0xd8, 0x7c, 0xfa, 0x73, 0x74, 0x5d, 0x76, 0x09,
	0x69, 0xb3, 0x93, 0x23, 0x47, 0x23, 0xb7, 0x6c, 0x76, 0x72, 0xa0, 0xb6, 0x27, 0xf1, 0xb6, 0x8f,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x37, 0x20, 0x7e, 0xf9, 0xac, 0x01, 0x00, 0x00,
}
