"""Test adding a T1 neighbor cluster to disaggregated T2 (dt2) single-ASIC SONiC via GCU.

This module tests the ability to add/configure a downstream T1 neighbor cluster on a
disaggregated T2 (dt2) device using GCU JSON patches. dt2 devices are single-ASIC
pizza box switches running in the T2 role, as opposed to multi-ASIC modular chassis.

Key differences from multi-ASIC (test_multiasic_addcluster.py):
- Single ASIC: no namespace handling, no '-n asicN' CLI args
- CONFIG_DB paths are flat (e.g., "/PORT/Ethernet0" not "/asic0/PORT/Ethernet0")
- No linecard concept — the DUT is the entire device
- Simpler topology discovery (no per-ASIC namespace iteration)

Key Design Notes:
-----------------
1. PORT ENTRIES ALWAYS EXIST: After `config load_minigraph`, all physical ports defined
   in platform.json exist in CONFIG_DB, regardless of device links. The test configures
   these existing ports rather than creating them from nothing.

2. ADMIN STATUS LIFECYCLE: When port interface definitions (PortChannels, IPInterfaces)
   are removed from minigraph, the affected ports revert to defaults from port_config.ini
   which sets admin_status=down. When GCU restores the configuration, admin_status
   transitions back to 'up'. This test verifies this lifecycle.

3. RFC 6902 "add" SEMANTICS: The generated patches use "add" operations which per RFC 6902
   mean "add or replace". For existing PORT entries, this replaces the platform-default
   config (e.g., 400G) with neighbor-specific config (e.g., 100G with FEC).

Limitations:
-----------
The patch is generated by diffing "config with T1" vs "config without T1". This
means the quality of the generated patch depends on MinigraphRefactor correctly
removing all T1 traces and `config load_minigraph` properly reverting port config
to platform defaults. A future improvement could use strict per-platform/topology
templates for deterministic patch content.

See test_dt2_addcluster_workflow() docstring for detailed explanation.
"""

import json
import logging
import os
import tempfile
import time
import uuid
import pytest

from tests.common.config_reload import config_reload
from tests.common.helpers.assertions import pytest_assert
from tests.common.gu_utils import apply_patch, generate_tmpfile, delete_tmpfile
from tests.common.gu_utils import create_checkpoint, delete_checkpoint
from tests.common.utilities import wait_until
from tests.generic_config_updater.util.generate_patch import (
    generate_config_patch,
    is_front_panel_port,
    extract_mirror_acl_ports,
    AUTOGEN_BUFFER_PG_PROFILE_PREFIX,
)
from tests.generic_config_updater.util.verify_patch import (
    compare_touched_entries,
    patch_touched_entries,
    patch_added_ports,
    patch_cable_length_ports,
    patch_pushed_lossless_pgs,
    get_config_db_field,
    config_db_key_exists,
    get_lossless_pg_entries,
    buffer_profile_exists,
    expected_lossless_profile_name,
)

from .util.process_minigraph import MinigraphRefactor

# dt2 addcluster tests target single-ASIC pizza box switches in the T2 role.
# Skip multi-ASIC and modular chassis platforms — those are covered by test_multiasic_addcluster.py.
pytestmark = [
    pytest.mark.topology('t2'),
    pytest.mark.disable_intf_up_check,
    pytest.mark.skip_config_db_check,
]

logger = logging.getLogger(__name__)

MINIGRAPH = "/etc/sonic/minigraph.xml"
MINIGRAPH_BACKUP = "/etc/sonic/minigraph.xml.backup"

# Loganalyzer ignore patterns for expected TRANSIENT errors during port reconfiguration.
LOGANALYZER_IGNORE_REGEX = [
    ".*doPortTask: Unsupported port .* speed.*",
    ".*createEntry: Failed to start PFC Watchdog on port.*",
    ".*Unable to find key NPU_SI_SETTINGS_SYNC_STATUS.*",
]


@pytest.fixture(autouse=True)
def ignore_expected_loganalyzer_errors(duthosts, loganalyzer):
    """Ignore expected transient errors during port reconfiguration."""
    if loganalyzer:
        for duthost in duthosts:
            if duthost.hostname in loganalyzer:
                loganalyzer[duthost.hostname].ignore_regex.extend(
                    LOGANALYZER_IGNORE_REGEX)
    yield


def get_downstream_t1_neighbor(duthost, mg_facts):
    """Get a downstream T1 neighbor from minigraph facts.

    For dt2 single-ASIC devices, T1 neighbors are downstream devices directly
    connected to the switch's front-panel ports.

    Args:
        duthost: DUT host object
        mg_facts: Minigraph facts dictionary

    Returns:
        str: T1 device name (e.g., 'ARISTA01T1'), or None if not found.
    """
    minigraph_devices = mg_facts.get('minigraph_devices', {})
    minigraph_neighbors = mg_facts.get('minigraph_neighbors', {})

    for neighbor_info in minigraph_neighbors.values():
        neighbor_name = neighbor_info.get('name')
        device_info = minigraph_devices.get(neighbor_name, {})
        if device_info.get('type') == 'LeafRouter':
            logger.info(f"Found downstream T1 neighbor: {neighbor_name}")
            return neighbor_name

    return None


def get_all_downstream_t1_neighbors(mg_facts):
    """Get all downstream T1 neighbors from minigraph facts.

    Args:
        mg_facts: Minigraph facts dictionary

    Returns:
        list: Sorted list of unique T1 device names.
    """
    minigraph_devices = mg_facts.get('minigraph_devices', {})
    minigraph_neighbors = mg_facts.get('minigraph_neighbors', {})

    t1_neighbors = set()
    for neighbor_info in minigraph_neighbors.values():
        neighbor_name = neighbor_info.get('name')
        device_info = minigraph_devices.get(neighbor_name, {})
        if device_info.get('type') == 'LeafRouter':
            t1_neighbors.add(neighbor_name)

    return sorted(t1_neighbors)


def get_interfaces_for_neighbor(mg_facts, neighbor_name):
    """Get the list of interfaces connected to a specific neighbor.

    Args:
        mg_facts: Minigraph facts dictionary
        neighbor_name: Name of the neighbor device

    Returns:
        list: List of interface names connected to the neighbor
    """
    minigraph_neighbors = mg_facts.get('minigraph_neighbors', {})
    interfaces = []
    for interface, neighbor_info in minigraph_neighbors.items():
        if neighbor_info.get('name') == neighbor_name:
            interfaces.append(interface)
    return interfaces


def get_mirror_acl_bindings(duthost):
    """Read MIRROR/MIRRORV6 ACL port bindings straight from CONFIG_DB.

    Reading CONFIG_DB avoids depending on the column layout of `show acl table`,
    which is presentation output and free to change between releases.

    Args:
        duthost: DUT host object

    Returns:
        set: Set of port/portchannel names bound to MIRROR or MIRRORV6 ACL tables
    """
    mirror_bindings = set()

    keys_result = duthost.shell('sonic-db-cli CONFIG_DB keys "ACL_TABLE|*"',
                                module_ignore_errors=True)
    if keys_result['rc'] != 0:
        return mirror_bindings

    for key in keys_result['stdout'].splitlines():
        key = key.strip()
        if not key:
            continue
        if get_config_db_field(duthost, key, 'type') not in ('MIRROR', 'MIRRORV6'):
            continue
        # CONFIG_DB stores list-valued fields under a trailing '@' as a comma-joined string.
        ports = get_config_db_field(duthost, key, 'ports@')
        if not ports:
            ports = get_config_db_field(duthost, key, 'ports')
        mirror_bindings.update(p.strip() for p in ports.split(',') if p.strip())

    return mirror_bindings


@pytest.fixture
def run_scratch(duthosts, rand_one_dut_hostname):
    """Per-run scratch space for config snapshots and the rewritten minigraph.

    Snapshot paths used to be scoped only by hostname and lived inside the test
    directory, so two runs against the same DUT overwrote each other's snapshots and
    the patch could be diffed against another run's config. Scoping by run keeps
    concurrent runs independent.

    The local directory is deliberately left on disk after the run — these snapshots
    are the primary triage artifact when a patch turns out wrong.

    Yields:
        tuple: (local_dir, dut_dir) scratch directories.
    """
    duthost = duthosts[rand_one_dut_hostname]
    run_id = uuid.uuid4().hex[:8]
    local_dir = tempfile.mkdtemp(prefix="dt2-addcluster-{}-".format(run_id))
    dut_dir = "/tmp/dt2-addcluster-{}".format(run_id)
    duthost.shell("mkdir -p {}".format(dut_dir))
    logger.info("Run scratch directories: local=%s dut=%s", local_dir, dut_dir)
    yield local_dir, dut_dir
    duthost.shell("rm -rf {}".format(dut_dir), module_ignore_errors=True)


@pytest.fixture(autouse=True)
def setup_env(duthosts, rand_one_dut_hostname):
    """Setup and teardown fixture for dt2 single-ASIC test.

    Teardown restores the original minigraph and reloads config.
    """
    duthost = duthosts[rand_one_dut_hostname]

    # Skip if multi-ASIC or modular chassis — those use test_multiasic_addcluster.py
    if duthost.is_multi_asic:
        pytest.skip("This test is for single-ASIC dt2 devices only; use test_multiasic_addcluster for multi-ASIC")
    if duthost.get_facts().get("modular_chassis"):
        pytest.skip("This test is for single-ASIC dt2 devices only; use test_multiasic_addcluster for modular chassis")

    create_checkpoint(duthost)
    yield
    try:
        if duthost.stat(path=MINIGRAPH_BACKUP)["stat"]["exists"]:
            logger.info(f"Restoring original minigraph from {MINIGRAPH_BACKUP}")
            duthost.shell(f"sudo cp {MINIGRAPH_BACKUP} {MINIGRAPH}")
            duthost.shell(f"sudo rm -f {MINIGRAPH_BACKUP}")

        logger.info("Reloading minigraph to restore original configuration")
        config_reload(duthost)
    finally:
        delete_checkpoint(duthost)


def test_dt2_addcluster_workflow(duthosts, rand_one_dut_hostname, loganalyzer, run_scratch):
    """Test adding a downstream T1 neighbor cluster via GCU on a dt2 single-ASIC device.

    This test validates that a T1 neighbor can be added to a single-ASIC disaggregated
    T2 (dt2) device using GCU JSON patches.

    Workflow:
    1. Discover a downstream T1 neighbor from minigraph
    2. Backup minigraph and reload it
    3. Capture full running config (with T1)
    4. Modify minigraph to remove target T1 neighbor
    5. Reload minigraph (now without T1)
    6. Capture running config without T1
    7. Generate GCU patch (diff between with-T1 and without-T1 configs)
    8. Apply patch to re-add the T1 cluster
    9. Verify: CONFIG_DB entries exist, ports configured, BGP neighbors present

    Args:
        duthosts: DUT hosts fixture
        rand_one_dut_hostname: Fixture providing a single random DUT hostname
        loganalyzer: Loganalyzer utility fixture
    """
    duthost = duthosts[rand_one_dut_hostname]
    local_dir, dut_dir = run_scratch

    # Platform skips live in setup_env so that a skipped run never reaches
    # create_checkpoint() and therefore never side-effects the DUT.

    # Cache minigraph facts
    mg_facts = duthost.minigraph_facts(host=duthost.hostname)['ansible_facts']

    # Discover a downstream T1 neighbor
    target_t1 = get_downstream_t1_neighbor(duthost, mg_facts)
    if not target_t1:
        pytest.skip("No downstream T1 neighbor found in minigraph")

    logger.info(f"Testing with downstream T1 neighbor: {target_t1} (single-ASIC dt2)")

    # Get interfaces connected to this neighbor
    neighbor_interfaces = get_interfaces_for_neighbor(mg_facts, target_t1)
    logger.info(f"Interfaces connected to {target_t1}: {neighbor_interfaces}")

    # Step 1: Backup minigraph
    logger.info(f"Backing up current minigraph from {MINIGRAPH} to {MINIGRAPH_BACKUP}")
    if not duthost.stat(path=MINIGRAPH)["stat"]["exists"]:
        pytest.fail(f"{MINIGRAPH} not found on DUT")
    duthost.shell(f"sudo cp {MINIGRAPH} {MINIGRAPH_BACKUP}")

    # Step 1.1: Reload minigraph to ensure clean state
    logger.info("Reloading minigraph using 'config load_minigraph -y'")
    duthost.shell("sudo config load_minigraph -y", module_ignore_errors=False)
    if not wait_until(300, 20, 0, duthost.critical_services_fully_started):
        pytest.fail("Critical services not fully started after minigraph reload")

    # Step 2: Capture full running configuration (with T1 neighbor)
    logger.info("Capturing full running configuration")
    dut_config_path = os.path.join(dut_dir, "all.json")
    full_config_path = os.path.join(local_dir, "dt2-all.json")
    os.makedirs(os.path.dirname(full_config_path), exist_ok=True)
    duthost.shell(f"show runningconfiguration all > {dut_config_path}")
    duthost.fetch(src=dut_config_path, dest=full_config_path, flat=True)
    logger.info(f"Saved full configuration backup to {full_config_path}")
    duthost.shell(f"rm -f {dut_config_path}")

    # Step 3: Modify minigraph to remove target T1 neighbor
    logger.info(f"Modifying minigraph to remove {target_t1}")
    local_minigraph = os.path.join(local_dir, "minigraph.xml")
    duthost.fetch(src=MINIGRAPH, dest=local_minigraph, flat=True)
    refactor = MinigraphRefactor(target_t1)
    success, affected_ports = refactor.process_minigraph(local_minigraph, local_minigraph)
    if not success:
        pytest.skip(f"Testbed topology does not match required conditions for {target_t1}")
    logger.info(f"Minigraph modification complete. Affected ports: {sorted(affected_ports)}")
    duthost.copy(src=local_minigraph, dest=MINIGRAPH)

    # Step 4: Reload minigraph (now without T1 neighbor)
    logger.info("Reloading minigraph using 'config load_minigraph -y' (without T1)")
    duthost.shell("sudo config load_minigraph -y", module_ignore_errors=False)
    if not wait_until(300, 20, 0, duthost.critical_services_fully_started):
        pytest.fail("Critical services not fully started after minigraph reload")

    # Verify affected ports have admin_status=down after minigraph reload.
    # This is the premise the whole diff-based approach rests on: removing the T1
    # from the minigraph must revert its ports to platform defaults. If it does not,
    # the "without T1" snapshot is wrong and so is every patch derived from it.
    if affected_ports:
        logger.info(f"Verifying admin_status=down for affected ports: {sorted(affected_ports)}")
        unexpected = {}
        for port in affected_ports:
            redis_cmd = f'sonic-db-cli CONFIG_DB hget "PORT|{port}" admin_status'
            result = duthost.shell(redis_cmd, module_ignore_errors=True)
            admin_status = result['stdout'].strip() if result['rc'] == 0 else "unknown"
            if admin_status != "down":
                unexpected[port] = admin_status
            else:
                logger.info(f"Verified port {port} has admin_status=down (as expected)")

        pytest_assert(
            not unexpected,
            "After removing {} from the minigraph and reloading, these ports did not revert "
            "to admin_status=down: {}. The baseline configuration is therefore not a clean "
            "'without T1' state, and any patch generated by diffing against it will be "
            "incorrect.".format(target_t1, unexpected))

    # Step 5: Capture running configuration without T1
    logger.info(f"Capturing running configuration without {target_t1}")
    dut_config_path = os.path.join(dut_dir, "all-without-t1.json")
    no_t1_config_path = os.path.join(local_dir, "dt2-all-without-t1.json")
    duthost.shell(f"show runningconfiguration all > {dut_config_path}")
    duthost.fetch(src=dut_config_path, dest=no_t1_config_path, flat=True)
    logger.info(f"Saved configuration without {target_t1} to {no_t1_config_path}")
    duthost.shell(f"rm -f {dut_config_path}")

    # Step 6: Generate GCU patch (diff between with-T1 and without-T1 configs)
    # For single-ASIC, the config structure is flat (no namespace nesting at top level)
    # generate_config_patch handles both single and multi-ASIC structures
    #
    # NOTE: The diff-based approach relies on MinigraphRefactor correctly removing all
    # T1 traces and `config load_minigraph` reverting ports to platform defaults.
    # If either is incomplete, the generated patch will be incomplete. A future
    # improvement is to use strict per-platform/topology patch templates instead.
    logger.info("Generating GCU patch")
    patch_file, = generate_config_patch(full_config_path, no_t1_config_path)

    # Step 7: Apply patch
    logger.info("Loading generated patch")
    with open(patch_file) as f:
        patch_data = json.load(f)

    # Extract items to verify from the patch.
    # Path parsing lives in patch_touched_entries so that this test and the
    # equivalence check below cannot disagree about what the patch touched.
    touched_entries = patch_touched_entries(patch_data)
    ports_to_check = set(touched_entries.get('PORT', ()))
    portchannels_to_check = set(touched_entries.get('PORTCHANNEL', ()))
    bgp_neighbors_to_check = set(touched_entries.get('BGP_NEIGHBOR', ()))
    config_entries_to_check = {
        table: {"{}|{}".format(table, key) for key in touched_entries.get(table, ())}
        for table in ('DEVICE_NEIGHBOR_METADATA', 'CABLE_LENGTH', 'PORT_QOS_MAP',
                      'PFC_WD', 'PORTCHANNEL_MEMBER', 'DEVICE_NEIGHBOR')
    }

    # Extract ACL-bound ports for verification.
    # Handles both whole-entry adds and per-port appends; see extract_mirror_acl_ports.
    acl_bound_ports = extract_mirror_acl_ports(patch_data, full_config_path)
    logger.info(f"Patch binds {len(acl_bound_ports)} port(s) to MIRROR ACL tables: "
                f"{sorted(acl_bound_ports)}")

    # The minigraph already told us which ports face this neighbor. Every one of them was
    # removed when the T1 was refactored out, so the add-cluster patch must bring all of
    # them back. Checking this catches a patch that is internally consistent but partial.
    missing_from_patch = set(neighbor_interfaces) - ports_to_check
    pytest_assert(
        not missing_from_patch,
        "Patch does not restore every port facing {}. Missing from the patch's PORT "
        "operations: {}. Minigraph reports these interfaces on the neighbor: {}. "
        "Patch touches: {}.".format(
            target_t1, sorted(missing_from_patch), sorted(neighbor_interfaces),
            sorted(ports_to_check)))

    # The lossless BUFFER_PG entries are never in the patch -- buffermgrd derives them
    # from PORT speed plus CABLE_LENGTH once the port is up. That makes speed,
    # CABLE_LENGTH and DEVICE_NEIGHBOR preconditions rather than incidental tables: if
    # the patch omits any of them for a port, no lossless PG is ever created and the port
    # silently runs without lossless buffers. Nothing else in this test would notice --
    # the patch applies, the port comes up, BGP establishes and the config compares equal.
    #
    # Scoped to ports the patch *adds*. A patch that only edits an existing port is not
    # required to restate cable length or neighbor, which the device already has; keeping
    # that distinction matters once the rework/idempotency scenarios are covered.
    patch_cable_lengths = patch_cable_length_ports(patch_data)
    patch_device_neighbors = set(touched_entries.get('DEVICE_NEIGHBOR', ()))
    added_ports = patch_added_ports(patch_data)
    front_panel_ports = {p for p in ports_to_check if is_front_panel_port(p)}
    added_front_panel_ports = {p for p in added_ports if is_front_panel_port(p)}

    # Guard against the checks below passing vacuously. This is an add-cluster patch, so
    # it must add front-panel ports; if it adds none, the three assertions that follow
    # would all be satisfied by an empty set and report nothing.
    pytest_assert(
        added_front_panel_ports,
        "Patch adds no front-panel PORT entries, so the cable-length, neighbor and speed "
        "preconditions below would pass without examining anything. Patch touches PORT "
        "entries: {}.".format(sorted(ports_to_check)))

    ports_missing_cable_length = added_front_panel_ports - set(patch_cable_lengths)
    pytest_assert(
        not ports_missing_cable_length,
        "Patch adds front-panel port(s) {} without a CABLE_LENGTH entry. buffermgrd needs "
        "PORT speed and CABLE_LENGTH to generate the lossless BUFFER_PG entries, so these "
        "ports would come up with no lossless buffers and no error reported. Patch sets "
        "cable lengths for: {}.".format(
            sorted(ports_missing_cable_length), sorted(patch_cable_lengths)))

    ports_missing_neighbor = added_front_panel_ports - patch_device_neighbors
    pytest_assert(
        not ports_missing_neighbor,
        "Patch adds front-panel port(s) {} without a DEVICE_NEIGHBOR entry. Patch sets "
        "neighbors for: {}.".format(
            sorted(ports_missing_neighbor), sorted(patch_device_neighbors)))

    # Speed is the other half of the lookup key. A PORT entry added without it yields no
    # pg_lossless_<speed>_<cable>_profile, exactly like a missing cable length would.
    ports_missing_speed = sorted(
        port for port in added_front_panel_ports if not added_ports[port].get('speed'))
    pytest_assert(
        not ports_missing_speed,
        "Patch adds front-panel port(s) {} without a 'speed' field. The lossless buffer "
        "profile is looked up by speed and cable length together, so a port added without "
        "a speed gets no lossless BUFFER_PG and no error.".format(ports_missing_speed))

    # The patch must not carry the lossless PGs itself. Pushing them would reference a
    # pg_lossless_<speed>_<cable>_profile that may not exist yet at apply time, and it
    # diverges from what NDM actually sends in production.
    pushed_lossless_pgs = patch_pushed_lossless_pgs(
        patch_data, AUTOGEN_BUFFER_PG_PROFILE_PREFIX)
    pytest_assert(
        not pushed_lossless_pgs,
        "Patch pushes auto-generated lossless BUFFER_PG entries: {}. These are created by "
        "buffermgrd on link-up and are absent from the NDM reference patch; including them "
        "references a buffer profile that may not exist yet.".format(pushed_lossless_pgs))

    logger.info("Patch supplies speed, CABLE_LENGTH and DEVICE_NEIGHBOR for all %d added "
                "front-panel port(s) and pushes no auto-generated lossless PGs",
                len(added_front_panel_ports))

    # Apply patch
    # Performance expectation: single T1 addition should complete within this budget.
    # We do NOT timeout the call — let it finish, then fail if it exceeded the budget.
    GCU_TIME_BUDGET_SECONDS = 60  # 1 minute for one T1 addition

    logger.info("Applying GCU patch (%d operations), time budget: %ds",
                len(patch_data), GCU_TIME_BUDGET_SECONDS)
    gcu_start = time.time()
    tmpfile = generate_tmpfile(duthost)
    try:
        apply_result = apply_patch(duthost, json_data=patch_data, dest_file=tmpfile)
        gcu_elapsed = time.time() - gcu_start
        if apply_result['rc'] != 0 or "Patch applied successfully" not in apply_result['stdout']:
            pytest.fail(f"Failed to apply patch after {gcu_elapsed:.1f}s: {apply_result['stdout']}")
        logger.info("Patch applied successfully in %.1fs (budget: %ds)",
                    gcu_elapsed, GCU_TIME_BUDGET_SECONDS)
    finally:
        delete_tmpfile(duthost, tmpfile)

    # Fail if GCU exceeded the time budget
    if gcu_elapsed > GCU_TIME_BUDGET_SECONDS:
        pytest.fail(
            f"GCU apply-patch took {gcu_elapsed:.1f}s, exceeded budget of "
            f"{GCU_TIME_BUDGET_SECONDS}s for single T1 addition"
        )

    # Step 8: Verification
    # -------------------------------------------------------------------------
    # Verify CONFIG_DB entries were correctly applied on the single-ASIC device.
    # No namespace args needed for single-ASIC.
    # -------------------------------------------------------------------------

    # Equivalence check, before any per-table checks.
    #
    # The test round-trips through a real minigraph reload precisely so that a
    # known-good "with T1" configuration is available. Comparing against it is the
    # only check that proves the patch reproduces that state; verifying that entries
    # merely exist would pass a patch carrying the wrong speed, MTU or BGP AS, or one
    # that clobbered an existing ACL binding.
    #
    # The comparison is scoped to the entries the patch touched, so unrelated
    # background churn in the running configuration cannot make this flaky.
    logger.info("Comparing patched configuration against the with-T1 baseline")
    after_patch_config_path = os.path.join(local_dir, "dt2-all-after-patch.json")
    dut_config_path = os.path.join(dut_dir, "all-after-patch.json")
    duthost.shell(f"show runningconfiguration all > {dut_config_path}")
    duthost.fetch(src=dut_config_path, dest=after_patch_config_path, flat=True)
    duthost.shell(f"rm -f {dut_config_path}")

    with open(full_config_path) as f:
        baseline_config = json.load(f)
    with open(after_patch_config_path) as f:
        after_patch_config = json.load(f)

    # Everything here -- the patch paths, patch_cable_length_ports(), and the CONFIG_DB
    # key "CABLE_LENGTH|AZURE" -- assumes CABLE_LENGTH holds exactly one profile named
    # AZURE, which Kumaresh confirmed is the case. Assert it rather than assume it, so a
    # device that ever carries a second profile fails here instead of silently skipping
    # the ports under it.
    baseline_cable_profiles = set(baseline_config.get('CABLE_LENGTH', {}))
    pytest_assert(
        baseline_cable_profiles == {'AZURE'},
        "Expected CABLE_LENGTH to contain exactly one profile named 'AZURE', found {}. "
        "Cable-length paths and lossless BUFFER_PG verification assume the single-AZURE "
        "layout; a different layout needs both updated.".format(sorted(baseline_cable_profiles)))

    differences = compare_touched_entries(baseline_config, after_patch_config, patch_data)
    pytest_assert(
        not differences,
        "Configuration after applying the patch does not match the baseline captured "
        "with {} present. The patch applied, but did not reproduce the intended state.\n"
        "{}".format(target_t1, "\n".join(differences)))
    logger.info("Patched configuration matches the with-T1 baseline for all %d touched entries",
                sum(len(keys) for keys in patch_touched_entries(patch_data).values()))

    # Verify port configuration
    if not ports_to_check:
        pytest.fail("No ports found in patch to verify")

    # front_panel_ports was computed before the patch was applied, when the
    # CABLE_LENGTH/DEVICE_NEIGHBOR preconditions were checked.
    skipped_ports = ports_to_check - front_panel_ports
    if skipped_ports:
        logger.info(f"Skipping internal/backplane ports: {sorted(skipped_ports)}")

    if not front_panel_ports:
        pytest.fail("No front-panel ports found in patch to verify")

    for port in front_panel_ports:
        logger.info(f"Verifying configuration for port {port}")
        pytest_assert(config_db_key_exists(duthost, f"PORT|{port}"),
                      f"Port {port} not found in CONFIG_DB after patch")
        admin_status = get_config_db_field(duthost, f"PORT|{port}", "admin_status")
        pytest_assert(admin_status == 'up',
                      f"Port {port} admin_status is '{admin_status}' in CONFIG_DB, expected 'up'")
        logger.info(f"Verified port {port} exists in CONFIG_DB with admin_status=up")

    # Verify MIRROR ACL bindings
    patch_has_acl_ops = any('/ACL_TABLE' in entry.get('path', '') for entry in patch_data)
    pytest_assert(not patch_has_acl_ops or acl_bound_ports,
                  "Patch contains ACL_TABLE operations but no MIRROR-bound ports were "
                  "extracted from it. The extraction is out of sync with the patch format, "
                  "which would silently skip ACL verification.")
    if acl_bound_ports:
        logger.info(f"Checking MIRROR ACL bindings for {len(acl_bound_ports)} ports")
        mirror_bindings = get_mirror_acl_bindings(duthost)
        for port in acl_bound_ports:
            pytest_assert(port in mirror_bindings,
                          f"Port {port} is not bound to any MIRROR ACL table. "
                          f"Current bindings: {sorted(mirror_bindings)}")
            logger.info(f"Verified port {port} is bound to MIRROR ACL table")

    # Verify PortChannel configuration
    if portchannels_to_check:
        for portchannel in portchannels_to_check:
            logger.info(f"Verifying PortChannel {portchannel}")
            pytest_assert(config_db_key_exists(duthost, f"PORTCHANNEL|{portchannel}"),
                          f"PortChannel {portchannel} not found in CONFIG_DB after patch")
            admin_status = get_config_db_field(duthost, f"PORTCHANNEL|{portchannel}", "admin_status")
            pytest_assert(admin_status == 'up',
                          f"PortChannel {portchannel} admin_status is '{admin_status}', expected 'up'")
            logger.info(f"Verified PortChannel {portchannel} in CONFIG_DB with admin_status=up")

    # Verify BGP neighbor configuration
    if bgp_neighbors_to_check:
        for neighbor in bgp_neighbors_to_check:
            logger.info(f"Verifying BGP neighbor {neighbor}")
            pytest_assert(config_db_key_exists(duthost, f"BGP_NEIGHBOR|{neighbor}"),
                          f"BGP neighbor {neighbor} not found in CONFIG_DB after patch")
            admin_status = get_config_db_field(duthost, f"BGP_NEIGHBOR|{neighbor}", "admin_status")
            pytest_assert(admin_status in ('', 'up'),
                          f"BGP neighbor {neighbor} admin_status is '{admin_status}', expected 'up'")
            logger.info(f"Verified BGP neighbor {neighbor} exists in CONFIG_DB")

    # Verify other CONFIG_DB entries
    for table, entries in config_entries_to_check.items():
        for entry in entries:
            pytest_assert(config_db_key_exists(duthost, entry),
                          f"Key {entry} missing or incorrect in CONFIG_DB")
            logger.info(f"Verified {entry} exists in CONFIG_DB")

    # Step 9: Verify interfaces come up (wait for convergence)
    logger.info("Waiting for interfaces to converge after patch application")
    if front_panel_ports:
        ports_not_up = {}

        def check_interfaces_up():
            ports_not_up.clear()
            for port in sorted(front_panel_ports):
                oper_status = duthost.shell(
                    f'sonic-db-cli APPL_DB hget "PORT_TABLE:{port}" oper_status',
                    module_ignore_errors=True)
                status = oper_status['stdout'].strip() if oper_status['rc'] == 0 else 'unknown'
                if status != 'up':
                    ports_not_up[port] = status
            return not ports_not_up

        pytest_assert(
            wait_until(300, 20, 0, check_interfaces_up),
            "Interfaces did not come up after the patch was applied: {}. These ports carried "
            "traffic to {} before it was removed from the minigraph, so they are expected to "
            "return to oper_status=up. If this testbed has no live peer on these links, the "
            "test should skip during setup rather than report success.".format(
                ports_not_up, target_t1))
        logger.info("All patched front-panel interfaces are operationally up")

        # Step 9b: the lossless BUFFER_PG entries the patch deliberately did not carry
        # must now exist, created by buffermgrd from PORT speed + CABLE_LENGTH on link-up.
        #
        # This is the check that closes the silent-failure gap. Up to this point a port
        # with a missing, zero, or unsupported cable length looks completely healthy:
        # apply returned rc=0, the port is up, BGP is established and the config matches
        # the baseline -- while the port carries no lossless buffers at all.
        logger.info("Verifying auto-generated lossless BUFFER_PG entries")

        # An absent cable length is a failure, not a skip. Only the explicit "0m"
        # sentinel means "this port intentionally has no lossless PG" -- treating a
        # missing entry the same way would skip exactly the port most likely to be broken.
        ports_without_cable_length = sorted(
            port for port in front_panel_ports
            if not get_config_db_field(duthost, "CABLE_LENGTH|AZURE", port))
        pytest_assert(
            not ports_without_cable_length,
            "Port(s) {} have no CABLE_LENGTH entry in CONFIG_DB after the patch applied. "
            "buffermgrd cannot generate their lossless BUFFER_PG entries without "
            "one.".format(ports_without_cable_length))

        # Derive the profile name each port should end up with, rather than accepting any
        # lossless profile. A port that came up with the profile for a different speed or
        # cable length has the wrong headroom, and checking only for "some lossless PG"
        # would pass it.
        expected_profiles = {}
        for port in sorted(front_panel_ports):
            cable_length = get_config_db_field(duthost, "CABLE_LENGTH|AZURE", port)
            if cable_length == '0m':
                # Legal, and deliberately not a failure -- but a T1-facing uplink with no
                # lossless buffers is worth seeing in the log, since "0m by mistake" and
                # "0m on purpose" look identical from here.
                logger.warning("Port %s has cable length 0m, so it gets no lossless "
                               "BUFFER_PG. Skipping its lossless buffer checks.", port)
                continue
            speed = get_config_db_field(duthost, "PORT|{}".format(port), 'speed')
            pytest_assert(
                speed,
                "Port {} has no 'speed' in CONFIG_DB after the patch applied, so no "
                "lossless buffer profile can be derived for it.".format(port))
            expected_profiles[port] = expected_lossless_profile_name(speed, cable_length)

        pytest_assert(
            expected_profiles,
            "No front-panel port has both a speed and a non-zero cable length, so the "
            "lossless BUFFER_PG checks below would verify nothing. Ports considered: "
            "{}.".format(sorted(front_panel_ports)))

        logger.info("Expecting lossless buffer profiles: %s", expected_profiles)

        ports_without_lossless_pg = {}

        def check_lossless_pgs_created():
            ports_without_lossless_pg.clear()
            for port, expected in sorted(expected_profiles.items()):
                found = get_lossless_pg_entries(
                    duthost, port, AUTOGEN_BUFFER_PG_PROFILE_PREFIX)
                if not found:
                    ports_without_lossless_pg[port] = "no lossless PG (expected {})".format(expected)
            return not ports_without_lossless_pg

        pytest_assert(
            wait_until(300, 20, 0, check_lossless_pgs_created),
            "Lossless BUFFER_PG entries were never created for port(s) {}. buffermgrd "
            "generates these from PORT speed and CABLE_LENGTH once the port is up; the patch "
            "intentionally does not carry them. Their absence means the port is forwarding "
            "without lossless buffers even though the patch applied cleanly and the port is "
            "up. Likely causes: CABLE_LENGTH missing or wrong for the port, or no "
            "pg_profile_lookup.ini row for this speed/cable-length pair.".format(
                ports_without_lossless_pg))

        # The PG must point at the profile derived from *this* port's speed and cable
        # length, and that profile must exist in CONFIG_DB and APPL_DB both. A PG
        # referencing a profile that never reached APPL_DB is config the dataplane never got.
        wrong_profile = {}
        profiles_missing = {}
        for port, expected in sorted(expected_profiles.items()):
            found = get_lossless_pg_entries(duthost, port, AUTOGEN_BUFFER_PG_PROFILE_PREFIX)
            for pg_key, profile in sorted(found.items()):
                if profile != expected:
                    wrong_profile[pg_key] = "{} (expected {})".format(profile, expected)
                    continue
                in_config_db, in_appl_db = buffer_profile_exists(duthost, profile)
                if not in_config_db or not in_appl_db:
                    profiles_missing[pg_key] = "{} (CONFIG_DB: {}, APPL_DB: {})".format(
                        profile,
                        "present" if in_config_db else "MISSING",
                        "present" if in_appl_db else "MISSING")

        pytest_assert(
            not wrong_profile,
            "Lossless BUFFER_PG entries reference a profile that does not match the port's "
            "speed and cable length: {}. The port has lossless buffers, but sized for a "
            "different link.".format(wrong_profile))

        pytest_assert(
            not profiles_missing,
            "Lossless BUFFER_PG entries reference buffer profiles that were not fully "
            "created: {}. The PG exists but its profile is missing from CONFIG_DB or never "
            "reached APPL_DB, so the dataplane has no headroom configured.".format(
                profiles_missing))

        logger.info("Lossless BUFFER_PG entries present and correctly sized for %d port(s)",
                    len(expected_profiles))

    # Step 10: Verify BGP sessions establish
    if bgp_neighbors_to_check:
        logger.info("Checking BGP session establishment")
        bgp_not_established = {}

        def check_bgp_established():
            bgp_not_established.clear()
            result = duthost.shell("vtysh -c 'show bgp summary json'", module_ignore_errors=True)
            if result['rc'] != 0 or not result['stdout'].strip():
                bgp_not_established['*'] = 'could not read bgp summary'
                return False
            try:
                bgp_summary = json.loads(result['stdout'])
            except (json.JSONDecodeError, KeyError):
                bgp_not_established['*'] = 'malformed bgp summary'
                return False

            peers = {}
            for af_key in ['ipv4Unicast', 'ipv6Unicast']:
                if af_key in bgp_summary:
                    peers.update(bgp_summary[af_key].get('peers', {}))

            for neighbor in sorted(bgp_neighbors_to_check):
                state = peers.get(neighbor, {}).get('state', 'not present')
                if state != 'Established':
                    bgp_not_established[neighbor] = state
            return not bgp_not_established

        pytest_assert(
            wait_until(180, 15, 0, check_bgp_established),
            "BGP sessions did not reach Established after the patch was applied: {}. These "
            "sessions were up before {} was removed from the minigraph. If this testbed has no "
            "live peer, the test should skip during setup rather than report success.".format(
                bgp_not_established, target_t1))
        logger.info("All patched BGP neighbors have established sessions")

    logger.info(f"dt2 addcluster test completed successfully for neighbor {target_t1}")


def test_dt2_addcluster_stress(duthosts, rand_one_dut_hostname, loganalyzer, run_scratch):
    """Stress test: add ALL T1 neighbors in a single GCU patch.

    Measures how many T1s can be added within a 1-hour window on a dt2 device.
    Generates one patch containing all T1 neighbors, applies it in a single call,
    and reports throughput metrics.

    The test does NOT timeout the GCU call — it lets it complete and then reports:
    - Total T1s in patch
    - Total patch operations
    - Wall-clock time for apply-patch
    - Time per T1 (avg)
    - Whether it fits within the 1-hour budget

    Args:
        duthosts: DUT hosts fixture
        rand_one_dut_hostname: Fixture providing a single random DUT hostname
        loganalyzer: Loganalyzer utility fixture
        run_scratch: Per-run local and DUT scratch directories
    """
    duthost = duthosts[rand_one_dut_hostname]
    local_dir, dut_dir = run_scratch

    if duthost.is_multi_asic:
        pytest.skip("This test is for single-ASIC dt2 devices only")
    if duthost.get_facts().get("modular_chassis"):
        pytest.skip("This test is for single-ASIC dt2 devices only")

    STRESS_TIME_BUDGET_SECONDS = 3600  # 1 hour

    mg_facts = duthost.minigraph_facts(host=duthost.hostname)['ansible_facts']
    all_t1s = get_all_downstream_t1_neighbors(mg_facts)
    if not all_t1s:
        pytest.skip("No downstream T1 neighbors found in minigraph")

    logger.info(f"Stress test: adding {len(all_t1s)} T1 neighbors in a single patch: {all_t1s}")

    # Step 1: Backup minigraph and reload for clean state
    if not duthost.stat(path=MINIGRAPH)["stat"]["exists"]:
        pytest.fail(f"{MINIGRAPH} not found on DUT")
    duthost.shell(f"sudo cp {MINIGRAPH} {MINIGRAPH_BACKUP}")

    logger.info("Reloading minigraph for clean state")
    duthost.shell("sudo config load_minigraph -y", module_ignore_errors=False)
    if not wait_until(300, 20, 0, duthost.critical_services_fully_started):
        pytest.fail("Critical services not fully started after minigraph reload")

    # Step 2: Capture full running config (with all T1s)
    dut_config_path = os.path.join(dut_dir, "stress-all.json")
    full_config_path = os.path.join(local_dir, "dt2-stress-all.json")
    os.makedirs(os.path.dirname(full_config_path), exist_ok=True)
    duthost.shell(f"show runningconfiguration all > {dut_config_path}")
    duthost.fetch(src=dut_config_path, dest=full_config_path, flat=True)
    duthost.shell(f"rm -f {dut_config_path}")

    # Step 3: Remove ALL T1 neighbors from minigraph
    local_minigraph = os.path.join(local_dir, "minigraph.xml")
    duthost.fetch(src=MINIGRAPH, dest=local_minigraph, flat=True)

    all_affected_ports = set()
    removed_t1s = []
    failed_t1s = []
    for t1_name in all_t1s:
        refactor = MinigraphRefactor(t1_name)
        success, affected_ports = refactor.process_minigraph(local_minigraph, local_minigraph)
        if not success:
            failed_t1s.append(t1_name)
            continue
        removed_t1s.append(t1_name)
        all_affected_ports.update(affected_ports)
        logger.info(f"Removed {t1_name} from minigraph (affected ports: {sorted(affected_ports)})")

    # A T1 that could not be removed stays in the minigraph, so it never appears in the
    # diff and never reaches the patch. Counting it would understate time per T1 and
    # overstate throughput, so the run is measured against what was actually removed.
    if failed_t1s:
        logger.warning("Could not remove %d of %d T1 neighbors from the minigraph: %s. "
                       "Stress metrics are reported for the remaining %d.",
                       len(failed_t1s), len(all_t1s), failed_t1s, len(removed_t1s))

    if not all_affected_ports:
        pytest.skip("Could not remove any T1 neighbors from minigraph")

    duthost.copy(src=local_minigraph, dest=MINIGRAPH)

    # Step 4: Reload minigraph without T1s
    logger.info("Reloading minigraph without T1 neighbors")
    duthost.shell("sudo config load_minigraph -y", module_ignore_errors=False)
    if not wait_until(300, 20, 0, duthost.critical_services_fully_started):
        pytest.fail("Critical services not fully started after minigraph reload")

    # Step 5: Capture running config without T1s
    dut_config_path = os.path.join(dut_dir, "stress-no-t1s.json")
    no_t1_config_path = os.path.join(local_dir, "dt2-stress-no-t1s.json")
    duthost.shell(f"show runningconfiguration all > {dut_config_path}")
    duthost.fetch(src=dut_config_path, dest=no_t1_config_path, flat=True)
    duthost.shell(f"rm -f {dut_config_path}")

    # Step 6: Generate single patch for ALL T1s
    #
    # NOTE: Same diff-based limitation as the single-T1 test applies here.
    # Patch quality depends on MinigraphRefactor removing all traces cleanly.
    logger.info("Generating single GCU patch for all T1 neighbors")
    patch_file, = generate_config_patch(full_config_path, no_t1_config_path)

    with open(patch_file) as f:
        patch_data = json.load(f)

    logger.info(f"Generated patch: {len(patch_data)} operations for {len(removed_t1s)} T1 neighbors")
    logger.info(f"Operations per T1 (avg): {len(patch_data) / len(removed_t1s):.1f}")

    # Step 7: Apply patch — let it run to completion, measure time
    logger.info("Applying stress patch (%d ops, %d T1s), timeout: %ds",
                len(patch_data), len(removed_t1s), STRESS_TIME_BUDGET_SECONDS)
    gcu_start = time.time()
    tmpfile = generate_tmpfile(duthost)
    try:
        patch_content = json.dumps(patch_data, indent=4)
        duthost.copy(content=patch_content, dest=tmpfile)

        # Run with 1-hour timeout (overrides default GCU timeout)
        cmds = f'config apply-patch {tmpfile}'
        pool, async_result = duthost.shell(cmds, module_ignore_errors=True,
                                           module_async=True)
        try:
            completed = wait_until(STRESS_TIME_BUDGET_SECONDS, 30, 0,
                                   lambda: async_result.ready())
            gcu_elapsed = time.time() - gcu_start

            if not completed:
                logger.error(
                    "Stress test: apply-patch did not complete within %ds, terminating",
                    STRESS_TIME_BUDGET_SECONDS
                )
                pytest.fail(
                    f"Stress test TIMEOUT: GCU apply-patch did not complete within "
                    f"{STRESS_TIME_BUDGET_SECONDS}s ({STRESS_TIME_BUDGET_SECONDS/3600:.0f}h) "
                    f"for {len(removed_t1s)} T1s ({len(patch_data)} ops)"
                )

            apply_result = async_result.get()
        finally:
            pool.terminate()
            pool.join()

        if apply_result['rc'] != 0 or "Patch applied successfully" not in apply_result['stdout']:
            pytest.fail(
                f"Failed to apply stress patch after {gcu_elapsed:.1f}s: {apply_result['stdout']}"
            )
    finally:
        delete_tmpfile(duthost, tmpfile)

    # Report results
    time_per_t1 = gcu_elapsed / len(removed_t1s)
    t1s_per_hour = 3600.0 / time_per_t1 if time_per_t1 > 0 else float('inf')

    logger.info("=" * 70)
    logger.info("STRESS TEST RESULTS")
    logger.info("=" * 70)
    logger.info(f"  T1 neighbors in patch:    {len(removed_t1s)}")
    logger.info(f"  Total patch operations:   {len(patch_data)}")
    logger.info(f"  Wall-clock time:          {gcu_elapsed:.1f}s")
    logger.info(f"  Time per T1 (avg):        {time_per_t1:.1f}s")
    logger.info(f"  Projected T1s per hour:   {t1s_per_hour:.0f}")
    logger.info(f"  Budget:                   {STRESS_TIME_BUDGET_SECONDS}s (1 hour)")
    logger.info(f"  Within budget:            {'YES' if gcu_elapsed <= STRESS_TIME_BUDGET_SECONDS else 'NO'}")
    logger.info("=" * 70)

    # Fail if exceeded budget
    if gcu_elapsed > STRESS_TIME_BUDGET_SECONDS:
        pytest.fail(
            f"Stress test: GCU apply-patch took {gcu_elapsed:.1f}s for {len(removed_t1s)} T1s, "
            f"exceeded 1-hour budget. Avg {time_per_t1:.1f}s/T1, "
            f"projected {t1s_per_hour:.0f} T1s/hour."
        )

    logger.info(
        f"Stress test PASSED: {len(removed_t1s)} T1s added in {gcu_elapsed:.1f}s "
        f"({time_per_t1:.1f}s/T1, projected {t1s_per_hour:.0f}/hour)"
    )
