"""Test adding a T1 neighbor cluster to disaggregated T2 (dt2) single-ASIC SONiC via GCU.

This module tests the ability to add/configure a downstream T1 neighbor cluster on a
disaggregated T2 (dt2) device using GCU JSON patches. dt2 devices are single-ASIC
pizza box switches running in the T2 role, as opposed to multi-ASIC modular chassis.

Key differences from multi-ASIC (test_multiasic_addcluster.py):
- Single ASIC: no namespace handling, no '-n asicN' CLI args
- CONFIG_DB paths are flat (e.g., "/PORT/Ethernet0" not "/asic0/PORT/Ethernet0")
- No linecard concept — the DUT is the entire device
- Simpler topology discovery (no per-ASIC namespace iteration)

Key Design Notes:
-----------------
1. PORT ENTRIES ALWAYS EXIST: After `config load_minigraph`, all physical ports defined
   in platform.json exist in CONFIG_DB, regardless of device links. The test configures
   these existing ports rather than creating them from nothing.

2. ADMIN STATUS LIFECYCLE: When port interface definitions (PortChannels, IPInterfaces)
   are removed from minigraph, the affected ports revert to defaults from port_config.ini
   which sets admin_status=down. When GCU restores the configuration, admin_status
   transitions back to 'up'. This test verifies this lifecycle.

3. RFC 6902 "add" SEMANTICS: The generated patches use "add" operations which per RFC 6902
   mean "add or replace". For existing PORT entries, this replaces the platform-default
   config (e.g., 400G) with neighbor-specific config (e.g., 100G with FEC).

Limitations:
-----------
The patch is generated by diffing "config with T1" vs "config without T1". This
means the quality of the generated patch depends on MinigraphRefactor correctly
removing all T1 traces and `config load_minigraph` properly reverting port config
to platform defaults. A future improvement could use strict per-platform/topology
templates for deterministic patch content.

See test_dt2_addcluster_workflow() docstring for detailed explanation.
"""

import json
import logging
import os
import shutil
import time
import pytest

from tests.common.config_reload import config_reload
from tests.common.helpers.assertions import pytest_assert
from tests.common.gu_utils import apply_patch, generate_tmpfile, delete_tmpfile
from tests.common.gu_utils import create_checkpoint, delete_checkpoint
from tests.common.plugins.loganalyzer.utils import support_ignore_loganalyzer
from tests.common.utilities import wait_until
from tests.generic_config_updater.util.generate_patch import generate_config_patch, is_front_panel_port

from .util.process_minigraph import MinigraphRefactor

# dt2 addcluster tests target single-ASIC pizza box switches in the T2 role.
# Skip multi-ASIC and modular chassis platforms — those are covered by test_multiasic_addcluster.py.
pytestmark = [
    pytest.mark.topology('t2'),
    pytest.mark.disable_intf_up_check,
    pytest.mark.skip_config_db_check,
]

logger = logging.getLogger(__name__)

MINIGRAPH = "/etc/sonic/minigraph.xml"
MINIGRAPH_BACKUP = "/etc/sonic/minigraph.xml.backup"
THIS_DIR = os.path.dirname(os.path.abspath(__file__))

# Loganalyzer ignore patterns for expected TRANSIENT errors during port reconfiguration.
LOGANALYZER_IGNORE_REGEX = [
    ".*doPortTask: Unsupported port .* speed.*",
    ".*createEntry: Failed to start PFC Watchdog on port.*",
    ".*Unable to find key NPU_SI_SETTINGS_SYNC_STATUS.*",
]


@support_ignore_loganalyzer
def apply_patch_with_log_ignore(duthost, json_data, dest_file):
    """Apply GCU patch with loganalyzer temporarily muted.

    YANG validation errors during GCU patch sorting are expected — GCU tries
    multiple orderings and intermediate states may fail validation. This wrapper
    mutes the loganalyzer during the GCU apply window.

    Args:
        duthost: Device Under Test (DUT)
        json_data: Source json patch to apply
        dest_file: Destination file on duthost

    Keyword Args (via decorator):
        ignore_loganalyzer: Dict mapping hostname to loganalyzer instance.

    Returns:
        dict: Result from apply_patch (shell output with rc, stdout, stderr)
    """
    return apply_patch(duthost, json_data=json_data, dest_file=dest_file)


@pytest.fixture(autouse=True)
def ignore_expected_loganalyzer_errors(duthosts, loganalyzer):
    """Ignore expected transient errors during port reconfiguration."""
    if loganalyzer:
        for duthost in duthosts:
            if duthost.hostname in loganalyzer:
                loganalyzer[duthost.hostname].ignore_regex.extend(
                    LOGANALYZER_IGNORE_REGEX)
    yield


def get_downstream_t1_neighbor(duthost, mg_facts):
    """Get a downstream T1 neighbor from minigraph facts.

    For dt2 single-ASIC devices, T1 neighbors are downstream devices directly
    connected to the switch's front-panel ports.

    Args:
        duthost: DUT host object
        mg_facts: Minigraph facts dictionary

    Returns:
        str: T1 device name (e.g., 'ARISTA01T1'), or None if not found.
    """
    minigraph_devices = mg_facts.get('minigraph_devices', {})
    minigraph_neighbors = mg_facts.get('minigraph_neighbors', {})

    for neighbor_info in minigraph_neighbors.values():
        neighbor_name = neighbor_info.get('name')
        device_info = minigraph_devices.get(neighbor_name, {})
        if device_info.get('type') == 'LeafRouter':
            logger.info(f"Found downstream T1 neighbor: {neighbor_name}")
            return neighbor_name

    return None


def get_all_downstream_t1_neighbors(mg_facts):
    """Get all downstream T1 neighbors from minigraph facts.

    Args:
        mg_facts: Minigraph facts dictionary

    Returns:
        list: Sorted list of unique T1 device names.
    """
    minigraph_devices = mg_facts.get('minigraph_devices', {})
    minigraph_neighbors = mg_facts.get('minigraph_neighbors', {})

    t1_neighbors = set()
    for neighbor_info in minigraph_neighbors.values():
        neighbor_name = neighbor_info.get('name')
        device_info = minigraph_devices.get(neighbor_name, {})
        if device_info.get('type') == 'LeafRouter':
            t1_neighbors.add(neighbor_name)

    return sorted(t1_neighbors)


def get_interfaces_for_neighbor(mg_facts, neighbor_name):
    """Get the list of interfaces connected to a specific neighbor.

    Args:
        mg_facts: Minigraph facts dictionary
        neighbor_name: Name of the neighbor device

    Returns:
        list: List of interface names connected to the neighbor
    """
    minigraph_neighbors = mg_facts.get('minigraph_neighbors', {})
    interfaces = []
    for interface, neighbor_info in minigraph_neighbors.items():
        if neighbor_info.get('name') == neighbor_name:
            interfaces.append(interface)
    return interfaces


def parse_mirror_acl_bindings(acl_table_output):
    """Parse 'show acl table' output to extract MIRROR/MIRRORV6 ACL bindings.

    Args:
        acl_table_output: String output from 'show acl table' command

    Returns:
        set: Set of port/portchannel names bound to MIRROR or MIRRORV6 ACL tables
    """
    current_table = None
    mirror_bindings = set()

    for line in acl_table_output.splitlines():
        if not line.strip() or '----' in line:
            continue

        if not line.startswith(' '):
            fields = [f for f in line.split() if f]
            if len(fields) >= 2 and fields[1] in ('MIRROR', 'MIRRORV6'):
                current_table = fields[0]
                if len(fields) >= 3:
                    mirror_bindings.add(fields[2])
            else:
                current_table = None
        elif current_table:
            port = line.strip()
            if port:
                mirror_bindings.add(port)

    return mirror_bindings


@pytest.fixture(autouse=True)
def setup_env(duthosts, rand_one_dut_hostname):
    """Setup and teardown fixture for dt2 single-ASIC test.

    Teardown restores the original minigraph and reloads config.
    """
    duthost = duthosts[rand_one_dut_hostname]

    # Skip if multi-ASIC or modular chassis — those use test_multiasic_addcluster.py
    if duthost.is_multi_asic:
        pytest.skip("This test is for single-ASIC dt2 devices only; use test_multiasic_addcluster for multi-ASIC")
    if duthost.get_facts().get("modular_chassis"):
        pytest.skip("This test is for single-ASIC dt2 devices only; use test_multiasic_addcluster for modular chassis")

    create_checkpoint(duthost)
    yield
    try:
        if duthost.stat(path=MINIGRAPH_BACKUP)["stat"]["exists"]:
            logger.info(f"Restoring original minigraph from {MINIGRAPH_BACKUP}")
            duthost.shell(f"sudo cp {MINIGRAPH_BACKUP} {MINIGRAPH}")
            duthost.shell(f"sudo rm -f {MINIGRAPH_BACKUP}")

        logger.info("Reloading minigraph to restore original configuration")
        config_reload(duthost)
    finally:
        delete_checkpoint(duthost)


def test_dt2_addcluster_workflow(duthosts, rand_one_dut_hostname, loganalyzer):
    """Test adding a downstream T1 neighbor cluster via GCU on a dt2 single-ASIC device.

    This test validates that a T1 neighbor can be added to a single-ASIC disaggregated
    T2 (dt2) device using GCU JSON patches.

    Workflow:
    1. Discover a downstream T1 neighbor from minigraph
    2. Backup minigraph and reload it
    3. Capture full running config (with T1)
    4. Modify minigraph to remove target T1 neighbor
    5. Reload minigraph (now without T1)
    6. Capture running config without T1
    7. Generate GCU patch (diff between with-T1 and without-T1 configs)
    8. Apply patch to re-add the T1 cluster
    9. Verify: CONFIG_DB entries exist, ports configured, BGP neighbors present

    Args:
        duthosts: DUT hosts fixture
        rand_one_dut_hostname: Fixture providing a single random DUT hostname
        loganalyzer: Loganalyzer utility fixture
    """
    duthost = duthosts[rand_one_dut_hostname]

    # Skip conditions (also checked in setup_env, but belt-and-suspenders)
    if duthost.is_multi_asic:
        pytest.skip("This test is for single-ASIC dt2 devices only")
    if duthost.get_facts().get("modular_chassis"):
        pytest.skip("This test is for single-ASIC dt2 devices only")

    # Cache minigraph facts
    mg_facts = duthost.minigraph_facts(host=duthost.hostname)['ansible_facts']

    # Discover a downstream T1 neighbor
    target_t1 = get_downstream_t1_neighbor(duthost, mg_facts)
    if not target_t1:
        pytest.skip("No downstream T1 neighbor found in minigraph")

    logger.info(f"Testing with downstream T1 neighbor: {target_t1} (single-ASIC dt2)")

    # Get interfaces connected to this neighbor
    neighbor_interfaces = get_interfaces_for_neighbor(mg_facts, target_t1)
    logger.info(f"Interfaces connected to {target_t1}: {neighbor_interfaces}")

    # Step 1: Backup minigraph
    logger.info(f"Backing up current minigraph from {MINIGRAPH} to {MINIGRAPH_BACKUP}")
    if not duthost.stat(path=MINIGRAPH)["stat"]["exists"]:
        pytest.fail(f"{MINIGRAPH} not found on DUT")
    duthost.shell(f"sudo cp {MINIGRAPH} {MINIGRAPH_BACKUP}")

    # Step 1.1: Reload minigraph to ensure clean state
    logger.info("Reloading minigraph using 'config load_minigraph -y'")
    duthost.shell("sudo config load_minigraph -y", module_ignore_errors=False)
    if not wait_until(300, 20, 0, duthost.critical_services_fully_started):
        pytest.fail("Critical services not fully started after minigraph reload")

    # Step 2: Capture full running configuration (with T1 neighbor)
    logger.info("Capturing full running configuration")
    dut_config_path = "/tmp/all.json"
    full_config_path = os.path.join(THIS_DIR, "backup", f"{duthost.hostname}-dt2-all.json")
    os.makedirs(os.path.dirname(full_config_path), exist_ok=True)
    duthost.shell(f"show runningconfiguration all > {dut_config_path}")
    duthost.fetch(src=dut_config_path, dest=full_config_path, flat=True)
    logger.info(f"Saved full configuration backup to {full_config_path}")
    duthost.shell(f"rm -f {dut_config_path}")

    # Step 3: Modify minigraph to remove target T1 neighbor
    logger.info(f"Modifying minigraph to remove {target_t1}")
    local_dir = "/tmp/minigraph_modified_dt2"
    local_minigraph = os.path.join(local_dir, f"{duthost.hostname}-minigraph.xml")
    os.makedirs(local_dir, exist_ok=True)
    duthost.fetch(src=MINIGRAPH, dest=local_minigraph, flat=True)
    refactor = MinigraphRefactor(target_t1)
    success, affected_ports = refactor.process_minigraph(local_minigraph, local_minigraph)
    if not success:
        pytest.skip(f"Testbed topology does not match required conditions for {target_t1}")
    logger.info(f"Minigraph modification complete. Affected ports: {sorted(affected_ports)}")
    duthost.copy(src=local_minigraph, dest=MINIGRAPH)

    # Step 4: Reload minigraph (now without T1 neighbor)
    logger.info("Reloading minigraph using 'config load_minigraph -y' (without T1)")
    duthost.shell("sudo config load_minigraph -y", module_ignore_errors=False)
    if not wait_until(300, 20, 0, duthost.critical_services_fully_started):
        pytest.fail("Critical services not fully started after minigraph reload")

    # Verify affected ports have admin_status=down after minigraph reload
    if affected_ports:
        logger.info(f"Verifying admin_status=down for affected ports: {sorted(affected_ports)}")
        for port in affected_ports:
            redis_cmd = f'sonic-db-cli CONFIG_DB hget "PORT|{port}" admin_status'
            result = duthost.shell(redis_cmd, module_ignore_errors=True)
            admin_status = result['stdout'].strip() if result['rc'] == 0 else "unknown"
            if admin_status != "down":
                logger.warning(f"Port {port} has admin_status={admin_status}, expected 'down'")
            else:
                logger.info(f"Verified port {port} has admin_status=down (as expected)")

    # Step 5: Capture running configuration without T1
    logger.info(f"Capturing running configuration without {target_t1}")
    dut_config_path = "/tmp/all-without-t1.json"
    no_t1_config_path = os.path.join(THIS_DIR, "backup", f"{duthost.hostname}-dt2-all-without-t1.json")
    duthost.shell(f"show runningconfiguration all > {dut_config_path}")
    duthost.fetch(src=dut_config_path, dest=no_t1_config_path, flat=True)
    logger.info(f"Saved configuration without {target_t1} to {no_t1_config_path}")
    duthost.shell(f"rm -f {dut_config_path}")

    # Step 6: Generate GCU patch (diff between with-T1 and without-T1 configs)
    # For single-ASIC, the config structure is flat (no namespace nesting at top level)
    # generate_config_patch handles both single and multi-ASIC structures
    #
    # NOTE: The diff-based approach relies on MinigraphRefactor correctly removing all
    # T1 traces and `config load_minigraph` reverting ports to platform defaults.
    # If either is incomplete, the generated patch will be incomplete. A future
    # improvement is to use strict per-platform/topology patch templates instead.
    logger.info("Generating GCU patch")
    patch_file = generate_config_patch(full_config_path, no_t1_config_path)

    # Step 7: Apply patch
    logger.info("Loading generated patch")
    with open(patch_file) as f:
        patch_data = json.load(f)

    # Extract items to verify from patches
    # For single-ASIC dt2, paths are flat: /TABLE/key (no namespace prefix)
    # However, generate_config_patch may use "" or "localhost" as the top-level key
    # for single-ASIC configs. We handle both cases.
    ports_to_check = set()
    portchannels_to_check = set()
    bgp_neighbors_to_check = set()
    config_entries_to_check = {
        'DEVICE_NEIGHBOR_METADATA': set(),
        'CABLE_LENGTH': set(),
        'PORT_QOS_MAP': set(),
        'PFC_WD': set(),
        'PORTCHANNEL_MEMBER': set(),
        'DEVICE_NEIGHBOR': set(),
    }

    for patch_entry in patch_data:
        path = patch_entry.get('path', '')
        parts = path.strip('/').split('/')

        # Determine table and key based on path structure
        # Single-ASIC: could be /TABLE/key or /localhost/TABLE/key or //TABLE/key
        if len(parts) >= 2:
            # Heuristic: if first part looks like a table name (uppercase), it's flat
            if parts[0].isupper() or parts[0] == '':
                # Flat path: /TABLE/key
                table = parts[0] if parts[0] else (parts[1] if len(parts) > 1 else '')
                key = parts[1] if parts[0] else (parts[2] if len(parts) > 2 else '')
            else:
                # Namespaced path: /namespace/TABLE/key (namespace could be 'localhost', '', etc.)
                table = parts[1] if len(parts) > 1 else ''
                key = parts[2] if len(parts) > 2 else ''

            if table == 'PORT' and key:
                ports_to_check.add(key)
            elif table == 'PORTCHANNEL' and key:
                portchannels_to_check.add(key)
            elif table == 'BGP_NEIGHBOR' and key:
                bgp_neighbors_to_check.add(key)
            elif table == 'PORTCHANNEL_MEMBER' and key:
                config_entries_to_check['PORTCHANNEL_MEMBER'].add(f"PORTCHANNEL_MEMBER|{key}")
            elif table == 'DEVICE_NEIGHBOR_METADATA' and key:
                config_entries_to_check['DEVICE_NEIGHBOR_METADATA'].add(f"DEVICE_NEIGHBOR_METADATA|{key}")
            elif table == 'DEVICE_NEIGHBOR' and key:
                config_entries_to_check['DEVICE_NEIGHBOR'].add(f"DEVICE_NEIGHBOR|{key}")
            elif table == 'PORT_QOS_MAP' and key:
                config_entries_to_check['PORT_QOS_MAP'].add(f"PORT_QOS_MAP|{key}")
            elif table == 'PFC_WD' and key:
                config_entries_to_check['PFC_WD'].add(f"PFC_WD|{key}")

    # Extract ACL-bound ports for verification
    acl_bound_ports = set()
    for patch_entry in patch_data:
        path = patch_entry.get('path', '')
        value = patch_entry.get('value', {})
        if isinstance(value, dict):
            acl_type = value.get('type', '')
            if acl_type in ('MIRROR', 'MIRRORV6'):
                ports_list = value.get('ports', [])
                if isinstance(ports_list, list):
                    for port in ports_list:
                        if is_front_panel_port(port):
                            acl_bound_ports.add(port)

    # Apply patch
    # Performance expectation: single T1 addition should complete within this budget.
    # We do NOT timeout the call — let it finish, then fail if it exceeded the budget.
    GCU_TIME_BUDGET_SECONDS = 60  # 1 minute for one T1 addition

    logger.info("Applying GCU patch (%d operations), time budget: %ds",
                len(patch_data), GCU_TIME_BUDGET_SECONDS)
    gcu_start = time.time()
    tmpfile = generate_tmpfile(duthost)
    try:
        apply_result = apply_patch_with_log_ignore(
            duthost, json_data=patch_data, dest_file=tmpfile,
            ignore_loganalyzer=loganalyzer
        )
        gcu_elapsed = time.time() - gcu_start
        if apply_result['rc'] != 0 or "Patch applied successfully" not in apply_result['stdout']:
            pytest.fail(f"Failed to apply patch after {gcu_elapsed:.1f}s: {apply_result['stdout']}")
        logger.info("Patch applied successfully in %.1fs (budget: %ds)",
                    gcu_elapsed, GCU_TIME_BUDGET_SECONDS)
    finally:
        delete_tmpfile(duthost, tmpfile)

    # Fail if GCU exceeded the time budget
    if gcu_elapsed > GCU_TIME_BUDGET_SECONDS:
        pytest.fail(
            f"GCU apply-patch took {gcu_elapsed:.1f}s, exceeded budget of "
            f"{GCU_TIME_BUDGET_SECONDS}s for single T1 addition"
        )

    # Step 8: Verification
    # -------------------------------------------------------------------------
    # Verify CONFIG_DB entries were correctly applied on the single-ASIC device.
    # No namespace args needed for single-ASIC.
    # -------------------------------------------------------------------------

    # Verify port configuration
    if not ports_to_check:
        pytest.fail("No ports found in patch to verify")

    front_panel_ports = {p for p in ports_to_check if is_front_panel_port(p)}
    skipped_ports = ports_to_check - front_panel_ports
    if skipped_ports:
        logger.info(f"Skipping internal/backplane ports: {sorted(skipped_ports)}")

    if not front_panel_ports:
        pytest.fail("No front-panel ports found in patch to verify")

    for port in front_panel_ports:
        logger.info(f"Verifying configuration for port {port}")
        redis_cmd = f'sonic-db-cli CONFIG_DB hgetall "PORT|{port}"'
        redis_output = duthost.shell(redis_cmd, module_ignore_errors=False)['stdout']
        pytest_assert(redis_output.strip(), f"Port {port} not found in CONFIG_DB after patch")
        pytest_assert("'admin_status'" in redis_output and "'up'" in redis_output,
                      f"Port {port} admin_status is not 'up' in CONFIG_DB. Got: {redis_output}")
        logger.info(f"Verified port {port} exists in CONFIG_DB with admin_status=up")

    # Verify MIRROR ACL bindings
    if acl_bound_ports:
        logger.info(f"Checking MIRROR ACL bindings for {len(acl_bound_ports)} ports")
        result = duthost.shell("show acl table", module_ignore_errors=False)["stdout"]
        mirror_bindings = parse_mirror_acl_bindings(result)
        for port in acl_bound_ports:
            pytest_assert(port in mirror_bindings,
                          f"Port {port} is not bound to any MIRROR ACL table. "
                          f"Current bindings: {sorted(mirror_bindings)}")
            logger.info(f"Verified port {port} is bound to MIRROR ACL table")

    # Verify PortChannel configuration
    if portchannels_to_check:
        for portchannel in portchannels_to_check:
            logger.info(f"Verifying PortChannel {portchannel}")
            redis_cmd = f'sonic-db-cli CONFIG_DB hgetall "PORTCHANNEL|{portchannel}"'
            redis_output = duthost.shell(redis_cmd, module_ignore_errors=False)['stdout']
            pytest_assert(redis_output.strip(),
                          f"PortChannel {portchannel} not found in CONFIG_DB after patch")
            pytest_assert("'admin_status'" in redis_output and "'up'" in redis_output,
                          f"PortChannel {portchannel} admin_status is not 'up'. Got: {redis_output}")
            logger.info(f"Verified PortChannel {portchannel} in CONFIG_DB with admin_status=up")

    # Verify BGP neighbor configuration
    if bgp_neighbors_to_check:
        for neighbor in bgp_neighbors_to_check:
            logger.info(f"Verifying BGP neighbor {neighbor}")
            redis_cmd = f'sonic-db-cli CONFIG_DB hgetall "BGP_NEIGHBOR|{neighbor}"'
            redis_output = duthost.shell(redis_cmd, module_ignore_errors=False)['stdout']
            pytest_assert(redis_output.strip(),
                          f"BGP neighbor {neighbor} not found in CONFIG_DB after patch")
            if "'admin_status'" in redis_output:
                pytest_assert("'up'" in redis_output,
                              f"BGP neighbor {neighbor} admin_status is not 'up'. Got: {redis_output}")
            logger.info(f"Verified BGP neighbor {neighbor} exists in CONFIG_DB")

    # Verify other CONFIG_DB entries
    for table, entries in config_entries_to_check.items():
        for entry in entries:
            if table == 'CABLE_LENGTH':
                redis_cmd = 'sonic-db-cli CONFIG_DB hgetall "CABLE_LENGTH|AZURE"'
                redis_output = duthost.shell(redis_cmd, module_ignore_errors=False)['stdout']
                pytest_assert(entry in redis_output,
                              f"Key {entry} missing in CABLE_LENGTH. Got: {redis_output}")
            else:
                redis_cmd = f'sonic-db-cli CONFIG_DB keys "{entry}"'
                redis_value = duthost.shell(redis_cmd, module_ignore_errors=False)['stdout'].strip()
                pytest_assert(redis_value == entry,
                              f"Key {entry} missing or incorrect in CONFIG_DB. Got: {redis_value}")
            logger.info(f"Verified {entry} exists in CONFIG_DB")

    # Step 9: Verify interfaces come up (wait for convergence)
    logger.info("Waiting for interfaces to converge after patch application")
    if front_panel_ports:
        def check_interfaces_up():
            result = duthost.shell("show interfaces status", module_ignore_errors=False)
            for line in result['stdout'].splitlines():
                fields = line.split()
                if len(fields) >= 9 and fields[0] in front_panel_ports:
                    # Look for oper status field
                    for i, field in enumerate(fields):
                        if field.lower() in ('up', 'down') and i >= 7:
                            if field.lower() != 'up':
                                return False
                            break
            return True

        if not wait_until(300, 20, 0, check_interfaces_up):
            # Don't fail — oper status depends on peer availability
            logger.warning("Some interfaces did not come up within timeout (peer may be unavailable)")
        else:
            logger.info("All patched front-panel interfaces are operationally up")

    # Step 10: Verify BGP sessions establish
    if bgp_neighbors_to_check:
        logger.info("Checking BGP session establishment")

        def check_bgp_established():
            result = duthost.shell("vtysh -c 'show bgp summary json'", module_ignore_errors=True)
            if result['rc'] != 0 or not result['stdout'].strip():
                return False
            try:
                bgp_summary = json.loads(result['stdout'])
                for af_key in ['ipv4Unicast', 'ipv6Unicast']:
                    if af_key in bgp_summary:
                        peers = bgp_summary[af_key].get('peers', {})
                        for neighbor in bgp_neighbors_to_check:
                            if neighbor in peers:
                                state = peers[neighbor].get('state', '')
                                if state != 'Established':
                                    return False
                return True
            except (json.JSONDecodeError, KeyError):
                return False

        if not wait_until(180, 15, 0, check_bgp_established):
            # Don't fail — BGP establishment depends on peer availability
            logger.warning("Some BGP sessions did not establish within timeout (peer may be unavailable)")
        else:
            logger.info("All patched BGP neighbors have established sessions")

    logger.info(f"dt2 addcluster test completed successfully for neighbor {target_t1}")


def test_dt2_addcluster_stress(duthosts, rand_one_dut_hostname, loganalyzer):
    """Stress test: add ALL T1 neighbors in a single GCU patch.

    Measures how many T1s can be added within a 1-hour window on a dt2 device.
    Generates one patch containing all T1 neighbors, applies it in a single call,
    and reports throughput metrics.

    The test does NOT timeout the GCU call — it lets it complete and then reports:
    - Total T1s in patch
    - Total patch operations
    - Wall-clock time for apply-patch
    - Time per T1 (avg)
    - Whether it fits within the 1-hour budget

    Args:
        duthosts: DUT hosts fixture
        rand_one_dut_hostname: Fixture providing a single random DUT hostname
        loganalyzer: Loganalyzer utility fixture
    """
    duthost = duthosts[rand_one_dut_hostname]

    if duthost.is_multi_asic:
        pytest.skip("This test is for single-ASIC dt2 devices only")
    if duthost.get_facts().get("modular_chassis"):
        pytest.skip("This test is for single-ASIC dt2 devices only")

    STRESS_TIME_BUDGET_SECONDS = 3600  # 1 hour

    mg_facts = duthost.minigraph_facts(host=duthost.hostname)['ansible_facts']
    all_t1s = get_all_downstream_t1_neighbors(mg_facts)
    if not all_t1s:
        pytest.skip("No downstream T1 neighbors found in minigraph")

    logger.info(f"Stress test: adding {len(all_t1s)} T1 neighbors in a single patch: {all_t1s}")

    # Step 1: Backup minigraph and reload for clean state
    if not duthost.stat(path=MINIGRAPH)["stat"]["exists"]:
        pytest.fail(f"{MINIGRAPH} not found on DUT")
    duthost.shell(f"sudo cp {MINIGRAPH} {MINIGRAPH_BACKUP}")

    logger.info("Reloading minigraph for clean state")
    duthost.shell("sudo config load_minigraph -y", module_ignore_errors=False)
    if not wait_until(300, 20, 0, duthost.critical_services_fully_started):
        pytest.fail("Critical services not fully started after minigraph reload")

    # Step 2: Capture full running config (with all T1s)
    dut_config_path = "/tmp/stress-all.json"
    full_config_path = os.path.join(THIS_DIR, "backup", f"{duthost.hostname}-dt2-stress-all.json")
    os.makedirs(os.path.dirname(full_config_path), exist_ok=True)
    duthost.shell(f"show runningconfiguration all > {dut_config_path}")
    duthost.fetch(src=dut_config_path, dest=full_config_path, flat=True)
    duthost.shell(f"rm -f {dut_config_path}")

    # Step 3: Remove ALL T1 neighbors from minigraph
    local_dir = "/tmp/minigraph_stress_dt2"
    local_minigraph = os.path.join(local_dir, f"{duthost.hostname}-minigraph.xml")
    os.makedirs(local_dir, exist_ok=True)
    duthost.fetch(src=MINIGRAPH, dest=local_minigraph, flat=True)

    all_affected_ports = set()
    for t1_name in all_t1s:
        refactor = MinigraphRefactor(t1_name)
        success, affected_ports = refactor.process_minigraph(local_minigraph, local_minigraph)
        if not success:
            logger.warning(f"Failed to remove {t1_name} from minigraph, skipping")
            continue
        all_affected_ports.update(affected_ports)
        logger.info(f"Removed {t1_name} from minigraph (affected ports: {sorted(affected_ports)})")

    if not all_affected_ports:
        pytest.skip("Could not remove any T1 neighbors from minigraph")

    duthost.copy(src=local_minigraph, dest=MINIGRAPH)

    # Step 4: Reload minigraph without T1s
    logger.info("Reloading minigraph without T1 neighbors")
    duthost.shell("sudo config load_minigraph -y", module_ignore_errors=False)
    if not wait_until(300, 20, 0, duthost.critical_services_fully_started):
        pytest.fail("Critical services not fully started after minigraph reload")

    # Step 5: Capture running config without T1s
    dut_config_path = "/tmp/stress-no-t1s.json"
    no_t1_config_path = os.path.join(THIS_DIR, "backup", f"{duthost.hostname}-dt2-stress-no-t1s.json")
    duthost.shell(f"show runningconfiguration all > {dut_config_path}")
    duthost.fetch(src=dut_config_path, dest=no_t1_config_path, flat=True)
    duthost.shell(f"rm -f {dut_config_path}")

    # Step 6: Generate single patch for ALL T1s
    #
    # NOTE: Same diff-based limitation as the single-T1 test applies here.
    # Patch quality depends on MinigraphRefactor removing all traces cleanly.
    logger.info("Generating single GCU patch for all T1 neighbors")
    patch_file = generate_config_patch(full_config_path, no_t1_config_path)

    with open(patch_file) as f:
        patch_data = json.load(f)

    logger.info(f"Generated patch: {len(patch_data)} operations for {len(all_t1s)} T1 neighbors")
    logger.info(f"Operations per T1 (avg): {len(patch_data) / len(all_t1s):.1f}")

    # Step 7: Apply patch — let it run to completion, measure time
    logger.info("Applying stress patch (%d ops, %d T1s), timeout: %ds",
                len(patch_data), len(all_t1s), STRESS_TIME_BUDGET_SECONDS)
    gcu_start = time.time()
    tmpfile = generate_tmpfile(duthost)
    try:
        patch_content = json.dumps(patch_data, indent=4)
        duthost.copy(content=patch_content, dest=tmpfile)

        # Run with 1-hour timeout (overrides default GCU timeout)
        cmds = f'config apply-patch {tmpfile}'
        pool, async_result = duthost.shell(cmds, module_ignore_errors=True,
                                           module_async=True)
        try:
            completed = wait_until(STRESS_TIME_BUDGET_SECONDS, 30, 0,
                                   lambda: async_result.ready())
            gcu_elapsed = time.time() - gcu_start

            if not completed:
                logger.error(
                    "Stress test: apply-patch did not complete within %ds, terminating",
                    STRESS_TIME_BUDGET_SECONDS
                )
                pytest.fail(
                    f"Stress test TIMEOUT: GCU apply-patch did not complete within "
                    f"{STRESS_TIME_BUDGET_SECONDS}s ({STRESS_TIME_BUDGET_SECONDS/3600:.0f}h) "
                    f"for {len(all_t1s)} T1s ({len(patch_data)} ops)"
                )

            apply_result = async_result.get()
        finally:
            pool.terminate()
            pool.join()

        if apply_result['rc'] != 0 or "Patch applied successfully" not in apply_result['stdout']:
            pytest.fail(
                f"Failed to apply stress patch after {gcu_elapsed:.1f}s: {apply_result['stdout']}"
            )
    finally:
        delete_tmpfile(duthost, tmpfile)

    # Report results
    time_per_t1 = gcu_elapsed / len(all_t1s)
    t1s_per_hour = 3600.0 / time_per_t1 if time_per_t1 > 0 else float('inf')

    logger.info("=" * 70)
    logger.info("STRESS TEST RESULTS")
    logger.info("=" * 70)
    logger.info(f"  T1 neighbors in patch:    {len(all_t1s)}")
    logger.info(f"  Total patch operations:   {len(patch_data)}")
    logger.info(f"  Wall-clock time:          {gcu_elapsed:.1f}s")
    logger.info(f"  Time per T1 (avg):        {time_per_t1:.1f}s")
    logger.info(f"  Projected T1s per hour:   {t1s_per_hour:.0f}")
    logger.info(f"  Budget:                   {STRESS_TIME_BUDGET_SECONDS}s (1 hour)")
    logger.info(f"  Within budget:            {'YES' if gcu_elapsed <= STRESS_TIME_BUDGET_SECONDS else 'NO'}")
    logger.info("=" * 70)

    # Fail if exceeded budget
    if gcu_elapsed > STRESS_TIME_BUDGET_SECONDS:
        pytest.fail(
            f"Stress test: GCU apply-patch took {gcu_elapsed:.1f}s for {len(all_t1s)} T1s, "
            f"exceeded 1-hour budget. Avg {time_per_t1:.1f}s/T1, "
            f"projected {t1s_per_hour:.0f} T1s/hour."
        )

    logger.info(
        f"Stress test PASSED: {len(all_t1s)} T1s added in {gcu_elapsed:.1f}s "
        f"({time_per_t1:.1f}s/T1, projected {t1s_per_hour:.0f}/hour)"
    )
