#!/bin/bash
stage_files=$(git diff --cached --name-only | grep "tests_mark_conditions*")
if [[ -z $stage_files ]];then
  exit 0
fi
chmod +x .hooks/pre-commit.py
python .hooks/pre-commit.py $stage_files
if [ $? != 0 ];then
    echo "The entries in tests/common/plugins/conditional_mark/tests_mark_conditions*.yaml are not sorted in alphabetic order."
    exit 1
else
    exit 0
fi
