#!/usr/bin/env python

# Supress warning
import warnings
warnings.filterwarnings("ignore")

import argparse
import json
import subprocess
import time
from tabulate import tabulate

from devutil.inv_helpers import HostManager
from devutil.ssh_utils import SSHClient
from devutil.task_runner import TaskRunner
import sys
sys.path.append("..")
from tests.common.connections import ConsoleHost
from tests.common.plugins.pdu_controller.snmp_pdu_controllers import get_pdu_controller

g_inv_mgr = None
g_task_runner = None
g_pdu_dict = {}


def run_cmd(cmd):
    '''
    @summary: Utility that runs a command in a subprocess
    @param cmd: Command to be run
    @return: stdout of the command run
    @return: stderr of the command run
    '''
    out = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
    stdout, stderr = out.communicate()
    return out.returncode, stdout, stderr


def build_global_vars(concurrency, inventory):
    global g_task_runner, g_inv_mgr
    g_task_runner = TaskRunner(max_worker=concurrency)
    g_inv_mgr = HostManager(inventory)


def retrieve_hosts(group, limit):
    global g_inv_mgr
    return g_inv_mgr.get_host_list(group, limit)


def get_pdu_info(pdu_host):
    global g_inv_mgr, g_pdu_dict

    if pdu_host in g_pdu_dict:
        return g_pdu_dict[pdu_host]

    hosts = retrieve_hosts('all', pdu_host)
    pdus=[]
    g_pdu_dict[pdu_host] = pdus
    for ph in pdu_host.split(','):
        if ph in hosts:
            pdu = hosts[ph]
            pdus.append(pdu)

    return pdus


def show_data_output(header, data, json_output=False):
    if json_output:
        print(json.dumps(sorted(data, key=lambda x: x['Host']), indent=4))
    else:
        print(tabulate(sorted(data, key=lambda x: x[0]), headers=header, tablefmt='grid'))


def action_list(parameters):
    hosts = parameters['hosts']
    header = ['Host', 'Ansible_host']
    data = []
    if parameters['json']:
        for name, vars in hosts.items():
            data.append(dict(zip(header, (name, vars['ansible_host']))))
    else:
        for name, vars in hosts.items():
            data.append((name, vars['ansible_host']))
    show_data_output(header, data, parameters['json'])


def action_ping(parameters):
    hosts = parameters['hosts']
    header = ['Host', 'Hostname', 'Ping result']
    data = []
    for name, vars in hosts.items():
        cmd = 'timeout 1 ping -q -c 1 -w 1 {}'.format(vars['ansible_host'])
        g_task_runner.submit_task(name + '|' + vars['ansible_host'], run_cmd, cmd=cmd)
    if parameters['json']:
        for name, result in g_task_runner.task_results():
            data.append(dict(zip(header, (name.split('|')[0], name.split('|')[1], 'Success' if result['result'][0] == 0 else "Fail"))))
    else:
        for name, result in g_task_runner.task_results():
            data.append((name.split('|')[0], name.split('|')[1], 'Success' if result['result'][0] == 0 else "Fail"))

    if parameters['ipv6']:
        for name, vars in hosts.items():
            if 'ansible_hostv6' in vars.keys():
                cmd = 'timeout 1 ping -6 -q -c 1 -w 1 {}'.format(vars['ansible_hostv6'])
                g_task_runner.submit_task(name + '|' + vars['ansible_hostv6'], run_cmd, cmd=cmd)
        if parameters['json']:
            for name, result in g_task_runner.task_results():
                data.append(dict(zip(header, (name.split('|')[0], name.split('|')[1], 'Success' if result['result'][0] == 0 else "Fail"))))
        else:
            for name, result in g_task_runner.task_results():
                data.append((name.split('|')[0], name.split('|')[1], 'Success' if result['result'][0] == 0 else "Fail"))

    show_data_output(header, data, parameters['json'])


def action_ssh(parameters):
    hosts = parameters['hosts']
    for _, vars in hosts.items():
        client = SSHClient()
        client.connect(hostname=vars['ansible_host'], username=vars['creds']['username'], passwords=vars['creds']['password'])
        client.posix_shell()


def action_console(parameters):
    hosts = parameters['hosts']
    # Todo: Retrieve console vars from conn_graph_fact
    for _, vars in hosts.items():
        console_host = ConsoleHost(console_type=vars['console_type'],
                                    console_host=vars['console_host'],
                                    console_port=vars['console_port'],
                                    sonic_username=vars['creds']['username'],
                                    sonic_password=vars['creds']['password'],
                                    console_username=vars['creds']['console_user'][vars['console_type']],
                                    console_password=vars['creds']['console_password'][vars['console_type']])
        console_host.posix_shell()


def pdu_action_on_dut(host, attrs, action):
    ret = { 'Host' : host, 'PDU status' : [], 'Summary' : [], 'Action' : action }
    pdu_name = attrs['pdu_host'] if 'pdu_host' in attrs else None
    if not pdu_name:
        ret['Summary'].append('DUT has no PDU configuration')
        return ret

    pdu_list = get_pdu_info(pdu_name)
    if not pdu_list:
        ret['Summary'].append('PDU not found in inventory')
        return ret

    for pdu_info in pdu_list:
        pdu_host = pdu_info['ansible_host'] if pdu_info and 'ansible_host' in pdu_info else None
        p_name = pdu_info['inventory_hostname'] if pdu_info and 'inventory_hostname' in pdu_info else None
        if not pdu_host or not p_name:
            ret['Summary'].append('No PDU IP or name')
            continue

        rec = { 'PDU' : p_name, 'PDU_IP' : pdu_host, 'status' : [] }
        ret['PDU status'].append(rec)

        controller = get_pdu_controller(pdu_host, host, pdu_info)

        if not controller:
            ret['Summary'].append('Failed to communicate with controller {}'.format(p_name))
            continue

        rec['status'] = controller.get_outlet_status()
        if action == 'off':
            for outlet in rec['status']:
                controller.turn_off_outlet(outlet['outlet_id'])
            rec['status'] = controller.get_outlet_status()
        elif action == 'on':
            for outlet in rec['status']:
                controller.turn_on_outlet(outlet['outlet_id'])
            rec['status'] = controller.get_outlet_status()
        elif action != 'status':
            ret['Summary'].append('Unsupported action {}.'.format(action))
            continue

    return ret


def action_pdu(parameters, action):
    hosts = parameters['hosts']
    data = []
    header = [ 'Host', 'Action', 'PDU status', 'Summary' ]
    for host, attrs in hosts.items():
        g_task_runner.submit_task(host, pdu_action_on_dut, host=host, attrs=attrs, action=action)

    for _, ret in g_task_runner.task_results():
        status = ret['result']
        if parameters['json']:
            data.append(status)
        else:
            data.append([ status[x] for x in header ])

    return header, data


def action_pdu_status(parameters):
    header, data = action_pdu(parameters, 'status')
    show_data_output(header, data, parameters['json'])


def action_pdu_off(parameters):
    header, data = action_pdu(parameters, 'off')
    show_data_output(header, data, parameters['json'])


def action_pdu_on(parameters):
    header, data = action_pdu(parameters, 'on')
    show_data_output(header, data, parameters['json'])


def action_pdu_reboot(parameters):
    header, data = action_pdu(parameters, 'off')
    # sleep 1 second to ensure there is gap between power off and on
    time.sleep(1)
    _, data_on = action_pdu(parameters, 'on')

    data = data + data_on
    show_data_output(header, data, parameters['json'])


def action_dispatcher(parameters):
    # Actions that can run simultaneously in different hosts
    parallel_actions = ['ssh_run_command']
    action = parameters['action'].__name__
    if action in parallel_actions:
        parallel_run(parameters)
    else:
        parameters['action'](parameters)


def parallel_run(parameters):
    action = parameters['action']
    cmd = parameters['cmd']
    hosts = parameters['hosts']
    if action.__name__ == 'ssh_run_command':
        for hostname, vars in hosts.items():
            args = {'hostname': vars['ansible_host'],
                    'username': vars['creds']['username'],
                    'passwords': vars['creds']['password'],
                    'cmd': cmd
                    }
            g_task_runner.submit_task(hostname, ssh_run_command, **args)
        for name, result in g_task_runner.task_results():
            print("task result for {} ===============>\n{}".format(name, str(result['result'][1])))

def ssh_run_command(hostname, username, passwords, cmd):
    client = SSHClient()
    client.connect(hostname=hostname, username=username, passwords=passwords)
    return client.run_command(cmd)

def validate_args(args):
    if args.action == 'run' and args.cmd == '':
        print("command is missing for run action")
        return False
    return True

def main():
    parser = argparse.ArgumentParser(description='Device utilities')
    parser.add_argument('-6', '--ipv6', help='Include IPv6', action='store_true',
                        required=False, default=False)
    parser.add_argument('-a', '--action',
                        help='Action towards host(s): list, ping, run, ssh, console, pdu_status, pdu_on, pdu_off, pdu_reboot, default list',
                        type=str, required=False, default='list',
                        choices=['list', 'ping', 'ssh', 'console', 'run', 'pdu_status', 'pdu_on', 'pdu_off', 'pdu_reboot'])
    parser.add_argument('--cmd', help="Command to run on all hosts",
                        type=str, required=False)
    parser.add_argument('-g', '--group', help='Groups: all, sonic, ptf, pdu, default all',
                        type=str, required=False, default='all')
    parser.add_argument('-i', '--inventory', help='Categories: lab, etc, default lab',
                        type=str, required=False, default='lab')
    parser.add_argument('-l', '--limit', help='Host: limit to a single dut host name, default all',
                        type=str, required=False)
    parser.add_argument('-u', '--user', help='User: user account to login to host with, default admin',
                        type=str, required=False, default='admin')
    parser.add_argument('-c', '--concurrency', help='Concurrency: the max concurrency for tasks that can run simultaneously, default 1',
                        type=int, required=False, default=1)
    parser.add_argument('-j', '--json', help='json output', action='store_true',
                        required=False, default=False)

    args = parser.parse_args()
    if not validate_args(args):
        return
    build_global_vars(args.concurrency, args.inventory);
    hosts = retrieve_hosts(args.group, args.limit)
    actions = { 'list' : action_list,
                'ping' : action_ping,
                'ssh' : action_ssh,
                'console' : action_console,
                'run' : ssh_run_command,
                'pdu_status' : action_pdu_status,
                'pdu_off' : action_pdu_off,
                'pdu_on' : action_pdu_on,
                'pdu_reboot' : action_pdu_reboot,
              }
    parameters = { 'hosts' : hosts,
                   'limit' : args.limit,
                   'action' : actions[args.action],
                   'user' : args.user,
                   'ipv6' : args.ipv6,
                   'cmd': args.cmd,
                   'json' : args.json,
                 }
    action_dispatcher(parameters)


if __name__ == '__main__':
    main()
