---
- name: Remove virtual NUT topology
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  vars_files:
    - group_vars/all/creds.yml
    - group_vars/lab/secrets.yml
  roles:
    - role: testbed/nut-vtopo-remove
