# Please update the actual username and password according to your lab configuration

ansible_ssh_user: admin
ansible_ssh_pass: pxq123
fanout_mlnx_user: admin
fanout_mlnx_password: pxq123
fanout_sonic_user: admin
fanout_sonic_password: pxq123

# Credential for accessing the network cli interface
fanout_network_user: netadmin
fanout_network_password: netpassword

# Credential for accessing the Linux shell
fanout_shell_user: shelladmin
fanout_shell_password: shellpassword

#fanout_tacacs_sonic_user: admin
#fanout_tacacs_sonic_password: password
