# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/gnmi/protos/gnoi/types/types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n(tests/gnmi/protos/gnoi/types/types.proto\x12\ngnoi.types\x1a google/protobuf/descriptor.proto"\x89\x01\n\x08HashType\x12/\n\x06method\x18\x01 \x01(\x0e\x32\x1f.gnoi.types.HashType.HashMethod\x12\x0c\n\x04hash\x18\x02 \x01(\x0c">\n\nHashMethod\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\n\n\x06SHA256\x10\x01\x12\n\n\x06SHA512\x10\x02\x12\x07\n\x03MD5\x10\x03":\n\x04Path\x12\x0e\n\x06origin\x18\x02 \x01(\t\x12"\n\x04\x65lem\x18\x03 \x03(\x0b\x32\x14.gnoi.types.PathElem"p\n\x08PathElem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x03key\x18\x02 \x03(\x0b\x32\x1d.gnoi.types.PathElem.KeyEntry\x1a*\n\x08KeyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"h\n\x0b\x43redentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\tcleartext\x18\x02 \x01(\tH\x00\x12&\n\x06hashed\x18\x03 \x01(\x0b\x32\x14.gnoi.types.HashTypeH\x00\x42\n\n\x08password*1\n\nL3Protocol\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04IPV4\x10\x01\x12\x08\n\x04IPV6\x10\x02:3\n\x0cgnoi_version\x12\x1c.google.protobuf.FileOptions\x18\xea\x07 \x01(\tB"Z github.com/openconfig/gnoi/typesb\x06proto3'
)

_L3PROTOCOL = DESCRIPTOR.enum_types_by_name["L3Protocol"]
L3Protocol = enum_type_wrapper.EnumTypeWrapper(_L3PROTOCOL)
UNSPECIFIED = 0
IPV4 = 1
IPV6 = 2

GNOI_VERSION_FIELD_NUMBER = 1002
gnoi_version = DESCRIPTOR.extensions_by_name["gnoi_version"]

_HASHTYPE = DESCRIPTOR.message_types_by_name["HashType"]
_PATH = DESCRIPTOR.message_types_by_name["Path"]
_PATHELEM = DESCRIPTOR.message_types_by_name["PathElem"]
_PATHELEM_KEYENTRY = _PATHELEM.nested_types_by_name["KeyEntry"]
_CREDENTIALS = DESCRIPTOR.message_types_by_name["Credentials"]
_HASHTYPE_HASHMETHOD = _HASHTYPE.enum_types_by_name["HashMethod"]
HashType = _reflection.GeneratedProtocolMessageType(
    "HashType",
    (_message.Message,),
    {
        "DESCRIPTOR": _HASHTYPE,
        "__module__": "tests.gnmi.protos.gnoi.types.types_pb2"
        # @@protoc_insertion_point(class_scope:gnoi.types.HashType)
    },
)
_sym_db.RegisterMessage(HashType)

Path = _reflection.GeneratedProtocolMessageType(
    "Path",
    (_message.Message,),
    {
        "DESCRIPTOR": _PATH,
        "__module__": "tests.gnmi.protos.gnoi.types.types_pb2"
        # @@protoc_insertion_point(class_scope:gnoi.types.Path)
    },
)
_sym_db.RegisterMessage(Path)

PathElem = _reflection.GeneratedProtocolMessageType(
    "PathElem",
    (_message.Message,),
    {
        "KeyEntry": _reflection.GeneratedProtocolMessageType(
            "KeyEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _PATHELEM_KEYENTRY,
                "__module__": "tests.gnmi.protos.gnoi.types.types_pb2"
                # @@protoc_insertion_point(class_scope:gnoi.types.PathElem.KeyEntry)
            },
        ),
        "DESCRIPTOR": _PATHELEM,
        "__module__": "tests.gnmi.protos.gnoi.types.types_pb2"
        # @@protoc_insertion_point(class_scope:gnoi.types.PathElem)
    },
)
_sym_db.RegisterMessage(PathElem)
_sym_db.RegisterMessage(PathElem.KeyEntry)

Credentials = _reflection.GeneratedProtocolMessageType(
    "Credentials",
    (_message.Message,),
    {
        "DESCRIPTOR": _CREDENTIALS,
        "__module__": "tests.gnmi.protos.gnoi.types.types_pb2"
        # @@protoc_insertion_point(class_scope:gnoi.types.Credentials)
    },
)
_sym_db.RegisterMessage(Credentials)

if _descriptor._USE_C_DESCRIPTORS == False:
    google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(gnoi_version)

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z github.com/openconfig/gnoi/types"
    _PATHELEM_KEYENTRY._options = None
    _PATHELEM_KEYENTRY._serialized_options = b"8\001"
    _L3PROTOCOL._serialized_start = 510
    _L3PROTOCOL._serialized_end = 559
    _HASHTYPE._serialized_start = 91
    _HASHTYPE._serialized_end = 228
    _HASHTYPE_HASHMETHOD._serialized_start = 166
    _HASHTYPE_HASHMETHOD._serialized_end = 228
    _PATH._serialized_start = 230
    _PATH._serialized_end = 288
    _PATHELEM._serialized_start = 290
    _PATHELEM._serialized_end = 402
    _PATHELEM_KEYENTRY._serialized_start = 360
    _PATHELEM_KEYENTRY._serialized_end = 402
    _CREDENTIALS._serialized_start = 404
    _CREDENTIALS._serialized_end = 508
# @@protoc_insertion_point(module_scope)
