#!/bin/sh
python tests/common/plugins/conditional_mark/hooks/pre-commit.py
if [ $? != 0 ];then
    echo "Pleace check the order in tests/common/plugins/conditional_mark/tests_mark_conditions*.yaml"
    exit 1
else
    exit 0
fi