#!/bin/sh
stage_files=$(git diff --cached --name-only | grep "tests_mark_conditions*")
if test ${#stage_files} -eq 0;then
  exit 0
fi
chmod +x tests/common/plugins/conditional_mark/hooks/pre-commit.py
python tests/common/plugins/conditional_mark/hooks/pre-commit.py $stage_files
if [ $? != 0 ];then
    echo "Pleace check the order in tests/common/plugins/conditional_mark/tests_mark_conditions*.yaml"
    exit 1
else
    exit 0
fi
