
arg_defaults = {
  "--ignore-tcmap-errors": 0,
  "--tclist-map": None,
  "--tclist-bucket": None,
  "--tclist-file": [],
  "--tclist-file-exclude": [],
  "--tclist-csv": [],
  "--tclist-csv-exclude": [],
  "--logs-path": None,
  "--file-mode": False,
  "--quick-test": False,
  "--email": None,
  "--email-subject": "Run Report",
  "--email-attachments": 0,
  "--skip-tgen": False,
  "--tgen-module-init": 1,
  "--topology-check": ["module"],
  "--load-config-method": "none",
  "--skip-init-config": False,
  "--skip-load-config": "module",
  "--load-image": "onie",
  "--skip-verify-config": "none",
  "--ignore-dep-check": 0,
  "--memory-check": "none",
  "--syslog-check": "err",
  "--save-sairedis": "none",
  "--faster-init": 1,
  "--faster-cli": 1,
  "--port-init-wait": 300,
  "--reboot-wait": 0,
  "--fetch-core-files": "session",
  "--get-tech-support": "onfail-epilog",
  "--tc-max-timeout": 600,
  "--module-init-max-timeout": 1200,
  "--results-prefix": None,
  "--results-compare": None,
  "--exclude-devices": None,
  "--include-devices": None,
  "--run-progress-report": 0,
  "--env": [],
  "--random-order": 1,
  "--repeat-test": ["", 1],
  "--rps-reboot": None,
  "--pde": False,
  "--community-build": "none",
  "--tryssh": 0,
  "--first-test-only": False,
  "--config-profile": None,
  "--build-url": None,
  "--libsai-url": None,
  "--clear-tech-support": 0,
  "--module-epilog-tgen-cleanup": 1,
  "--module-epilog": 1,
  "--graceful-exit": 1,
  "--reuse-results": "none",
  "--link-param": [],
  "--dev-prop": [],
  "--dev-param": [],
  "--change-section": [],
  "--ixserver": [],
  "--ui-type": "click",
  "--breakout-mode": "native",
  "--speed-mode": "configured",
  "--ifname-type": "native",
  "--mgmt-vrf": 0
}

def get_default(name, default):
    if name in arg_defaults:
        return arg_defaults[name]
    return default

def get_default_all():
    return sorted(arg_defaults.items())

