
tacacs:
  hosts: [{ip: 10.29.158.58, username: rraghav, password: roZes@123,
           timeout: 5, passkey: testsonic, tcp_port: 49, auth_type: pap, priority: 1},
          {ip: 10.29.158.43, username: rraghav, password: roZes123,
           timeout: 5, passkey: testsonic, tcp_port: 49, auth_type: pap, priority: 2},
           {ip: 10.29.158.60, username: rraghav, password: roZes@123,
           timeout: 5, passkey: testsonic, tcp_port: 49, auth_type: pap, priority: 3},
          {ip: 172.27.147.156, username: rraghav, password: roZes123,
           timeout: 5, passkey: testsonic, tcp_port: 49, auth_type: pap, priority: 4},
          {ip: 10.2.3.4, username: root, password: lvl7india,
           timeout: 5, passkey: testsonic, tcp_port: 49, auth_type: pap, priority: 5},
          {ip: 10.2.3.5, username: root, password: lvl7india,
           timeout: 5, passkey: testsonic, tcp_port: 49, auth_type: pap, priority: 6},
          {ip: 10.2.3.6, username: root, password: lvl7india,
           timeout: 5, passkey: testsonic, tcp_port: 49, auth_type: pap, priority: 7},
          {ip: 10.2.3.7, username: root, password: lvl7india,
           timeout: 5, passkey: testsonic, tcp_port: 49, auth_type: pap, priority: 8}
           ]
radius:
  ro_user: {username: test1, password: password, password1: test}
