#!/bin/bash

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Workaround to ensure that if we are running on OS X with a homebrew installed
# GNU sed then we can still run sed.
runsed() {
  if hash gsed 2>/dev/null; then
    gsed "$@"
  else
    sed "$@"
  fi
}

PACKAGE_NAME=gostructs

git clone --depth 1 https://github.com/openconfig/public.git

go get -u github.com/openconfig/ygot
go get -t -d $GOPATH/src/github.com/openconfig/ygot/...

mkdir deps
cp  $GOPATH/src/github.com/openconfig/ygot/demo/getting_started/yang/{ietf,iana}* deps
go run $GOPATH/src/github.com/openconfig/ygot/generator/generator.go \
  -path=public,deps \
  -output_file=$PACKAGE_NAME.go \
  -package_name=$PACKAGE_NAME -compress_paths=false \
  -generate_fakeroot -fakeroot_name=device \
  -exclude_modules=ietf-interfaces \
  -generate_append \
  -generate_getters \
  public/release/models/network-instance/openconfig-network-instance.yang \
  public/release/models/optical-transport/openconfig-optical-amplifier.yang \
  public/release/models/optical-transport/openconfig-terminal-device.yang \
  public/release/models/optical-transport/openconfig-transport-line-protection.yang \
  public/release/models/optical-transport/openconfig-channel-monitor.yang \
  public/release/models/platform/openconfig-platform.yang \
  public/release/models/policy/openconfig-routing-policy.yang \
  public/release/models/lacp/openconfig-lacp.yang \
  public/release/models/system/openconfig-system.yang \
  public/release/models/system/openconfig-aaa.yang \
  public/release/models/types/openconfig-types.yang \
  public/release/models/types/openconfig-inet-types.yang \
  public/release/models/types/openconfig-yang-types.yang \
  public/release/models/lldp/openconfig-lldp.yang \
  public/release/models/stp/openconfig-spanning-tree.yang \
  public/release/models/interfaces/openconfig-interfaces.yang \
  public/release/models/interfaces/openconfig-if-ip.yang \
  public/release/models/interfaces/openconfig-if-aggregate.yang \
  public/release/models/interfaces/openconfig-if-ethernet.yang \
  public/release/models/interfaces/openconfig-if-ip-ext.yang
runsed -i 's/This package was generated by.*/This package was generated by github.com\/openconfig\/gnmitest/g' $PACKAGE_NAME.go
gofmt -w -s $PACKAGE_NAME.go
rm -rf public deps
