steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Set up Python 3'

- script: |
    set -x

    python -m pip install natsort

    python ./.azure-pipelines/dependency_check/dependency_check.py tests
    if [[ $? -ne 0 ]]; then
      echo "##vso[task.complete result=Failed;]Condition check failed."
      exit 1
    fi
  displayName: "Dependency Check"
