steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python 3'

- script: |
    set -x

    python -m pip install natsort

    python ./.azure-pipelines/markers_check/markers_check.py tests
    if [[ $? -ne 0 ]]; then
      echo "##vso[task.complete result=Failed;]Markers check fails."
      exit 1
    fi
  displayName: "Markers Check"
