steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Set up Python 3'

- script: |
    python -m pip install ipaddr natsort PyYAML six

    python ./ansible/scripts/meta/meta_validator.py -r errors -c .azure-pipelines/meta_validator.yml
    if [[ $? -ne 0 ]]; then
      echo "##vso[task.complete result=Failed;]Meta check fails."
      exit 1
    fi
  displayName: "Meta Check"
