from .args.populate_fdb_args import add_populate_fdb_args
from tests.common.fixtures.populate_fdb import populate_fdb

# FDB pytest arguments


def pytest_addoption(parser):
    """
        Adds option to FDB pytest and option to specify Spytst junit file path.

        Args:
            parser: pytest parser object

        Returns:
            None
    """
    add_populate_fdb_args(parser)

    parser.addoption(
        "--spytest-junit-xml",
        action="store",
        dest="spytest_xmlpath",
        help="the junit xml file generated by Spytest."
    )

    parser.addoption(
        "--spytest-updated-junit-xml",
        action="store",
        dest="spytest_updated_xmlpath",
        help="store path of the updated junit xml file generated by test_add_property_spytest_junit_xml.")
