---
ansible_user: root
ansible_password: Embe1mpls
ansible_become_password: Embe1mpls

# Use the following username/password variables to login to vm hosts
# instead of the default variables (defined above).
vm_host_user: root
vm_host_password: Embe1mpls
vm_host_become_password: Embe1mpls
